### ISSUE TITLE
Can't add an instance into a group

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#10]
I successfully created an instance. 

On the /manage/instances page, I can click on the edit button which display the `Update instance properties` form. 

When I try to add the instance into a group I get an "internal error" message and the following log:

```
2016-10-28 21:30:09,088 temboard[20449]: [temboard] INFO: 200 GET /json/manage/instance/0.0.0.0/2345 (90.78.76.123) 63.16ms
2016-10-28 21:30:17,140 temboard[20449]: [temboard] INFO: Posting instance.
2016-10-28 21:30:17,184 temboard[20449]: [temboard] DEBUG: {u'pg_port': u'5434', u'new_agent_address': u'0.0.0.0', u'hostname': u'redtail.taadeem.net', u'pg_data': u'/var/lib/postgresql/9.5/main', u'agent_key': u'NOTMYACTUALKEY', u'memory_size': u'2063396864', u'groups': [u'plop'], u'plugins': [u'activity', u'dashboard', u'supervision', u'settings'], u'new_agent_port': u'2345', u'pg_version': u'PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609, 64-bit', u'cpu': u'1'}
2016-10-28 21:30:17,187 temboard[20449]: [temboard] DEBUG: Traceback (most recent call last):
2016-10-28 21:30:17,188 temboard[20449]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/handlers/manage/instance.py", line 128, in post_instance
2016-10-28 21:30:17,189 temboard[20449]: [temboard] DEBUG:     instance_groups = get_groups_by_instance(self.db_session, instance.agent_address, instance.agent_port)
2016-10-28 21:30:17,190 temboard[20449]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/application.py", line 383, in get_groups_by_instance
2016-10-28 21:30:17,190 temboard[20449]: [temboard] DEBUG:     return session.query(InstanceGroups).filter(InstanceGroups.agent_address == unicode(agent_address), InstanceGroups.agent_port == agent_port).order_by(InstanceGroup.group_name).all()
2016-10-28 21:30:17,191 temboard[20449]: [temboard] DEBUG: NameError: global name 'InstanceGroup' is not defined
2016-10-28 21:30:17,191 temboard[20449]: [temboard] ERROR: global name 'InstanceGroup' is not defined
2016-10-28 21:30:17,192 temboard[20449]: [temboard] INFO: Failed.
```

**Comment by daamien** [comment]
FTR This occurs when  I'm update an instance. Everything is fine when I add the instance into a group during the instance creation process

**Comment by julmon** [comment]
Hi Damien,

Can I close this issue ? This commit https://github.com/dalibo/temboard/commit/8948f6d249d30448d3e2f9334740f4725fc233a3 should fix it.
