### ISSUE TITLE
ProgrammingError: invalid dsn: invalid connection option "channel_binding"

### ISSUE THREAD

**Issue by xroman70** [dalibo/temboard#1019]
While running : systemctl status temboard-agent@12-main 
the following output is shown

```
Jul 02 16:04:04 db2.io env[26377]:   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
Jul 02 16:04:04 db2.io env[26377]:     dsn = _ext.make_dsn(dsn, **kwargs)
Jul 02 16:04:04 db2.io env[26377]:   File "/usr/local/lib/python2.7/dist-packages/psycopg2/extensions.py", line 153, in make_dsn
Jul 02 16:04:04 db2.io env[26377]:     parse_dsn(dsn)
Jul 02 16:04:04 db2.io env[26377]: ProgrammingError: invalid dsn: invalid connection option "channel_binding"
Jul 02 16:04:04 db2.io env[26377]: invalid dsn: invalid connection option "channel_binding"
Jul 02 16:04:04 db2.io env[26377]: Traceback (most recent call last):
Jul 02 16:04:04 db2.io env[26377]:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/plugins/monitoring/probes.py", line 871, in run
Jul 02 16:04:04 db2.io env[26377]:     dsn = parse_dsn(get_primary_conninfo(conn))
Jul 02 16:04:04 db2.io env[26377]: ProgrammingError: invalid dsn: invalid connection option "channel_binding"
```

**Comment by daamien** [comment]
@xroman70  This issue has been inactive for several weeks. Unless you can provide new elements to the discussion, we will close it in a few days.
