### ISSUE TITLE
Temboard agent unable to request public key from server.

### ISSUE THREAD

**Issue by vaibhavpandey-bista** [dalibo/temboard#1180]
We updated ssl cert for our server.
Since then while auto configuring temboard agent, it suggests us to fetch UI signing key using
`sudo -u postgres temboard-agent -c /etc/temboard-agent/11/main/temboard-agent.conf fetch-key`

and when we run this command, it gives us this:
```
INFO:  fetch_key: Requesting public key from https://serverdomain.com:8888.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3/dist-packages/temboardagent/cli/app.py", line 135, in main
            return command.main(args)
          File "/usr/lib/python3/dist-packages/temboardagent/cli/fetch_key.py", line 42, in main
            response.raise_for_status()
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/http.py", line 175, in raise_for_status
            raise TemboardHTTPError(self)
        temboardagent.toolkit.http.TemboardHTTPError: 405: Method Not Allowed
ERROR:  app: temboardagent version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
```

**Comment by bersace** [comment]
Hi @vaibhavpandey-bista , thanks for reaching.

Did you upgrade temBoard server to 8.0 before upgrading agent ? Can you share DEBUG logs from temBoard server ?

**Comment by bersace** [comment]
Closing in favor of #1232
