### ISSUE TITLE
Temboard-agent upgrade to 8.0 issue

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#1183]
Hi,

I'm facing an error during temboard-agent upgrade to version 8.0.
The temboard server upgraded without any problem.
But for the agent, it is a little bit more difficult...

According to [the documentation](https://temboard.readthedocs.io/en/latest/agent_upgrade/#from-711-to-80), the configuration file has to be updated.
In my case (coming from an old install of the first versions of Temboard, upgraded in different versions up to 7.11 recently), my configuration file is /etc/temboard-agent/.../tembard-agent.conf.d/auto.conf and not /etc/temboard-agent/.../tembard-agent.conf
In that file, I have removed quotes in the pg_ctl parameter.
But I don't find any parameter ui_url.

When I try to execute the following command:
`temboard-agent --config=/etc/temboard-agent/12/main/temboard-agent.conf.d/auto.conf fetch-key`
I get the following error:

INFO:  app: Using config file /etc/temboard-agent/12/main/temboard-agent.conf.d/auto.conf.
ERROR:  app: Unhandled error:
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
	    retcode = self.main(argv, environ)
	  File "/usr/lib/python3/dist-packages/temboardagent/cli/app.py", line 135, in main
	    return command.main(args)
	  File "/usr/lib/python3/dist-packages/temboardagent/cli/fetch_key.py", line 33, in main
	    ui_url_raw = self.app.config.temboard.ui_url.rstrip('/')
	AttributeError: 'NoneType' object has no attribute 'rstrip'
ERROR:  app: temboardagent version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!

The temboard-agent service restarts correctly  without any error, but in Temboard IU, on the instance, I get the error: 
Error
Failed to contact agent NVLDBDFSQLBD1.ign.fr:2345: [Errno 111] Connection refused. Is it running?

How can I solve this issue?

Thanks in advance for your help,

Cedric

**Comment by ced75** [comment]
Hi,

That did it, but I also had to copy signing-public.pem file from /etc/temboard-agent/12/main/temboard-agent.conf.d/ to /etc/temboard-agent/12/main/ to restart the service.

Thanks for the help.
