### ISSUE TITLE
error when fetching signing key while upgrading temboard agent v7.8 to 8.0

### ISSUE THREAD

**Issue by fathoniinsansilmi** [dalibo/temboard#1186]
[postgres@postgre01 ~]$ temboard-agent --config=/etc/temboard-agent/temboard-agent.conf fetch-key
INFO:  app: Using config file /etc/temboard-agent/temboard-agent.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/app.py", line 135, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/fetch_key.py", line 33, in main
            ui_url_raw = self.app.config.temboard.ui_url.rstrip('/')
        AttributeError: 'NoneType' object has no attribute 'rstrip'
ERROR:  app: temboardagent version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!

**Comment by pirlgon** [comment]
Hello,
It looks like you didn't add the ui_url parameter in temboard-agent config file. [upgrade agent](https://temboard.readthedocs.io/en/latest/agent_upgrade/)

**Comment by fathoniinsansilmi** [comment]
> Hello, It looks like you didn't add the ui_url parameter in temboard-agent config file. [upgrade agent](https://temboard.readthedocs.io/en/latest/agent_upgrade/)

[postgres@postgre01 ~]$ cat /etc/temboard-agent/temboard-agent.conf |grep ui_url
ui_url = https://10.10.2.41:8888

already added before sir

**Comment by pirlgon** [comment]
did you put it in the temboard section of conf file? the fetch-key seems unable to access the value.

**Comment by fathoniinsansilmi** [comment]
> did you put it in the temboard section of conf file? the fetch-key seems unable to access the value.

ok sir problem solved, but i have another error when running tusk flush
temboard-agent --config=/etc/temboard-agent/temboard-agent.conf fetch-key
INFO:  app: Using config file /etc/temboard-agent/temboard-agent.conf.
INFO:  fetch_key: Requesting public key from https://10.10.2.41:8888.
INFO:  fetch_key: Validating PEM data.
INFO:  fetch_key: /etc/temboard-agent/signing-public.pem updated from https://10.10.2.41:8888.
INFO:  fetch_key: Please reload agent service if running.
[postgres@postgre01 ~]$ temboard-agent --config=/etc/temboard-agent/temboard-agent.conf tasks flush
INFO:  app: Using config file /etc/temboard-agent/temboard-agent.conf.
INFO:  taskmanager: Flushed 3 tasks.
[postgres@postgre01 ~]$ exit
logout
[root@postgre01 temboard-agent]# systemctl start temboard-agent
Failed to start temboard-agent.service: Unit temboard-agent.service not found.
[root@postgre01 ~]# systemctl status temboard-agent
● temboard-agent.service
   Loaded: not-found (Reason: Unit temboard-agent.service not found.)
   Active: failed (thawing) (Result: exit-code) since Fri 2022-12-02 14:01:40 WIB; 2h 32min ago
 Main PID: 4060802 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by fathoniinsansilmi** [comment]
[root@postgre01 data]# systemctl status temboard-agent@12-data.service
● temboard-agent@12-data.service - PostgreSQL Remote Control Agent 12/data
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2022-12-06 12:20:07 WIB; 6min ago
  Process: 17394 ExecStart=/usr/bin/temboard-agent -c /etc/temboard-agent/12/data/temboard-agent.conf (co>
 Main PID: 17394 (code=exited, status=1/FAILURE)

Dec 06 12:20:06 postgre01.lab.local systemd[1]: Started PostgreSQL Remote Control Agent 12/data.
Dec 06 12:20:07 postgre01.lab.local temboard-agent[17394]: INFO:  app: Using config file /etc/temboard-ag>
Dec 06 12:20:07 postgre01.lab.local temboard-agent[17394]: CRITICAL:  app: You must not quote string in c>
Dec 06 12:20:07 postgre01.lab.local systemd[1]: temboard-agent@12-data.service: Main process exited, code>
Dec 06 12:20:07 postgre01.lab.local systemd[1]: temboard-agent@12-data.service: Failed with result 'exit-

**Comment by fathoniinsansilmi** [comment]
> @fathoniinsansilmi temBoard 8 dropped `temboard-agent.service` unit file, thus the message:
> 
> ```
> Loaded: not-found (Reason: Unit temboard-agent.service not found.)
> ```
> 
> I suggest to move `/etc/temboard-agent` directory to `/etc/temboard-agent/<cluster_name>` and use parameterized unit:
> 
> ```
> systemctl enable --now temboard-agent@<cluster_name>
> ```

[root@postgre01 data]# systemctl status temboard-agent@12-data.service
● temboard-agent@12-data.service - PostgreSQL Remote Control Agent 12/data
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2022-12-06 12:20:07 WIB; 6min ago
  Process: 17394 ExecStart=/usr/bin/temboard-agent -c /etc/temboard-agent/12/data/temboard-agent.conf (co>
 Main PID: 17394 (code=exited, status=1/FAILURE)

Dec 06 12:20:06 postgre01.lab.local systemd[1]: Started PostgreSQL Remote Control Agent 12/data.
Dec 06 12:20:07 postgre01.lab.local temboard-agent[17394]: INFO:  app: Using config file /etc/temboard-ag>
Dec 06 12:20:07 postgre01.lab.local temboard-agent[17394]: CRITICAL:  app: You must not quote string in c>
Dec 06 12:20:07 postgre01.lab.local systemd[1]: temboard-agent@12-data.service: Main process exited, code>
Dec 06 12:20:07 postgre01.lab.local systemd[1]: temboard-agent@12-data.service: Failed with result 'exit-

i just did what u suggested, so now the config file is in dir /etc/temboard-agent/12/data, i just did restarting agent also

**Comment by bersace** [comment]
Hi, as documented in upgrade documentation, you must remove quotes around pg_ctl parameter in configuration file. https://temboard.readthedocs.io/en/latest/agent_upgrade/#from-711-to-80

**Comment by fathoniinsansilmi** [comment]
> Hi, as documented in upgrade documentation, you must remove quotes around pg_ctl parameter in configuration file. https://temboard.readthedocs.io/en/latest/agent_upgrade/#from-711-to-80

[temboard]
# Bind port.
port = 2345
# Bind address.
address = 0.0.0.0
# User & password file.
users = users
# Plugins in use.
plugins = ["monitoring", "dashboard", "pgconf", "administration", "activity", "statements", "maintenance"]
# SSL: certificat file path (.pem)
ssl_cert_file = /etc/pki/tls/certs/temboard-agent.pem
# SSL: private key file path (.key)
ssl_key_file = /etc/pki/tls/private/temboard-agent.key
# Hostname must be an unique and valid FQDN : e.g. db1.mydomain.foo
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
# hostname = db1.mydomain.foo
# Key
key = 214081c54a464274ca3c4de333044232
home=/var/lib/temboard-agent
ui_url = https://10.10.2.41:8888

[postgresql]
# Unix socket path.
host = /var/run/postgresql
# PG port number.
port = 5432
# Super-user name.
user = postgres
# Super-user password.
# password =
# Default database.
dbname = postgres
# Instance name.
instance = main

[logging]
# Available methods for logging: stderr, syslog or file
method = file
# Syslog facility.
# facility = local0
# Log destination, should be /dev/log for syslog on Linux system.
# When using file logging method, this is referencing the log file path.
destination = /var/log/temboard-agent/temboard-agent.log
# Log level, can be: DEBUG, INFO, WARNING, ERROR or CRITICAL.
level = INFO

### PLUGINS ###
[dashboard]
# Dashboard plugin part
# Interval, in second, between each run of the process collecting
# data used to render the dashboard. Default: 2
# scheduler_interval = 2
# Number of record to keep. Default: 150
# history_length = 150

[monitoring]
# Monitoring plugin part.
# DB name list (comma separator) to supervise. * for all.
dbnames = *
# List of probes to run, comma separator, * for all.
# Available probes: bgwriter,blocks,btree_bloat,cpu,db_size,filesystems_size,heap_bloat,loadavg,locks,memory,process,replication_connection,replication_lag,sessions,tblspc_size,temp_files_size_delta,wal_files,xacts
# when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
probes = *
# Interval, in second, between each run of the process executing
# the probes. Default: 60
# scheduler_interval = 60

[administration]
# External command used for start/stop PostgreSQL.
# This commands actually works on Debian jessie.
pg_ctl = /usr/pgsql-10/bin/pg_ctl %s -D /var/lib/pgsql/10/data -m fast

[statements]
# Statements plugin part.
# DB name hosting pg_stat_statements view (the one where the extension has
# been created with "CREATE EXTENSION")
dbname = postgres

**Comment by fathoniinsansilmi** [comment]
> Hi, as documented in upgrade documentation, you must remove quotes around pg_ctl parameter in configuration file. https://temboard.readthedocs.io/en/latest/agent_upgrade/#from-711-to-80

[temboard]
# Bind port.
port = 2345
# Bind address.
address = 0.0.0.0
# User & password file.
users = users
# Plugins in use.
plugins = ["monitoring", "dashboard", "pgconf", "administration", "activity", "statements", "maintenance"]
# SSL: certificat file path (.pem)
ssl_cert_file = /etc/pki/tls/certs/temboard-agent.pem
# SSL: private key file path (.key)
ssl_key_file = /etc/pki/tls/private/temboard-agent.key
# Hostname must be an unique and valid FQDN : e.g. db1.mydomain.foo
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
# hostname = db1.mydomain.foo
# Key
key = 214081c54a464274ca3c4de333044232
home=/var/lib/temboard-agent
ui_url = https://10.10.2.41:8888

[postgresql]
# Unix socket path.
host = /var/run/postgresql
# PG port number.
port = 5432
# Super-user name.
user = postgres
# Super-user password.
# password =
# Default database.
dbname = postgres
# Instance name.
instance = main

[logging]
# Available methods for logging: stderr, syslog or file
method = file
# Syslog facility.
# facility = local0
# Log destination, should be /dev/log for syslog on Linux system.
# When using file logging method, this is referencing the log file path.
destination = /var/log/temboard-agent/temboard-agent.log
# Log level, can be: DEBUG, INFO, WARNING, ERROR or CRITICAL.
level = INFO

### PLUGINS ###
[dashboard]
# Dashboard plugin part
# Interval, in second, between each run of the process collecting
# data used to render the dashboard. Default: 2
# scheduler_interval = 2
# Number of record to keep. Default: 150
# history_length = 150

[monitoring]
# Monitoring plugin part.
# DB name list (comma separator) to supervise. * for all.
dbnames = *
# List of probes to run, comma separator, * for all.
# Available probes: bgwriter,blocks,btree_bloat,cpu,db_size,filesystems_size,heap_bloat,loadavg,locks,memory,process,replication_connection,replication_lag,sessions,tblspc_size,temp_files_size_delta,wal_files,xacts
# when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
probes = *
# Interval, in second, between each run of the process executing
# the probes. Default: 60
# scheduler_interval = 60

[administration]
# External command used for start/stop PostgreSQL.
# This commands actually works on Debian jessie.
pg_ctl = /usr/pgsql-10/bin/pg_ctl %s -D /var/lib/pgsql/10/data -m fast

[statements]
# Statements plugin part.
# DB name hosting pg_stat_statements view (the one where the extension has
# been created with "CREATE EXTENSION")
dbname = postgres

this my config, i did remove the quotes from pg_ctl

**Comment by bersace** [comment]
Do you have temboard-agent.conf.d/*.conf files ? Can you share DEBUG level messages ?

**Comment by fathoniinsansilmi** [comment]
yes i have  temboard-agent.conf.d/auto.conf, which one is the right destination of config file?
/etc/temboard-agent/temboard-agent.conf?
/etc/temboard-agent/12/data/temboard-agent.conf?
or /etc/temboard-agent/12/data/ temboard-agent.conf.d/auto.conf?

**Comment by bersace** [comment]
Hi,

- temboard-agent.conf is read first.
- then temboard-agent.conf.d/*.conf files are read using C sort order.

If that helps you, I suggest to merge de file. temBoard 8 does not produce auto_configure.sh anymore.

**Comment by fathoniinsansilmi** [comment]
what do u mean about merge de file? do i need to remove existing auto.conf?

**Comment by bersace** [comment]
Hi @fathoniinsansilmi . Which UNIX user owns .db files in temBoard's home ?

**Comment by bersace** [comment]
Thanks. What is the output of `lsof server_tasks.db` ?

**Comment by bersace** [comment]
Thanks. What is the output of `lsof server_tasks.db` ?

**Comment by fathoniinsansilmi** [comment]
here is 
temboard@postgre01 ~]$ lsof server_tasks.db
lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
      Output information may be incomplete.
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF      NODE NAME
temboard 13347 temboard    7u   REG  253,0    12288 234890625 server_tasks.db
temboard 13356 temboard    7u   REG  253,0    12288 234890625 server_tasks.db
temboard 13357 temboard    7u   REG  253,0    12288 234890625 server_tasks.db

**Comment by bersace** [comment]
Ok, you have a running temBoard locking the database. one cannot flush tasks while a server is running, I need to properly explain this to user.

Can you stop temboard service using systemctl before flushing  tasks ?

**Comment by fathoniinsansilmi** [comment]
[root@postgre01 ~]# systemctl stop temboard-agent@12-data.service
[root@postgre01 ~]# systemctl status temboard-agent@12-data.service
● temboard-agent@12-data.service - PostgreSQL Remote Control Agent 12/data
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2022-12-08 15:57:45 WIB; 54s ago
  Process: 1064546 ExecStart=/usr/bin/temboard-agent -c /etc/temboard-agent/12/data/temboard-agent.conf (code=exited,>
 Main PID: 1064546 (code=exited, status=1/FAILURE)

Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]:           File "/usr/lib/python3.6/site-packages/temboar>
Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]:             now=datetime.utcnow()
Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]:           File "/usr/lib/python3.6/site-packages/temboar>
Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]:             raise StorageEngineError("Could not recover >
Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]:         temboardagent.toolkit.errors.StorageEngineError:>
Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]: app: temboardagent version is 8.0.
Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]: app: This is a bug!
Dec 08 15:57:45 postgre01.lab.local temboard-agent[1064546]: app: Please report traceback to https://github.com/dalib>
Dec 08 15:57:45 postgre01.lab.local systemd[1]: temboard-agent@12-data.service: Main process exited, code=exited, sta>
Dec 08 15:57:45 postgre01.lab.local systemd[1]: temboard-agent@12-data.service: Failed with result 'exit-code'.

this is the result when stopping temboard service

**Comment by bersace** [comment]
I'm talking about temboard.service, not temboard-agent@*.service.

**Comment by bersace** [comment]
You have one single service named temboard and multiple temboard-agent@, one per managed PostgreSQL instance.

temboard is running as unix user temboard, has a dedicated role in a PostgreSQL database named temboard.

temboard-agent is running as unix user postgres, connect using UNIX socket to managed PostgreSQL. There is strictly no data specific to agent in the managed PostgreSQL.

YMMV

**Comment by fathoniinsansilmi** [comment]
> I'm talking about temboard.service, not temboard-agent@*.service.

[root@postgre01 ~]# systemctl stop temboard-agent
[root@postgre01 ~]# systemctl status temboard-agent
● temboard-agent.service
   Loaded: not-found (Reason: Unit temboard-agent.service not found.)
   Active: failed (thawing) (Result: exit-code) since Wed 2022-12-07 17:25:01 WIB; 23h ago
 Main PID: 604175 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[root@postgre01 ~]#

**Comment by fathoniinsansilmi** [comment]
> I'm talking about temboard.service, not temboard-agent@*.service.

hi @bersace im so so sorry didnt pay attention last time, this is the result temboard service and the log.

[root@postgre01 ~]# systemctl status temboard
● temboard.service - temBoard Server
   Loaded: loaded (/usr/lib/systemd/system/temboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2022-12-06 12:07:35 WIB; 5 days ago
 Main PID: 13347 (temboard)
    Tasks: 17 (limit: 23543)
   Memory: 32.8M
   CGroup: /system.slice/temboard.service
           ├─13347 temboard: web
           ├─13356 temboard: worker pool
           └─13357 temboard: scheduler

Dec 12 10:06:34 postgre01.lab.local temboard[13347]: monitoring: Scheduling batch collector for 1 agents.
Dec 12 10:06:34 postgre01.lab.local temboard[13347]: statements: Pulling statements from 10.10.2.41:2345.
Dec 12 10:06:34 postgre01.lab.local temboard[13347]: statements: Agent 10.10.2.41:2345 is not available: Error while >
Dec 12 10:06:34 postgre01.lab.local temboard[13347]: statements: No instances to pull data from.
Dec 12 10:06:34 postgre01.lab.local temboard[13347]: monitoring: End of collector scheduler.
Dec 12 10:06:35 postgre01.lab.local temboard[13347]: monitoring: Starting monitoring collector for 10.10.2.41:2345.
Dec 12 10:06:35 postgre01.lab.local temboard[13347]: monitoring: Found host #1 and instance #1 postgre01.lab.local:54>
Dec 12 10:06:35 postgre01.lab.local temboard[13347]: monitoring: Querying monitoring history from postgre01.lab.local>
Dec 12 10:06:35 postgre01.lab.local temboard[13347]: monitoring: Failed to query history for postgre01.lab.local:5432>
Dec 12 10:06:35 postgre01.lab.local temboard[13347]: monitoring: Agent or host may be down or misconfigured.
lines 1-21/21 (END)


2022-12-12 10:06:35 WIB temboardui[2878028] ERROR:  monitoring: Agent or host may be down or misconfigured.
2022-12-12 10:07:35 WIB temboardui[2878384] INFO:  monitoring: Starting collector scheduler.
2022-12-12 10:07:35 WIB temboardui[2878384] INFO:  monitoring: Scheduling batch collector for 1 agents.
2022-12-12 10:07:35 WIB temboardui[2878384] INFO:  monitoring: End of collector scheduler.
2022-12-12 10:07:35 WIB temboardui[2878383] INFO:  statements: Pulling statements from 10.10.2.41:2345.
2022-12-12 10:07:35 WIB temboardui[2878383] ERROR:  statements: Agent 10.10.2.41:2345 is not available: Error while fetching statements from instance: [Errno 111] Connection refused
2022-12-12 10:07:35 WIB temboardui[2878383] INFO:  statements: No instances to pull data from.
2022-12-12 10:07:36 WIB temboardui[2878391] INFO:  monitoring: Starting monitoring collector for 10.10.2.41:2345.
2022-12-12 10:07:36 WIB temboardui[2878391] INFO:  monitoring: Found host #1 and instance #1 postgre01.lab.local:5432.
2022-12-12 10:07:36 WIB temboardui[2878391] INFO:  monitoring: Querying monitoring history from postgre01.lab.local:5432.
2022-12-12 10:07:36 WIB temboardui[2878391] ERROR:  monitoring: Failed to query history for postgre01.lab.local:5432: [Errno 111] Connection refused
2022-12-12 10:07:36 WIB temboardui[2878391] ERROR:  monitoring: Agent or host may be down or misconfigured.

**Comment by fathoniinsansilmi** [comment]
> Ok, you have a running temBoard locking the database. one cannot flush tasks while a server is running, I need to properly explain this to user.
> 
> Can you stop temboard service using systemctl before flushing tasks ?

i did stop the temboard service before flush and it working properly, but when i start the temboard service and temboard-agent@.., the temboard_service@ still error

2022-12-12 10:21:20 WIB temboardagent[2882788] ERROR:  app: temboardagent version is 8.0.
2022-12-12 10:21:20 WIB temboardagent[2882788] ERROR:  app: This is a bug!
2022-12-12 10:21:20 WIB temboardagent[2882788] ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
2022-12-12 10:21:46 WIB temboardagent[2883001] ERROR:  sqlite3_engine: attempt to write a readonly database
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/tasklist/sqlite3_engine.py", line 244, in recover
            (st_aborted, datetime_to_epoch(now), st_doing)
        sqlite3.OperationalError: attempt to write a readonly database
2022-12-12 10:21:46 WIB temboardagent[2883001] ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/tasklist/sqlite3_engine.py", line 244, in recover
            (st_aborted, datetime_to_epoch(now), st_doing)
        sqlite3.OperationalError: attempt to write a readonly database

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/app.py", line 106, in main
            self.apply_config()
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/app.py", line 141, in apply_config
            return super().apply_config()
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 215, in apply_config
            service.apply_config()
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/taskmanager.py", line 457, in apply_config
            self.scheduler.setup_task_list()
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/taskmanager.py", line 303, in setup_task_list
            self.task_list.recover()
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/taskmanager.py", line 115, in recover
            now=datetime.utcnow()
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/tasklist/sqlite3_engine.py", line 253, in recover
            raise StorageEngineError("Could not recover tasks.")
        temboardagent.toolkit.errors.StorageEngineError: Could not recover tasks.
2022-12-12 10:21:46 WIB temboardagent[2883001] ERROR:  app: temboardagent version is 8.0.
2022-12-12 10:21:46 WIB temboardagent[2883001] ERROR:  app: This is a bug!
2022-12-12 10:21:46 WIB temboardagent[2883001] ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new

2022-12-12 10:19:26 WIB temboardui[13356] INFO:  taskmanager: Aborting jobs on SIGTERM.
2022-12-12 10:19:26 WIB temboardui[13356] INFO:  services: worker pool terminated.
2022-12-12 10:19:26 WIB temboardui[13357] INFO:  services: scheduler terminated.
2022-12-12 10:19:27 WIB temboardui[13347] INFO:  services: web terminated.
2022-12-12 10:20:57 WIB temboardui[2882609] INFO:  migrator: temBoard database is up-to-date.
2022-12-12 10:20:57 WIB temboardui[2882609] INFO:  services: Starting web.
2022-12-12 10:20:57 WIB temboardui[2882621] INFO:  services: Starting worker pool.
2022-12-12 10:20:57 WIB temboardui[2882622] INFO:  services: Starting scheduler.
2022-12-12 10:20:57 WIB temboardui[2882609] INFO:  temboardui: Serving temboardui on https://0.0.0.0:8888
2022-12-12 10:20:58 WIB temboardui[2882626] INFO:  statements: Purging old statements data
2022-12-12 10:20:58 WIB temboardui[2882630] INFO:  monitoring: Starting monitoring data purge worker.
2022-12-12 10:20:58 WIB temboardui[2882631] INFO:  monitoring: Starting collector scheduler.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_sessions.
2022-12-12 10:20:58 WIB temboardui[2882627] INFO:  monitoring: Aggregating data for metric metric_sessions.
2022-12-12 10:20:58 WIB temboardui[2882626] INFO:  statements: Old statements purged successfully.
2022-12-12 10:20:58 WIB temboardui[2882631] INFO:  monitoring: Scheduling batch collector for 1 agents.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_xacts.
2022-12-12 10:20:58 WIB temboardui[2882625] INFO:  statements: Pulling statements from 10.10.2.41:2345.
2022-12-12 10:20:58 WIB temboardui[2882625] ERROR:  statements: Agent 10.10.2.41:2345 is not available: Error while fetching statements from instance: [Errno 111] Connection refused
2022-12-12 10:20:58 WIB temboardui[2882631] INFO:  monitoring: End of collector scheduler.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_locks.
2022-12-12 10:20:58 WIB temboardui[2882625] INFO:  statements: No instances to pull data from.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_blocks.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_bgwriter.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_db_size.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_tblspc_size.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_filesystems_size.
2022-12-12 10:20:58 WIB temboardui[2882627] INFO:  monitoring: Aggregating data for metric metric_xacts.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_temp_files_size_delta.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_wal_files.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_cpu.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_process.
2022-12-12 10:20:58 WIB temboardui[2882628] INFO:  monitoring: Archiving data for metric metric_memory.

**Comment by fathoniinsansilmi** [comment]
@bersace yes , its in the same server
