### ISSUE TITLE
URGENT - temboard server is down after attempted v7.11 to 8 upgrade

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#1192]
we see the following upon startup:

```
2022-12-09 16:59:35 UTC temboardui[11367] INFO:  migrator: temBoard database is up-to-date.
2022-12-09 16:59:35 UTC temboardui[11381] ERROR:  app: Unhandled error:
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
	    retcode = self.main(argv, environ)
	  File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 145, in main
	    return command.main(args)
	  File "/usr/lib/python3.6/site-packages/temboardui/cli/serve.py", line 27, in main
	    with self.app.webservice.services:
	  File "/usr/lib/python3.6/site-packages/temboardui/toolkit/services.py", line 176, in __enter__
	    self.start()
	  File "/usr/lib/python3.6/site-packages/temboardui/toolkit/services.py", line 192, in start
	    process.start()
	  File "/usr/lib64/python3.6/multiprocessing/process.py", line 101, in start
	    'can only start a process object created by current process'
	AssertionError: can only start a process object created by current process
2022-12-09 16:59:35 UTC temboardui[11381] ERROR:  app: temboardui version is 8.0.
2022-12-09 16:59:35 UTC temboardui[11381] ERROR:  app: This is a bug!
2022-12-09 16:59:35 UTC temboardui[11381] ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
```

`systemctl` reports (we removed our server name):

```
Dec 09 17:01:54 xxxx.xxxx.xxxx systemd[1]: Starting temBoard Web UI...
Dec 09 17:01:55 xxxx.xxxx.xxxx temboard[12592]: INFO:  app: Using config file /etc/temboard/temboard.conf.
Dec 09 17:01:55 xxxx.xxxx.xxxx temboard[12592]: INFO:  migrator: temBoard database is up-to-date.
Dec 09 17:01:55 xxxx.xxxx.xxxx systemd[1]: PID file /run/temboard/temboard.pid not readable (yet?) after start.
Dec 09 17:01:55 xxxx.xxxx.xxxx systemd[1]: Failed to start temBoard Web UI.
Dec 09 17:01:55 xxxx.xxxx.xxxx systemd[1]: Unit temboard.service entered failed state.
Dec 09 17:01:55 xxxx.xxxx.xxxx systemd[1]: temboard.service failed.
```

we're noticing that `/run/temboard` is removed even if we manually create it.

not sure what to do moving forward here; temboard is **down** in our production environment and we can't easily rollback since we're past the point of return after the schema changes are in place.

**Comment by bersace** [comment]
Hi @bsislow . Do you have a `Restarting background service` message in logs ?

**Comment by bersace** [comment]
Can you share `systemctl cat temboard.service` and `temboard --version` output ?

**Comment by bsislow** [comment]
```
# systemctl cat temboard.service
# /etc/systemd/system/temboard.service
# It's not recommended to modify this file in-place, because it will be
# overwritten during package upgrades.  If you want to customize, the
# best way is to create a file "/etc/systemd/system/temboard.service",
# containing
#       .include /lib/systemd/system/temboard.service
#       ...make your changes here...
# For more info about custom unit files, see
# http://fedoraproject.org/wiki/Systemd#How_do_I_customize_a_unit_file.2F_add_a_custom_unit_file.3F

[Unit]
Description=temBoard Web UI
After=network.target syslog.target

[Service]
Type=forking

User=temboard
Group=temboard

RuntimeDirectory=temboard
PIDFile=/run/temboard/temboard.pid

ExecStart=/usr/bin/temboard -c /etc/temboard/temboard.conf -d -p /run/temboard/temboard.pid
ExecStop=/bin/kill -TERM $MAINPID
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

```
# temboard --version
temBoard 8.0 (/bin/temboard)
System CentOS Linux 7 (Core)
Python 3.6.6 (/usr/bin/python3)
cryptography 2.3
Tornado 4.5.3
libpq 13.2
psycopg2 2.8.5 (dt dec pq3 ext lo64)
SQLAlchemy 1.1.3
```

**Comment by bersace** [comment]
temboard.service is of type `simple` since 2018. Did you copied manually /etc/systemd/system/temboard.service from custom or old configuration ?

**Comment by bsislow** [comment]
We have not copied the `systemd` service file or modified it in any way…. it’s still the one that was packaged in the RPM by whomever makes the packages.

**Comment by bersace** [comment]
Ok. I need to check if daemonization triggers this bug. I suggest you to use /usr/lib/systemd/system/temboard.service shipped by temboard RPM.
