### ISSUE TITLE
Auto-configure error : MissingSectionHeader

### ISSUE THREAD

**Issue by vvitad** [dalibo/temboard#1199]
RHEL 7. Latest release of tembord.

I do: 
```
$ sudo /usr/share/temboard/auto_configure.sh
Configuring temboard in /etc/temboard.
Creating Postgres user, database and schema.
Failure. See /var/log/temboard-auto-configure.log for details.
```

It says: 
```
.....
.....
++ type -p temboard
+ psql=(psql --set 'ON_ERROR_STOP=on' --pset 'pager=off')
+ '[' -d /var/run/postgresql ']'
+ psql=("${runas[@]}" "${psql[@]}")
+ sudo -inu temboard /bin/temboard --config=/etc/temboard/temboard.conf migratedb check
INFO:  app: Using config file /etc/temboard/temboard.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 107, in main
            self.bootstrap(args=args, environ=environ, service=command.is_service)
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 105, in bootstrap
            self.read_file(parser, configfile)
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 242, in read_file
            parser.readfp(fp)
          File "/usr/lib64/python3.6/configparser.py", line 763, in readfp
            self.read_file(fp, source=filename)
          File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
            self._read(f, source)
          File "/usr/lib64/python3.6/configparser.py", line 1080, in _read
            raise MissingSectionHeaderError(fpname, lineno, line)
        configparser.MissingSectionHeaderError: File contains no section headers.
        file: '/etc/temboard/temboard.conf', line: 1
        "Creating directory '/var/empty/temboard'.\n"
ERROR:  app: temboardui version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
+ sudo -inu temboard /bin/temboard --config=/etc/temboard/temboard.conf migratedb upgrade
INFO:  app: Using config file /etc/temboard/temboard.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 107, in main
            self.bootstrap(args=args, environ=environ, service=command.is_service)
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 105, in bootstrap
            self.read_file(parser, configfile)
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 242, in read_file
            parser.readfp(fp)
          File "/usr/lib64/python3.6/configparser.py", line 763, in readfp
            self.read_file(fp, source=filename)
          File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
            self._read(f, source)
          File "/usr/lib64/python3.6/configparser.py", line 1080, in _read
            raise MissingSectionHeaderError(fpname, lineno, line)
        configparser.MissingSectionHeaderError: File contains no section headers.
        file: '/etc/temboard/temboard.conf', line: 1
        "Creating directory '/var/empty/temboard'.\n"
ERROR:  app: temboardui version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!

```

**Comment by vvitad** [comment]
Next I did this:

```
$ sudo vim /var/log/temboard-auto-configure.log
$ sudo vim /usr/share/temboard/auto_configure.sh
$ sudo cat /etc/temboard/temboard.conf
```
_Creating directory '/var/empty/temboard'.
# Configuration initiated by /usr/share/temboard/auto_configure.sh on Wed Feb 15 09:24:56 MSK 2023
#
# See https://temboard.rtfd.io/ for details on configuration
# possibilities.

[temboard]
port = ////
ssl_cert_file = /etc/pki/tls/certs/temboard-auto.pem
ssl_key_file = /etc/pki/tls/private/temboard-auto.key
cookie_secret = ////
home = /var/lib/temboard

[repository]
host = /var/run/postgresql
port = 5432
user = temboard
password = ///
dbname = temboard

[logging]
method = stderr
level = INFO

[monitoring]
# purge_after = 730

[statements]
# purge_after = 7_

```
$ sudo /usr/share/temboard/auto_configure.sh
Configuring temboard in /etc/temboard.
Creating Postgres user, database and schema.

Success. You can now start temboard using:

    systemctl enable-now temboard

Remember to replace default admin user!!!
```

For some reason of worked after I restarted auto-configure.sh

**Comment by bersace** [comment]
Hi @vvitad . It seems a spurious lines got injected on top of conf file:

```
Creating directory '/var/empty/temboard'.
```

The cause may be a noise frominteractive shell in content redirection in script.

Can you confirm this work ?

`auto_configure.sh` should close stdin upfront to avoid such errors. Please keep this issue open.

**Comment by vvitad** [comment]
@bersace hi! what can I do to help?

**Comment by vvitad** [comment]
@bersace, hellp
I have found where the problems began
the main reason was how the agent defined cluster-name 
it was autoconfigured to patroni-pg-cluster and "-" ruined things for me:
```
$ /usr/share/temboard-agent/auto_configure.sh https://xx.xx.xx.xx:8888/
Using hostname somehostname.com
Configuring for PostgreSQL user postgres.
Configuring for cluster on port 5432.
Configuring for cluster at /data/pgsql/9.6/data.
Using /usr/pgsql-9.6/bin/pg_ctl.
Cluster name is patroni-pg-cluster.
Configuring temboard-agent in /etc/temboard-agent/patroni-pg-cluster/temboard-agent.conf .
Configuring temboard-agent to run on port 2345.
Configuring systemd unit temboard-agent@patroni\x2dpg\x2dcluster.service.

Success. You now need to fetch UI signing key using:

    sudo -u postgres temboard-agent -c /etc/temboard-agent/patroni-pg-cluster/temboard-agent.conf fetch-key

Then start agent service using:

    systemctl enable --now temboard-agent@patroni\x2dpg\x2dcluster.service

```
