### ISSUE TITLE
Parameter 'X-Session' is malformed.

### ISSUE THREAD

**Issue by fathoniinsansilmi** [dalibo/temboard#1219]
Parameter 'X-Session' is malformed. it happens when we upgrading temboard ui version 7.10 to 8.0 (latest), and temboard agent version is 7.8, what should i do?
![image](https://user-images.githubusercontent.com/89531166/232657071-6a5f8592-6e20-4dcc-8319-a83c148d79ba.png)

**Comment by bersace** [comment]
Hi @fathoniinsansilmi . Did you try 7.11 agent ? Did you try to clean cookies ?

**Comment by daamien** [comment]
Hi @fathoniinsansilmi 

This is issue is inactive since April, so are closing it. 

Feel free to reopen it, if you have new information about it.

**Comment by bsislow** [comment]
I see the following in our temboard agent logs on certain instances:

Versions:
temboard-agent-7.11-1
temboard-8.0-1

Error:
```
...
Loading plugin monitoring.
Loading plugin maintenance.
Loading plugin pgconf.
Loading plugin activity.
Loading plugin statements.
Loading plugin administration.
Loading plugin dashboard.
Starting main process.
Starting main process.
Starting worker pool.
Starting scheduler.
{'error': "Parameter 'X-Session' is malformed."}
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 136, in response
   (code, message) = self.route_request()
 File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 265, in route_request
   username = check_sessionid(self.headers, self.sessions)
 File "/usr/lib/python3.6/site-packages/temboardagent/api.py", line 33, in check_sessionid
   [('X-Session', T_SESSIONID, False)])
 File "/usr/lib/python3.6/site-packages/temboardagent/tools.py", line 58, in validate_parameters
   raise e
 File "/usr/lib/python3.6/site-packages/temboardagent/tools.py", line 45, in validate_parameters
   % (key))
temboardagent.errors.HTTPError: Parameter 'X-Session' is malformed.
{'error': "Parameter 'X-Session' is malformed."}
client: 10.244.6.162 request: "GET /profile HTTP/1.1" 406 - 2.47ms
{'error': "Parameter 'X-Session' is malformed."}
Traceback (most recent call last):
 File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 136, in response
   (code, message) = self.route_request()
 File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 265, in route_request
   username = check_sessionid(self.headers, self.sessions)
 File "/usr/lib/python3.6/site-packages/temboardagent/api.py", line 33, in check_sessionid
   [('X-Session', T_SESSIONID, False)])
 File "/usr/lib/python3.6/site-packages/temboardagent/tools.py", line 58, in validate_parameters
   raise e
 File "/usr/lib/python3.6/site-packages/temboardagent/tools.py", line 45, in validate_parameters
   % (key))
temboardagent.errors.HTTPError: Parameter 'X-Session' is malformed.
{'error': "Parameter 'X-Session' is malformed."}
```
