### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 3: invalid continuation byte

### ISSUE THREAD

**Issue by hafedh-hk** [dalibo/temboard#1236]
Hi support team,

I have launched /usr/share/temboard/auto_configure.sh and i'm faced with the following errors 

cat /var/log/temboard-auto-configure.log
+ echo 'step2 .....................'
step2 .....................
+ setup_pq
+ local psql
+ export PGHOST=/home/spidr3/data/14/run/postgres/
+ PGHOST=/home/spidr3/data/14/run/postgres/
+ export PGPORT=54320
+ PGPORT=54320
+ export PGUSER=dbaspidr3
+ PGUSER=dbaspidr3
+ '[' -d /home/spidr3/data/14/run/postgres/ ']'
+ psql=(sudo -nEu "$PGUSER" psql)
+ sudo -nEu dbaspidr3 psql -tc 'SELECT '\''Postgres connection working.'\'';'
 Postgres connection working.

+ echo 'step3 .....................'
step3 .....................
+ export TEMBOARD_PASSWORD=57N%d3rW%7534587mUfr
+ TEMBOARD_PASSWORD=57N%d3rW%7534587mUfr
+ getent passwd temboard
temboard:x:500:500:temBoard Web UI:/var/lib/temboard:/bin/bash
+ echo 'step4 .....................'
step4 .....................
+ getent group ssl-cert
+ log 'step5 .....................'
+ echo 'step5 .....................'
+ tee -a /dev/fd/3
step5 .....................
+ log 'Configuring temboard in /etc/temboard.'
+ echo 'Configuring temboard in /etc/temboard.'
+ tee -a /dev/fd/3
Configuring temboard in /etc/temboard.
+ mapfile -t sslfiles
++ set -eu
++ setup_ssl
++ local pki
++ for d in /etc/pki/tls /etc/ssl /etc/temboard
++ '[' -d /etc/pki/tls ']'
++ pki=/etc/pki/tls
++ break
++ '[' -z /etc/pki/tls ']'
++ '[' -f /etc/pki/tls/certs/ssl-cert-snakeoil.pem ']'
++ sslcert=/etc/pki/tls/certs/temboard-auto.pem
++ sslkey=/etc/pki/tls/private/temboard-auto.key
++ '[' -f /etc/pki/tls/certs/temboard-auto.pem ']'
++ chmod 640 /etc/pki/tls/private/temboard-auto.key
++ chgrp temboard /etc/pki/tls/private/temboard-auto.key
++ readlink -e /etc/pki/tls/certs/temboard-auto.pem /etc/pki/tls/private/temboard-auto.key
+ install -o temboard -g temboard -m 0750 -d /etc/temboard /var/log/temboard /var/lib/temboard
+ install -o temboard -g temboard -m 0640 /dev/null /etc/temboard/temboard.conf
+ generate_configuration /etc/pki/tls/certs/temboard-auto.pem /etc/pki/tls/private/temboard-auto.key
+ local sslcert=/etc/pki/tls/certs/temboard-auto.pem
+ shift
+ local sslkey=/etc/pki/tls/private/temboard-auto.key
+ shift
+ sudo -iu temboard test -r /etc/pki/tls/certs/temboard-auto.pem
mesg: ttyname failed: Inappropriate ioctl for device
+ sudo -iu temboard test -r /etc/pki/tls/private/temboard-auto.key
mesg: ttyname failed: Inappropriate ioctl for device
+ cat
++ date
++ pwgen 128
++ od -vN 64 -An -tx1 /dev/urandom
++ tr -d ' \n'
+ log 'step6 .....................'
+ echo 'step6 .....................'
+ tee -a /dev/fd/3
step6 .....................
+ log 'Creating Postgres user, database and schema.'
+ echo 'Creating Postgres user, database and schema.'
+ tee -a /dev/fd/3
Creating Postgres user, database and schema.
+ DEBUG=y
+ TEMBOARD_CONFIGFILE=/etc/temboard/temboard.conf
+ ./create_repository.sh
++ readlink -m ./create_repository.sh/../sql/
+ SQLDIR=/usr/share/temboard/sql
+ SYSUSER=temboard
+ export PGUSER=dbaspidr3
+ PGUSER=dbaspidr3
+ export PGHOST=/home/spidr3/data/14/run/postgres/
+ PGHOST=/home/spidr3/data/14/run/postgres/
+ log 'setp10 ................ PGUSER: dbaspidr3'
+ echo 'setp10 ................ PGUSER: dbaspidr3'
+ tee -a /dev/fd/3
setp10 ................ PGUSER: dbaspidr3
+ log 'setp10 ................ PGHOST:  /home/spidr3/data/14/run/postgres/'
+ echo 'setp10 ................ PGHOST:  /home/spidr3/data/14/run/postgres/'
+ tee -a /dev/fd/3
setp10 ................ PGHOST:  /home/spidr3/data/14/run/postgres/
+ log 'setp10 ................ SQLDIR:  /usr/share/temboard/sql'
+ echo 'setp10 ................ SQLDIR:  /usr/share/temboard/sql'
+ tee -a /dev/fd/3
setp10 ................ SQLDIR:  /usr/share/temboard/sql
+ log 'setp10 ................ SYSUSER: temboard'
+ echo 'setp10 ................ SYSUSER: temboard'
+ tee -a /dev/fd/3
setp10 ................ SYSUSER: temboard
+ psql=(psql -d "$PGUSER")
+ '[' -d /home/spidr3/data/14/run/postgres/ ']'
+ psql=(sudo -nEHu "${PGUSER}" "${psql[@]}")
+ echo 'setp11 ................'
setp11 ................
+ TEMBOARD_DATABASE=temboard
+ TEMBOARD_PASSWORD=57N%d3rW%7534587mUfr
+ sudo -nEHu dbaspidr3 psql -d dbaspidr3 -c 'SELECT '\''SKIP'\'' FROM pg_catalog.pg_user WHERE usename = '\''temboard'\'''
+ grep -q SKIP
+ sudo -nEHu dbaspidr3 psql -d dbaspidr3 -awc 'CREATE ROLE temboard LOGIN PASSWORD '\''57N%d3rW%7534587mUfr'\'';'
CREATE ROLE temboard LOGIN PASSWORD '57N%d3rW%7534587mUfr';
CREATE ROLE
+ sudo -nEHu dbaspidr3 psql -d dbaspidr3 -c 'SELECT '\''SKIP'\'' FROM pg_catalog.pg_database WHERE datname = '\''temboard'\'''
+ grep -q SKIP
+ sudo -nEHu dbaspidr3 psql -d dbaspidr3 -awc 'CREATE DATABASE temboard OWNER temboard;'
CREATE DATABASE temboard OWNER temboard;
CREATE DATABASE
+ PGUSER=temboard
+ export PGPASSWORD=57N%d3rW%7534587mUfr
+ PGPASSWORD=57N%d3rW%7534587mUfr
+ export PGDATABASE=temboard
+ PGDATABASE=temboard
+ getent passwd temboard
++ whoami
+ '[' root '!=' temboard ']'
+ runas=(sudo -inu "$SYSUSER")
+ migratedb=("${runas[@]}" "$(type -p temboard)" ${TEMBOARD_CONFIGFILE+--config=$TEMBOARD_CONFIGFILE} migratedb)
++ type -p temboard
+ psql=(psql --set 'ON_ERROR_STOP=on' --pset 'pager=off')
+ '[' -d /home/spidr3/data/14/run/postgres/ ']'
+ psql=("${runas[@]}" "${psql[@]}")
+ sudo -inu temboard /usr/bin/temboard --config=/etc/temboard/temboard.conf migratedb check
mesg: ttyname failed: Inappropriate ioctl for device
INFO:  app: Using config file /etc/temboard/temboard.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 145, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 39, in main
            with self.parent.make_conn() as conn:
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 29, in make_conn
            return closing(connect(format_dsn(self.app.config.repository)))
          File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
            dsn = _ext.make_dsn(dsn, **kwargs)
          File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 153, in make_dsn
            parse_dsn(dsn)
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 3: invalid continuation byte
ERROR:  app: temboardui version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
+ sudo -inu temboard /usr/bin/temboard --config=/etc/temboard/temboard.conf migratedb upgrade
mesg: ttyname failed: Inappropriate ioctl for device
INFO:  app: Using config file /etc/temboard/temboard.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 145, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 51, in main
            with self.parent.make_conn() as conn:
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 29, in make_conn
            return closing(connect(format_dsn(self.app.config.repository)))
          File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
            dsn = _ext.make_dsn(dsn, **kwargs)
          File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 153, in make_dsn
            parse_dsn(dsn)
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 3: invalid continuation byte
ERROR:  app: temboardui version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
+ catchall
+ local rc=1
+ trap - INT EXIT TERM
+ set +x
Failure. See /var/log/temboard-auto-configure.log for details.

**Comment by bersace** [comment]
Hi,

Did you modify the script ?

Postgres connexion string contains non utf-8 char, what encoding are you using in DSN ?

Regards,
Étienne

**Comment by hafedh-hk** [comment]
Hi,
Yes i have added some traces in create_repository.sh
how can i restore the last old of create_repository.sh ?

**Comment by hafedh-hk** [comment]
I have removed temboard-8.0-1.el8.noarch.rpm and installed it again.

I have always the same error :
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 145, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 51, in main
            with self.parent.make_conn() as conn:
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 29, in make_conn
            return closing(connect(format_dsn(self.app.config.repository)))
          File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
            dsn = _ext.make_dsn(dsn, **kwargs)
          File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 153, in make_dsn
            parse_dsn(dsn)
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 3: invalid continuation byte

**Comment by hafedh-hk** [comment]
Hi,
Other question:
what do you mean by "what encoding are you using in DSN" ?

Thanks
