### ISSUE TITLE
error launching /usr/share/temboard/auto_configure.sh

### ISSUE THREAD

**Issue by Slimane2021** [dalibo/temboard#1245]
Hello,

i had launched this script, /usr/share/temboard/auto_configure.sh, with the folowing parameters : 

export PGHOST=/home/project/postgres/
export PGPORT=54321
export PGUSER=dbaspidr4
export TEMBOARD_PASSWORD="55584mokjh2023UHK"

i had receive the folwing errors : 

mesg: ttyname failed: Inappropriate ioctl for device
INFO:  app: Using config file /etc/temboard/temboard.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 145, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 39, in main
            with self.parent.make_conn() as conn:
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 29, in make_conn
            return closing(connect(format_dsn(self.app.config.repository)))
          File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
            dsn = _ext.make_dsn(dsn, **kwargs)
          File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 153, in make_dsn
            parse_dsn(dsn)
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 3: invalid continuation byte
ERROR:  app: temboardui version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
+ log etape51
+ echo etape51
+ tee -a /dev/fd/3
etape51
+ sudo -inu temboard /usr/bin/temboard --config=/etc/temboard/temboard.conf migratedb upgrade
mesg: ttyname failed: Inappropriate ioctl for device
INFO:  app: Using config file /etc/temboard/temboard.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 145, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 51, in main
            with self.parent.make_conn() as conn:
          File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 29, in make_conn
            return closing(connect(format_dsn(self.app.config.repository)))
          File "/usr/lib64/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
            dsn = _ext.make_dsn(dsn, **kwargs)
          File "/usr/lib64/python3.6/site-packages/psycopg2/extensions.py", line 153, in make_dsn
            parse_dsn(dsn)
        UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 3: invalid continuation byte
ERROR:  app: temboardui version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
+ catchall
+ local rc=1
+ trap - INT EXIT TERM
+ set +x

Could you advise please,

Regards,
Slimane MRABTI

**Comment by pirlgon** [comment]
Hi, 
please don't post your password here (I've updated your comment).
It looks like you have a problem with the encoding in the temboard.conf file.
Can you give us the contents?

**Comment by Slimane2021** [comment]
Hi,

Please find below the contents : 

cat /etc/temboard/temboard.conf
# Configuration initiated by /usr/share/temboard/auto_configure.sh on Wed Aug  2 11:08:29 CEST 2023
#
# See https://temboard.rtfd.io/ for details on configuration
# possibilities.

[temboard]
port = 8888
ssl_cert_file = /etc/pki/tls/certs/temboard-auto.pem
ssl_key_file = /etc/pki/tls/private/temboard-auto.key
cookie_secret = 898a00cdb5a0bb1fa60549661e9b63be6df48d762d7cf28173045f1a1247d94499f84fd2a227eb7a31c8d351ce0c8491f4fe70fd1277098da2e5f7a346917e8d
home = /var/lib/temboard

[repository]
host = /home/spidr4/data/14/run/postgres/
port = 54321
user = temboard
password = 57N%d3rW%7534587mUHK
dbname = temboard

[logging]
method = stderr
level = INFO

[monitoring]
# purge_after = 730

[statements]
# purge_after = 7

Best regards

**Comment by Slimane2021** [comment]
Hi,

Could you please tel me whether you need more informations ?

Best regards

**Comment by Slimane2021** [comment]
Hello,

this is the output : 

/etc/temboard/temboard.conf: text/plain; charset=us-ascii

Best regards

**Comment by bersace** [comment]
You have a non ascii char in your password or something like that.

**Comment by Hugues-Antoine** [comment]
Hello,

You can get this error if the password stored in the temboard.conf file is not correct. This can happen if the auto_configure.sh script is run a second time, as it will not change the password at database level.
