### ISSUE TITLE
can't open schema on Maintenance menu

### ISSUE THREAD

**Issue by fathoniinsansilmi** [dalibo/temboard#1280]
hi, we have another issue after upgrading temboard UI and agents, we cant open schema on Maintenance menu, it was keep loading until it stopped and showing the error message like this 
the agent still running.
![image](https://github.com/dalibo/temboard/assets/89531166/66ecfe9f-8b41-4fb2-929e-2cf5feaf2229)

this is the log
2023-10-19 15:18:02 WIB temboardui[2617] INFO:  access: 200 GET /proxy/db02lnswdrc.insw.go.id/2345/maintenance/nswdbgen2/schema/nsw_nk_v2/reindex/scheduled (10.191.167.44) 163.87ms
2023-10-19 15:18:02 WIB temboardui[2617] ERROR:  tornado: Request failed: 500 Failed to contact agent db03lnswdc.insw.go.id:2345: The read operation timed out. Is it running?.
2023-10-19 15:18:02 WIB temboardui[2617] ERROR:  access: 500 GET /proxy/db03lnswdc.insw.go.id/2345/maintenance/nswdbgen2/schema/nsw_nk_v2 (10.191.167.44) 30100.77ms

we've tried on cloned temboard server and with the same agents, but the version temboard UI is still 7.11v, but it working properly to open the schema on maintenance menu, we need ur help

**Comment by fathoniinsansilmi** [comment]
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR: [Errno 32] Broken pipe
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR: Traceback (most recent call last):
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:   File "/usr/lib/python3.6/site-packages/temboardagent/httpd.py", line 162, in response
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:     .encode('utf-8'))
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:   File "/usr/lib64/python3.6/socketserver.py", line 803, in write
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:     self._sock.sendall(b)
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:   File "/usr/lib64/python3.6/ssl.py", line 934, in sendall
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:     v = self.send(byte_view[count:])
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:   File "/usr/lib64/python3.6/ssl.py", line 903, in send
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:     return self._sslobj.write(data)
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:   File "/usr/lib64/python3.6/ssl.py", line 601, in write
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR:     return self._sslobj.write(data)
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR: BrokenPipeError: [Errno 32] Broken pipe
2023-10-26 15:21:42,540 temboardagent[258558]: [httpd] ERROR: Could not send response

this the log agent when i was reloading the page
please hel @bersace

**Comment by bersace** [comment]
hi @fathoniinsansilmi , thanks for reaching.

It's a bad idea to mix UI on a same agent.

What are your temBoard UI and agent versions ?

**Comment by fathoniinsansilmi** [comment]
UI 8.0 version
agent instances are mix version, 7.11 version and 8.0 version

do i have to stop the agent that installed on the same server as the UI?
is there any issue with our network?
