### ISSUE TITLE
Temboard not working with Pypi install | ERROR:  tornado.general: Uncaught exception, closing connection.

### ISSUE THREAD

**Issue by fxsoulis** [dalibo/temboard#1322]
I have tornado error when i run temboard from a Pypi install whereas it works with a ubuntu22 package install.

``` bash
$ sudo pip install temboard psycopg2-binary
$ temboard --version
```

>temBoard 8.2.1 (/usr/local/bin/temboard)
>System Ubuntu 22.04.1 LTS (Jammy Jellyfish)
>Python 3.10.12 (/usr/bin/python3)
>cryptography 3.4.8
>Tornado **6.4**
>libpq 16.0
>psycopg2 2.9.9 (dt dec pq3 ext lo64)
>SQLAlchemy 1.4.50

``` bash
$ sudo apt install temboard
$ temboard --version
```

>temBoard 8.2.1 (/usr/lib/temboard/bin/temboard)
>System Ubuntu 22.04.1 LTS (Jammy Jellyfish)
>Python 3.10.12 (/usr/bin/python3)
>cryptography 41.0.5
>Tornado **6.3.3**
>libpq 14.10
>psycopg2 2.9.2 (dt dec pq3 ext lo64)
>SQLAlchemy 1.4.50

I've retried a Pypi install with tornado **v6.3.3** *(same ubuntu package version)* and it works.

Here is the error encountered when i load url from my web navigator with Pypi install as the documention :

```txt
ERROR:  tornado.general: Uncaught exception, closing connection.
        Traceback (most recent call last):
          File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 691, in _handle_events
            self._handle_read()
          File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 1427, in _handle_read
            self._do_ssl_handshake()
          File "/usr/local/lib/python3.10/dist-packages/temboardui/autossl.py", line 159, in _do_ssl_handshake
            if not self._verify_cert(self.socket.getpeercert()):
        AttributeError: 'EasySSLIOStream' object has no attribute '_verify_cert'
ERROR:  asyncio: Exception in callback None()
        handle: <Handle cancelled>
        Traceback (most recent call last):
          File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
            self._context.run(self._callback, *self._args)
          File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 202, in _handle_events
            handler_func(fileobj, events)
          File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 691, in _handle_events
            self._handle_read()
          File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 1427, in _handle_read
            self._do_ssl_handshake()
          File "/usr/local/lib/python3.10/dist-packages/temboardui/autossl.py", line 159, in _do_ssl_handshake
            if not self._verify_cert(self.socket.getpeercert()):
        AttributeError: 'EasySSLIOStream' object has no attribute '_verify_cert'
ERROR:  tornado.application: Exception in callback functools.partial(<function AutoHTTPSServer._handle_connection.<locals>.<lambda> at 0x7fa38c5bfd00>, <Future finished exception=AttributeError("'EasySSLIOStream' object has no attribute '_verify_cert'")>)
        Traceback (most recent call last):
          File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 750, in _run_callback
            ret = callback()
          File "/usr/local/lib/python3.10/dist-packages/temboardui/autossl.py", line 226, in <lambda>
            io_loop.add_future(future, lambda f: f.result())
          File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 780, in run
            yielded = self.gen.throw(exc)
          File "/usr/local/lib/python3.10/dist-packages/temboardui/autossl.py", line 233, in handle_stream
            yield ssl_stream.wait_for_handshake()
          File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 767, in run
            value = future.result()
          File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 691, in _handle_events
            self._handle_read()
          File "/usr/local/lib/python3.10/dist-packages/tornado/iostream.py", line 1427, in _handle_read
            self._do_ssl_handshake()
          File "/usr/local/lib/python3.10/dist-packages/temboardui/autossl.py", line 159, in _do_ssl_handshake
            if not self._verify_cert(self.socket.getpeercert()):
        AttributeError: 'EasySSLIOStream' object has no attribute '_verify_cert'
```

**Comment by pirlgon** [comment]
Thank you for the report, we will work on it.

**Comment by jeanloesch** [comment]
Hi,

I have the same error messages with Temboard Server v9.0.1 under Rocky Linux release 8.10 (Green Obsidian).
cat /etc/temboard/temboard.conf
#
#   T E M B O A R D   U I   C O N F I G U R A T I O N
#
# Generated by /usr/share/temboard/auto_configure.sh on lun. févr. 17 18:14:05 CET 2025.
#
# temBoard 9.0.1 (/usr/bin/temboard)
# System Rocky Linux 8.10 (Green Obsidian)
# Python 3.6.8 (/usr/libexec/platform-python)
# cryptography 3.2.1
# Tornado 6.0.2
# Flask 0.12.2
# libpq 17.2
# psycopg2 2.9.5 (dt dec pq3 ext lo64)
# SQLAlchemy 1.3.2


tail -f /var/log/temboard/temboard.log
2025-02-19T10:09:37.213Z temboardui[479333] ERROR:  asyncio: Exception in callback None()
        handle: <Handle cancelled>
        Traceback (most recent call last):
          File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
            self._callback(*self._args)
          File "/usr/lib64/python3.6/site-packages/tornado/platform/asyncio.py", line 138, in _handle_events
            handler_func(fileobj, events)
          File "/usr/lib64/python3.6/site-packages/tornado/iostream.py", line 706, in _handle_events
            self._handle_write()
          File "/usr/lib64/python3.6/site-packages/tornado/iostream.py", line 1477, in _handle_write
            self._do_ssl_handshake()
          File "/usr/lib/python3.6/site-packages/temboardui/autossl.py", line 100, in _do_ssl_handshake
            self.socket.do_handshake()
          File "/usr/lib64/python3.6/ssl.py", line 1070, in do_handshake
            self._sslobj.do_handshake()
          File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
            self._sslobj.do_handshake()
        OSError: [Errno 0] Error
