### ISSUE TITLE
KeyError: 'Hugepagesize'

### ISSUE THREAD

**Issue by egorsmkv** [dalibo/temboard#1327]
When I start the containers with teamboard agent I am getting this error:

```
2024-01-11 18:26:37 UTC temboardagent[232] DEBUG:  agent: Boostraping plugin dashboard
2024-01-11 18:26:37 UTC temboardagent[232] INFO:  serve: Resetting monitoring data.
2024-01-11 18:26:37 UTC temboardagent[232] DEBUG:  agent: Loading signing key from /etc/temboard-agent/instance15/signing-public.pem.
2024-01-11 18:26:37 UTC temboardagent[232] DEBUG:  discover: Inspecting temBoard and system.
2024-01-11 18:26:37 UTC temboardagent[232] ERROR:  app: Unhandled error:
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
	    retcode = self.main(argv, environ)
	  File "/usr/lib/python3/dist-packages/temboardagent/cli/app.py", line 135, in main
	    return command.main(args)
	  File "/usr/lib/python3/dist-packages/temboardagent/cli/serve.py", line 32, in main
	    self.app.discover.refresh()
	  File "/usr/lib/python3/dist-packages/temboardagent/discover.py", line 116, in refresh
	    collect_memory(d)
	  File "/usr/lib/python3/dist-packages/temboardagent/discover.py", line 168, in collect_memory
	    s['hugepage'] = meminfo['Hugepagesize']
	KeyError: 'Hugepagesize'
2024-01-11 18:26:37 UTC temboardagent[232] ERROR:  app: temboardagent version is 8.2.1.
2024-01-11 18:26:37 UTC temboardagent[232] ERROR:  app: This is a bug!
```

I am running it on MacOS.

**Comment by daamien** [comment]
Hi @egorsmkv !

Thanks for the feedback. Currently the community support for Temboard is limited to 👍 

* Debian 9 up to 11
*  RHEL 7 and 8
