### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DataMark-911** [dalibo/temboard#1387]
[root@XXXXXXX ~]# sudo -u postgres temboard-agent -c /etc/temboard-agent/15/pg5432/temboard-agent.conf register --groups linux
INFO:  app: Using config file /etc/temboard-agent/15/pg5432/temboard-agent.conf.
WARNING:  configuration: Can't move back to /root: [Errno 13] Permission denied: '/root'
INFO:  register: Working for agent listening at https://XXXXXXXX:2345.
INFO:  register: Discovering system and PostgreSQL ...
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/app.py", line 135, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardagent/cli/register.py", line 90, in main
            discover['postgres']['version_summary'],
        KeyError: 'version_summary'
ERROR:  app: temboardagent version is 8.2.1.
**ERROR:  app: This is a bug!**
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!

**Comment by bersace** [comment]
Execute `sudo -u postgres temboard-agent -c /etc/temboard-agent/15/pg5432/temboard-agent.conf discover` to refresh discover data as a workaround.

Please keep this issue open, temBoard should handle gently this situation.

**Comment by bersace** [comment]
Note that we recommend using `temboard register-instance` on UI side rather than registering on agent side. This avoids asking for admin credentials on UI and prevent agent to UI request initiation.

**Comment by DataMark-911** [comment]
_[root@XXXXXXX~]# sudo -u postgres temboard-agent -c /etc/temboard-agent/15/pg5432/temboard-agent.conf discover
INFO:  app: Using config file /etc/temboard-agent/15/pg5432/temboard-agent.conf.
WARNING:  configuration: Can't move back to /root: [Errno 13] Permission denied: '/root'
ERROR:  discover: Failed to collect Postgres data: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: fe_sendauth: no password supplied

INFO:  discover: Instance discover updated.
{
  "postgres": {},
  "system": {
    "arch": "x86_64",
    "cpu_count": 4,
    "cpu_model": "Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz",
    "distribution": "AlmaLinux 8.8 (Sapphire Caracal)",
    "fqdn": "XXXXXXX",
    "hostname": "XXXXXXX",
    "hugepage": 2097152,
    "memory": 8070406144,
    "os": "Linux",
    "os_version": "4.18.0-477.13.1.el8_8.x86_64",
    "start_time": "2023-10-28T07:02:02",
    "swap": 1073737728
  },
  "temboard": {
    "agent_version": "8.2.1",
    "bin": "/bin/temboard-agent",
    "bottle_version": "0.12.21",
    "configfile": "/etc/temboard-agent/15/pg5432/temboard-agent.conf",
    "cryptography_version": "3.2.1",
    "libpq_version": "15.3",
    "plugins": [
      "activity",
      "administration",
      "dashboard",
      "maintenance",
      "monitoring",
      "pgconf",
      "statements"
    ],
    "psycopg2_version": "2.9.5 (dt dec pq3 ext lo64)",
    "python_version": "3.6.8",
    "pythonbin": "/usr/libexec/platform-python"
  }
}_


I try to add on UI but error msg :

![image](https://github.com/dalibo/temboard/assets/171325360/98b3bbca-090f-4a2a-a8d9-e738796c2440)

I added the port on the previous page

**Comment by DataMark-911** [comment]
my pg_hba.conf file was not configured to go out.
I modified and restarted, i added on UI, it's ok now
Thank you bersace

**Comment by bersace** [comment]
What was the log message of temboard agent ?
