### ISSUE TITLE
problem with Temboard-Agent configuration

### ISSUE THREAD

**Issue by MickaelTheCat** [dalibo/temboard#1496]
Hello
I have problem with PyPI :

temboard-agent --version
temBoard agent 8.2.1 (/usr/local/bin/temboard-agent)
System Ubuntu 24.04 LTS (Noble Numbat)
Python 3.12.3 (/usr/bin/python3)
bottle 0.12.25
cryptography 41.0.7
libpq 16.0
psycopg2 2.9.9 (dt dec pq3 ext lo64)

/usr/local/share/temboard-agent/auto_configure.sh https://xxx.local:8888
Using hostname xxx.local.
Configuring for PostgreSQL user postgres.
Configuring for cluster on port 5432.
Configuring for cluster at /data/postgresql.
Using /usr/lib/postgresql/16/bin/pg_ctl.
Cluster name is 16/main.
Configuring temboard-agent in /etc/temboard-agent/16/main/temboard-agent.conf .
Using snake-oil SSL certificate.
Configuring temboard-agent to run on port 2345.
Failure. See /var/log/temboard-agent-auto-configure.log for details.

-->

+ type -p temboard-agent
+ sudo -Eu postgres /usr/local/bin/temboard-agent -c /etc/temboard-agent/16/main/temboard-agent.conf discover
INFO:  app: Using config file /etc/temboard-agent/16/main/temboard-agent.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/local/lib/python3.12/dist-packages/temboardagent/toolkit/app.py", line 351, in entrypoint
            retcode = self.main(argv, environ)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
          File "/usr/local/lib/python3.12/dist-packages/temboardagent/cli/app.py", line 93, in main
            self.bootstrap(args=args, environ=environ, service=command.is_service)
          File "/usr/local/lib/python3.12/dist-packages/temboardagent/toolkit/app.py", line 105, in bootstrap
            self.read_file(parser, configfile)
          File "/usr/local/lib/python3.12/dist-packages/temboardagent/toolkit/app.py", line 242, in read_file
            parser.readfp(fp)
            ^^^^^^^^^^^^^
        AttributeError: 'RawConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
ERROR:  app: temboardagent version is 8.2.1.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!

**Comment by daamien** [comment]
Hi @MickaelTheCat 

Temboard 8 is not supported on Ubuntu 24.04 LTS.

In this case, Ubuntu 24.04 LTS ships Python 3.12 which introduce a few backward incompatible changes.
