### ISSUE TITLE
After upgrade in version 9.0.0, i can't register new instance

### ISSUE THREAD

**Issue by vidierr** [dalibo/temboard#1530]
```
sudo -u temboard temboard register-instance -e prod --if-not-exists hostname.xxx.yyy 2345
INFO:  app: Starting temboard 9.0.0.
INFO:  app: Using config file /etc/temboard/temboard.conf.
INFO:  register_instance: Discovering temBoard agent at hostname.xxx.yyy:2345.
INFO:  register_instance: Registering PostgreSQL 15.7 serving /PGDATA/data at hostname:5432.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
            cursor, statement, parameters, context
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
            cursor.execute(statement, parameters)
        psycopg2.ProgrammingError: can't adapt type 'RowProxy'

        The above exception was the direct cause of the following exception:

        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 312, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 116, in main
            return command.main(args)
          File "/usr/lib/python3.6/site-packages/temboardui/cli/register_instance.py", line 177, in main
            .with_session(session)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3275, in one
            ret = self.one_or_none()
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
            ret = list(self)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
            return self._execute_and_instances(context)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
            result = conn.execute(querycontext.statement, self._params)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
            return meth(self, multiparams, params)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
            return connection._execute_clauseelement(self, multiparams, params)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
            distilled_params,
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
            e, statement, parameters, cursor, context
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
            util.raise_from_cause(sqlalchemy_exception, exc_info)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
            reraise(type(exception), exception, tb=exc_tb, cause=cause)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
            raise value.with_traceback(tb)
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
            cursor, statement, parameters, context
          File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
            cursor.execute(statement, parameters)
        sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'RowProxy'
        [SQL: -- From /usr/lib/python3.6/site-packages/temboardui/model/queries/instances-insert.sql
        WITH environment AS (
            SELECT id FROM application.environments WHERE name = %(environment)s
        )
        INSERT INTO application.instances (agent_address, agent_port, hostname, pg_port, notify, comment, discover, discover_date, discover_etag, environment_id)
        SELECT
            %(agent_address)s AS agent_address,
            %(agent_port)s AS agent_port,
            %(hostname)s AS hostname,
            %(pg_port)s AS pg_port,
            %(notify)s AS notify,
            %(comment)s AS "comment",
            %(discover)s AS discover,
            %(discover_date)s AS discover_date,
            %(discover_etag)s AS discover_etag,
            environment.id AS environment_id
        FROM environment
        RETURNING *;

        ]
        [parameters: {'environment': (5, 'prod', 'instances de production', None, 5, 5, 'prod/dba', 'DBA'), 'agent_address': 'hostname.xxx.yyy', 'agent_port': 2345, 'hostname': 'hostname.xxx.yyy', 'pg_port': 5432, 'notify': False, 'comment': 'Registered from CLI.', 'discover': '{"postgres": {"version": "PostgreSQL 15.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3), 64-bit", "version_summary ... (1822 characters truncated) ... "15.7", "psycopg2_version": "2.9.9 (dt dec pq3 ext lo64)", "python_version": "3.9.18", "pythonbin": "/usr/bin/python3"}, "signature_status": "valid"}', 'discover_date': datetime.datetime(2024, 10, 28, 15, 53, 42, 193074, tzinfo=datetime.timezone.utc), 'discover_etag': '873930080efc2f6c5e13a89ca16251b26bbb25271e5119fea508b1bf6b146d31'}]
        (Background on this error at: http://sqlalche.me/e/f405)
ERROR:  app: temboardui version is 9.0.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! 
```

Thanks!

The agent and server are on version 9.0.0.
Server :
```
temboard --version
INFO:  app: Starting temboard 9.0.0.
temBoard 9.0.0 (/usr/bin/temboard)
System Red Hat Enterprise Linux 8.10 (Ootpa)
Python 3.6.8 (/usr/libexec/platform-python)
cryptography 3.2.1
Tornado 6.0.2
Flask 0.12.2
libpq 15.7
psycopg2 2.9.5 (dt dec pq3 ext lo64)
SQLAlchemy 1.3.2
```

Agent:
```
temboard-agent --version
INFO:  app: Starting temboard-agent 9.0.0.
temBoard agent 9.0.0 (/usr/bin/temboard-agent)
System Red Hat Enterprise Linux 9.4 (Plow)
Python 3.9.18 (/usr/bin/python3)
bottle 0.12.21
cryptography 36.0.1
libpq 15.7
psycopg2 2.9.9 (dt dec pq3 ext lo64)
```

Is there a workaround or what did i do wrong ?

**Comment by vidierr** [comment]
Hello,
I tried this morning with an agent 8.2.1 and there is the same error.

**Comment by pirlgon** [comment]
Thanks for reporting this, we 'll investigate quickly

**Comment by vidierr** [comment]
The new version fixes the bug
