### ISSUE TITLE
Problem on enabling temboard agent

### ISSUE THREAD

**Issue by jmarsac** [dalibo/temboard#1543]
System :

Distributor ID: Debian
Description:  Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:   bullseye

I get following error (I used Guillaume's [guide](https://blog.dalibo.com/2024/11/18/lp4.html) )

```sh
sde22@srvsdesig:~$ sudo -u postgres temboard-agent -c /etc/temboard-agent/13/main/temboard-agent.conf fetch-key
INFO:  app: Starting temboard-agent 9.0.0.
INFO:  app: Using config file /etc/temboard-agent/13/main/temboard-agent.conf.
INFO:  fetch_key: Requesting public key from https://localhost.localdomain:8888.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/app.py", line 312, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/python3/dist-packages/temboardagent/cli/app.py", line 127, in main
            return command.main(args)
          File "/usr/lib/python3/dist-packages/temboardagent/cli/fetch_key.py", line 43, in main
            response = ui_client.get("/signing.key")
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/http.py", line 129, in get
            return self.request("GET", path, headers)
          File "/usr/lib/python3/dist-packages/temboardagent/toolkit/http.py", line 110, in request
            conn.request(method, path, body, headers)
          File "/usr/lib/python3.9/http/client.py", line 1259, in request
            self._send_request(method, url, body, headers, encode_chunked)
          File "/usr/lib/python3.9/http/client.py", line 1305, in _send_request
            self.endheaders(body, encode_chunked=encode_chunked)
          File "/usr/lib/python3.9/http/client.py", line 1254, in endheaders
            self._send_output(message_body, encode_chunked=encode_chunked)
          File "/usr/lib/python3.9/http/client.py", line 1014, in _send_output
            self.send(msg)
          File "/usr/lib/python3.9/http/client.py", line 954, in send
            self.connect()
          File "/usr/lib/python3.9/http/client.py", line 1421, in connect
            super().connect()
          File "/usr/lib/python3.9/http/client.py", line 925, in connect
            self.sock = self._create_connection(
          File "/usr/lib/python3.9/socket.py", line 822, in create_connection
            for res in getaddrinfo(host, port, 0, SOCK_STREAM):
          File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
            for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        socket.gaierror: [Errno -2] Name or service not known
ERROR:  app: temboardagent version is 9.0.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
```

Thanks in advance for your help

**Comment by jmarsac** [comment]
Bonjour Etienne,

Au temps pour moi, _localhost.localdomain_ était absent de _hosts_ et _getent_ ne me rendait pas la main.

**Comment by jmarsac** [comment]
Je laisse ouvert en attendant la gestion de ce cas de configuration.
