### ISSUE TITLE
Crash when using temboard migratedb

### ISSUE THREAD

**Issue by jmarsac** [dalibo/temboard#1545]
Hello,

I got this log when migrating temboard database after update

```sh
root@srvsdesig:/var/log# temboard migratedb check
INFO:  app: Starting temboard. version=9.0.1
INFO:  app: Using config file /etc/temboard/temboard.conf.
ERROR:  app: Unhandled error:
        Traceback (most recent call last):
          File "/usr/lib/temboard/temboardui/toolkit/app.py", line 308, in entrypoint
            retcode = self.main(argv, environ)
          File "/usr/lib/temboard/temboardui/cli/app.py", line 116, in main
            return command.main(args)
          File "/usr/lib/temboard/temboardui/cli/migratedb.py", line 38, in main
            with self.parent.make_conn() as conn:
          File "/usr/lib/temboard/temboardui/cli/migratedb.py", line 28, in make_conn
            return closing(connect(format_dsn(self.app.config.repository)))
          File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
            conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
        psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  authentification peer échouée pour l'utilisateur « temboard »

ERROR:  app: temboardui version is 9.0.1.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!

```
Error due to this context ?

```sh
root@srvsdesig:/var/log# root@srvsdesig:/var/log# ls /var/run/postgresql
13-main.pg_stat_tmp  13-main.pid
root@srvsdesig:/var/log#
```
TIA

**Comment by vidierr** [comment]
you need to execute this with the user temboard or by using sudo :
sudo -u temboard temboard migratedb check

**Comment by jmarsac** [comment]
Thank you @vidierr
