### ISSUE TITLE
[supervision] Error with some graph

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#17]
When I go to ```/server/0.0.0.0/2345/supervision/week``, the graphs won't load and I get the error belown in the log 

```
2016-10-31 11:14:24,376 temboard[20449]: [temboard] INFO: 500 GET /server/0.0.0.0/2345/supervision/data/waiting_locks?start=2016-10-24T11:14:22&end=2016-10-31T11:14:22 (90.78.76.123) 140.75ms
2016-10-31 11:14:24,381 temboard[20449]: [temboard] DEBUG: Traceback (most recent call last):
2016-10-31 11:14:24,382 temboard[20449]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/plugins/supervision/__init__.py", line 246, in get_data_probe
2016-10-31 11:14:24,383 temboard[20449]: [temboard] DEBUG:     data = get_locks(self.db_session, instance.hostname, instance.pg_port, start_time, end_time)
2016-10-31 11:14:24,383 temboard[20449]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/plugins/supervision/chartdata.py", line 208, in get_locks
2016-10-31 11:14:24,384 temboard[20449]: [temboard] DEBUG:     cur.copy_expert(query % (tablename, hostname, port, start.strftime('%Y-%m-%dT%H:%M:%S'), end.strftime('%Y-%m-%dT%H:%M:%S')), data_buffer)
2016-10-31 11:14:24,384 temboard[20449]: [temboard] DEBUG: ProgrammingError: relation "supervision.metric_locks_10m" does not exist
2016-10-31 11:14:24,385 temboard[20449]: [temboard] DEBUG: LINE 1: ...) AS access_exclusive, SUM(siread) AS siread FROM supervisio...
2016-10-31 11:14:24,386 temboard[20449]: [temboard] DEBUG:                                                              ^
2016-10-31 11:14:24,387 temboard[20449]: [temboard] DEBUG: 
2016-10-31 11:14:24,387 temboard[20449]: [temboard] ERROR: relation "supervision.metric_locks_10m" does not exist
LINE 1: ...) AS access_exclusive, SUM(siread) AS siread FROM supervisio...
                                                             ^

2016-10-31 11:14:24,390 temboard[20449]: [temboard] INFO: 500 GET /server/0.0.0.0/2345/supervision/data/locks?start=2016-10-24T11:14:22&end=2016-10-31T11:14:22 (90.78.76.123) 174.98ms
```

The ``supervision.sql`` is correctly loaded 

```
temboard=# \d
                       List of relations
   Schema    |             Name              | Type  |  Owner   
-------------+-------------------------------+-------+----------
 application | access_role_instance          | table | temboard
 application | groups                        | table | temboard
 application | instance_groups               | table | temboard
 application | plugins                       | table | temboard
 application | role_groups                   | table | temboard
 application | roles                         | table | temboard
 supervision | hosts                         | table | temboard
 supervision | instances                     | table | temboard
 supervision | metric_bgwriter               | table | temboard
 supervision | metric_blocks                 | table | temboard
 supervision | metric_cpu                    | table | temboard
 supervision | metric_db_size                | table | temboard
 supervision | metric_filesystems_size       | table | temboard
 supervision | metric_loadavg                | table | temboard
 supervision | metric_locks                  | table | temboard
 supervision | metric_memory                 | table | temboard
 supervision | metric_process                | table | temboard
 supervision | metric_replication            | table | temboard
 supervision | metric_sessions               | table | temboard
 supervision | metric_tblspc_size            | table | temboard
 supervision | metric_temp_files_size_db     | table | temboard
 supervision | metric_temp_files_size_tblspc | table | temboard
 supervision | metric_vacuum_analyze         | table | temboard
 supervision | metric_wal_files              | table | temboard
 supervision | metric_xacts                  | table | temboard
(25 rows)
```

**Comment by julmon** [comment]
Theses tables are created (if they don't exist) when running the aggregator script `metric-aggregator` (user `temboard`). Execution of this script should be planed using a crontjob every 15 minutes.
We need to add this in the documentation I guess.

**Comment by daamien** [comment]
Confirmed. Launching ``sudo -u temboard ./metric-aggregator`` fixes the problem

I'll modify the doc and provide a readymade cronjob file to add in /etc/cron.d
