### ISSUE TITLE
[supervision] Error with /server/0.0.0.0/2345/supervision/data/blocks

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#18]
I get this error when going to  ``/server/0.0.0.0/2345/supervision/week``

The ''Filesystems size'' and ''Filesystems usage'' graphs are not displaid.

```
2016-10-31 17:42:15,405 temboard[8671]: [temboard] INFO: 200 GET /server/0.0.0.0/2345/supervision/data/blocks?start=2016-10-30T17:42:13&end=2016-10-31T17:42:13 (90.78.76.123) 446.22ms
2016-10-31 17:42:15,411 temboard[8671]: [temboard] DEBUG: Traceback (most recent call last):
2016-10-31 17:42:15,416 temboard[8671]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/plugins/supervision/__init__.py", line 254, in get_data_probe
2016-10-31 17:42:15,417 temboard[8671]: [temboard] DEBUG:     data = get_tblspc_size(self.db_session, instance.hostname, instance.pg_port, start_time, end_time)
2016-10-31 17:42:15,417 temboard[8671]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/plugins/supervision/chartdata.py", line 303, in get_tblspc_size
2016-10-31 17:42:15,417 temboard[8671]: [temboard] DEBUG:     cur.copy_expert(q_copy.format(col=col, tablename=tablename, hostname=hostname, port=port, start_datetime=start_datetime, end_datetime=end_datetime, col_type=col_type), data_buffer)
2016-10-31 17:42:15,417 temboard[8671]: [temboard] DEBUG: ProgrammingError: query-specified return tuple and crosstab function are not compatible
2016-10-31 17:42:15,418 temboard[8671]: [temboard] DEBUG: 
2016-10-31 17:42:15,418 temboard[8671]: [temboard] ERROR: query-specified return tuple and crosstab function are not compatible
```

**Comment by julmon** [comment]
Do you have any postgres error raised at the same time ?

**Comment by daamien** [comment]
```
2016-11-06 16:51:15 CET ERROR:  query-specified return tuple and crosstab function are not compatible
2016-11-06 16:51:15 CET STATEMENT:  COPY (SELECT to_char(datetime, 'YYYY/MM/DD HH24:MI:SS') AS Date  FROM crosstab('SELECT datetime, spcname, size FROM supervision.metric_tblspc_size_10m WHERE hostname = ''redtail.taadeem.net'' AND port = 5434 AND datetime >= ''2016-10-30T16:51:13'' AND datetime <= ''2016-11-06T16:51:13'' ORDER BY 1,2 ASC', 'SELECT DISTINCT(spcname) FROM supervision.metric_tblspc_size_10m WHERE hostname = ''redtail.taadeem.net'' AND port = 5434 AND datetime >= ''2016-10-30T16:51:13'' AND datetime <= ''2016-11-06T16:51:13'' ORDER BY spcname') AS ct(datetime timestamp with time zone )) TO STDOUT WITH CSV HEADER
2016-11-06 16:51:15 CET ERROR:  query-specified return tuple and crosstab function are not compatible
2016-11-06 16:51:15 CET STATEMENT:  COPY (SELECT to_char(datetime, 'YYYY/MM/DD HH24:MI:SS') AS Date  FROM crosstab('SELECT datetime, mount_point, used FROM supervision.metric_filesystems_size_10m WHERE hostname = ''redtail.taadeem.net'' AND datetime >= ''2016-10-30T16:51:13'' AND datetime <= ''2016-11-06T16:51:13'' ORDER BY 1,2 ASC', 'SELECT DISTINCT(mount_point) FROM supervision.metric_filesystems_size_10m WHERE hostname = ''redtail.taadeem.net'' AND datetime >= ''2016-10-30T16:51:13'' AND datetime <= ''2016-11-06T16:51:13'' ORDER BY mount_point') AS ct(datetime timestamp with time zone )) TO STDOUT WITH CSV HEADER
2016-11-06 16:51:15 CET ERROR:  query-specified return tuple and crosstab function are not compatible
2016-11-06 16:51:15 CET STATEMENT:  COPY (SELECT to_char(datetime, 'YYYY/MM/DD HH24:MI:SS') AS Date  FROM crosstab('SELECT datetime, mount_point, round(((used::FLOAT/total::FLOAT)*100)::numeric, 1) AS usage FROM supervision.metric_filesystems_size_10m WHERE hostname = ''redtail.taadeem.net'' AND datetime >= ''2016-10-30T16:51:13'' AND datetime <= ''2016-11-06T16:51:13'' ORDER BY 1,2 ASC', 'SELECT DISTINCT(mount_point) FROM supervision.metric_filesystems_size_10m WHERE hostname = ''redtail.taadeem.net'' AND datetime >= ''2016-10-30T16:51:13'' AND datetime <= ''2016-11-06T16:51:13'' ORDER BY mount_point') AS ct(datetime timestamp with time zone )) TO STDOUT WITH CSV HEADER
```
