### ISSUE TITLE
temBoard Server - SSLError: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:2521)

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#193]
Experiencing the following:

```
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'dashboard'.
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'dashboard' configuration.
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'pgconf'.
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'pgconf' configuration.
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'activity'.
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'activity' configuration.
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'monitoring'.
temboard[20448]: [temboardui.pluginsmgmt  ]     INFO: Loading plugin 'monitoring' configuration.
temboard[20448]: [temboardui              ]     INFO: Starting task manager.
temboard[20448]: [temboardui              ]     INFO: Starting temboardui on https://0.0.0.0:8888
temboard[20448]: [tornado.application     ]    ERROR: Exception in callback (<socket._socketobject object at 0x3ea6600>, <function null_wrapper at 0x3ec5320>)
temboard[20448]: [tornado.application     ]    ERROR: Traceback (most recent call last):
temboard[20448]: [tornado.application     ]    ERROR:   File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 882, in start
temboard[20448]: [tornado.application     ]    ERROR:     handler_func(fd_obj, events)
temboard[20448]: [tornado.application     ]    ERROR:   File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
temboard[20448]: [tornado.application     ]    ERROR:     return fn(*args, **kwargs)
temboard[20448]: [tornado.application     ]    ERROR:   File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 273, in accept_handler
temboard[20448]: [tornado.application     ]    ERROR:     callback(connection, address)
temboard[20448]: [tornado.application     ]    ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/autossl.py", line 164, in _handle_connection
temboard[20448]: [tornado.application     ]    ERROR:     do_handshake_on_connect=False)
temboard[20448]: [tornado.application     ]    ERROR:   File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 509, in ssl_wrap_socket
temboard[20448]: [tornado.application     ]    ERROR:     context = ssl_options_to_context(ssl_options)
temboard[20448]: [tornado.application     ]    ERROR:   File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 486, in ssl_options_to_context
temboard[20448]: [tornado.application     ]    ERROR:     context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
temboard[20448]: [tornado.application     ]    ERROR: SSLError: [X509: KEY_VALUES_MISMATCH] key values mismatch (_ssl.c:2521)
```

Conf file is as follows:

```
[root@pem01 temboard]# cat temboard.conf
[temboard]
# Bind port
port = 8888
# Bind address
address = 0.0.0.0
# SSL: certificat file path (.pem)
ssl_cert_file = /etc/temboard/ssl/temboard.pem
# SSL: private key file path (.key)
ssl_key_file = /etc/temboard/ssl/temboard.key
# SSL: CA cert file
# This file must contains SSL cert of each agent that the UI can establish a connexion to.
ssl_ca_cert_file = /etc/temboard/ssl/ca_certs_localhost.pem
# Cookie secret key
cookie_secret = ***********
# Plugins
plugins = ["dashboard", "pgconf", "activity", "monitoring"]
# Array of plugins requiring a PG connexion to the repository.
plugins_orm_engine = ["monitoring"]
# Working dir
home = /var/run/temboard

[repository]
# Unix socket path.
#host = /var/run/postgresql
host=127.0.0.1
# PG port number.
port = 45221
# User name.
user = temboard
# User password.
password = ******
# Database name.
dbname = temboard

[logging]
# Available methods for logging: stderr, syslog or file
#method = stderr
method = file
# Syslog facility.
# facility = local0
# Log destination, should be /dev/log for syslog on Linux.
# When using file logging method, this is referencing the log file path.
destination = /var/log/temboard/temboard.log
# Default log level.
level = INFO
```

**Comment by bersace** [comment]
Hi @bsislow . It looks like tornado is not able to use your certificate. The private key does not match the certificate. If unsure, try to use it with e.g. nginx to validate all SSL files and test it back with temboard.

**Comment by bsislow** [comment]
Thank you. We will work with our System Admins on this.

[ale]<http://www.accertify.com/>

Bob Sislow
Lead Database Administrator
Accertify, Inc., an American Express Company
Phone: 312.613.4982
Email: bsislow@accertify.com<mailto:bsislow@accertify.com>
Web: www.accertify.com<http://www.accertify.com/>
[cid:image002.png@01D1CBBF.6EE1AA10]<https://www.linkedin.com/company/accertify-inc->

**Comment by bersace** [comment]
Let's close. Please reopen if you need further assistance.
