### ISSUE TITLE
Registered instances not being monitored

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#195]
I have 2 instances that I have just added to temboard via the GUI, and they appear listed in the GUI and I can look at their dashboards BUT nothing appears in their monitoring screens.

There is an error in the temboard server logfile:

temboard[  653]: [temboardui              ]    
ERROR: Exception: Can't find host_id for "binderdbpg02.ams.accertify.net" in monitoring.hosts table.

and if I check the temboard database I can't see these 2 instances listed in the monitoring.hosts table, just the 1 instance I added a few days ago:

temboard=# select * from monitoring.hosts;
 host_id |        hostname         |  os   |         os_version         | os_flavour | cpu_count | cpu_arch | memory_size
 | swap_size | virtual
---------+-------------------------+-------+----------------------------+------------+-----------+----------+------------
-+-----------+---------
       1 | pem01.ams.accertify.net | Linux | 3.10.0-514.26.2.el7.x86_64 |            |        16 | x86_64   | 33567145984
 |           |
(1 row)

The database that is listed is running temboard-agent==0.0.2, the 2 I am having problems with are running temboard-agent==0.0.1.

**Comment by bersace** [comment]
@dgiffin Thanks for the report.

Can you use latest alpha ? `pip install --pre --upgrade temboard-agent` ?

**Comment by dgiffin** [comment]
I'll talk to our SysAdmin team and get back to you - thanks.

**Comment by dgiffin** [comment]
We have upgraded:

[dgiffin@binderdbpg01 ~]$ pip freeze|grep temb
temboard-agent==1.0a5

but it hasn't helped, I can add a new instance in the GUI and monitor it via the dashboard option but it isn't being added to the temboard database. I CAN successfully add an instance that is running on the same host as the temboard server though.

Config and log files attached.
[temboard.conf.gz](https://github.com/dalibo/temboard/files/1320388/temboard.conf.gz)
[temboard.log.gz](https://github.com/dalibo/temboard/files/1320389/temboard.log.gz)
[temboard-agent.conf.gz](https://github.com/dalibo/temboard/files/1320390/temboard-agent.conf.gz)
[temboard-agent.log.gz](https://github.com/dalibo/temboard/files/1320387/temboard-agent.log.gz)

**Comment by bersace** [comment]
I think the error is :

**Comment by bersace** [comment]
@julmon any idea ?

**Comment by bersace** [comment]
hrm:

```
2017-09-21 07:57:01,296 temboard-agent[2449]: [monitoring_sender_worker] ERROR: 'NoneType' object has no attribute 'strip'
```
@dgiffin can you reproduce this with debug logs ? Thanks !

**Comment by dgiffin** [comment]
Done...
[temboard-agent.log.gz](https://github.com/dalibo/temboard/files/1320952/temboard-agent.log.gz)

**Comment by bersace** [comment]
@dgiffin thanks !

@julmon  the trace is:

```
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG: Traceback (most recent call last):
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 1084, in monitoring_sender_worker
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:     msg.content)
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/output.py", line 34, in send_output
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:     data=json.loads(j_output)
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardagent/httpsclient.py", line 90, in https_request
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:     request = RequestWithMethod(url, data=json.dumps(data), method=method)
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardagent/httpsclient.py", line 67, in __init__
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:     urllib2.Request.__init__(self, *args, **kwargs)
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:   File "/usr/lib64/python2.7/urllib2.py", line 229, in __init__
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:     self.__original = unwrap(url)
2017-09-21 11:25:21,360 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:   File "/usr/lib64/python2.7/urllib.py", line 1057, in unwrap
2017-09-21 11:25:21,361 temboard-agent[58402]: [monitoring_sender_worker] DEBUG:     url = url.strip()
2017-09-21 11:25:21,361 temboard-agent[58402]: [monitoring_sender_worker] DEBUG: AttributeError: 'NoneType' object has no attribute 'strip'
2017-09-21 11:25:21,361 temboard-agent[58402]: [monitoring_sender_worker] ERROR: 'NoneType' object has no attribute 'strip'
2017-09-21 11:25:21,361 temboard-agent[58402]: [monitoring_sender_worker] DEBUG: Duration: 523.745849609.
2017-09-21 11:25:21,361 temboard-agent[58402]: [monitoring_sender_worker] DEBUG: Failed.
```

Any idea ?

**Comment by bsislow** [comment]
Hello,

I am on David's team. We also do not see graphs being populated and we are on the latest version.

I started a case about graphs not being populated for version 0.0.1 but now we see the same behavior.

See below - I chose a one week range and we only see data for that "blip" during the morning of 18Sep2017.

Could this be related?

Apologies if not - you can spin this off to a new case if needed.

![tem_charts](https://user-images.githubusercontent.com/30243584/30703595-c4fcbece-9eb5-11e7-82da-262e31c72f72.JPG)

**Comment by bsislow** [comment]
The agent was upgraded on 9/20/2017 if this helps. Perhaps related, perhaps not. We cannot distinguish at this point.

**Comment by dgiffin** [comment]
I just restarted the temboard server with the log level set to DEBUG and tried to remove the existing instance and add a new one. I got no errors in the GUI but the monitoring.hosts and monitoring.instances tables weren't updated for either actions.
[temboard.log.gz](https://github.com/dalibo/temboard/files/1324140/temboard.log.gz)

**Comment by dgiffin** [comment]
We have a hard go-live date for these environments coming up and need to resolve our monitoring problems before that happens. If we can't make progress with this version we may have to look at reverting to the old versions (0.0.1) which had problems with the monitoring charts but does seem slightly more functional at the moment.

**Comment by julmon** [comment]
Hi,

It seems you have an issue with the configuration file of your temboard agents. `[supervision]` section has been renamed to `[monitoring]`. Could you please update `temboard-agent.conf` accordng to this, and restart the agents. 

Regards,

**Comment by dgiffin** [comment]
Done it - made no difference, sorry.

**Comment by bersace** [comment]
@dgiffin no worry ! Please tell us once you've gone live ! :-)

**Comment by bersace** [comment]
@dgiffin sorry, i misread your comment :/

**Comment by bersace** [comment]
@dgiffin can you tell us what's in table `monitoring.hosts` ? I'm wondering if there is a mismatch of FQDN.

**Comment by julmon** [comment]
@dgiffin could you please attach the logs from the agent since you've made the changes in the configuration file ?

Thanks,

**Comment by dgiffin** [comment]
pem01.ams.accertify.net:/home/postgres(postgres:45221)$ psql -d temboard -U temboard
psql (9.6.3)
Type "help" for help.

temboard=# select * from monitoring.hosts;
 host_id |        hostname         |  os   |         os_version         | os_flavour | cpu_count | cpu_arch | memory_size
 | swap_size | virtual
---------+-------------------------+-------+----------------------------+------------+-----------+----------+------------
-+-----------+---------
       1 | pem01.ams.accertify.net | Linux | 3.10.0-514.26.2.el7.x86_64 |            |        16 | x86_64   | 33567145984
 |           |
(1 row)

**Comment by bersace** [comment]
@dgiffin is `pem01.ams.accertify.net` the same host as `binderdbpg01.ams.accertify.net`.

@dgiffin I guess you should re-register if you renamed `[monitoring]` section.

**Comment by dgiffin** [comment]
No, two different hosts, binderdbpg01.ams is the one I am trying to register. For info, using the temboard GUI, I remove the pem01.ams host/database but as you can see, it's still listed in the table. Maybe these are related?

**Comment by bersace** [comment]
@dgiffin no, I guess this should be cleaned by monitoring plugin. But I don't think it's related.

**Comment by bersace** [comment]
@dgiffin did you re-register `binderdbpg01` ?

**Comment by dgiffin** [comment]
Yes, that is the one I have been trying to register, unsuccessfully.

**Comment by julmon** [comment]
Hi @dgiffin,

It looks that the configuration file of the agent is still not valid:
```
2017-09-22 11:26:31,512 temboard-agent[52447]: [temboard-agent] INFO: Loading plugin 'monitoring' configuration.
2017-09-22 11:26:31,514 temboard-agent[52447]: [temboard-agent] INFO: No configuration.
```

Meaning that `temboard-agent` didn't find any valid conf for `monitoring` plugin.

Thanks,

**Comment by dgiffin** [comment]
This is the temboard-agent.conf file - can you see what I've got wrong?

[temboard-agent.conf.gz](https://github.com/dalibo/temboard/files/1324592/temboard-agent.conf.gz)

**Comment by julmon** [comment]
@dgiffin this time, your config file is right, but we've found an issue, this commit fixes it : https://github.com/dalibo/temboard-agent/pull/50/commits/4d70d9d91cbd561c1de56bd45021edcd5f7ee438

**Comment by bsislow** [comment]
This appears to have fixed the issue. Charts are now populating. Please leave this open for a few days so we can confirm long-term functionality and accuracy. Thank you.

**Comment by bersace** [comment]
@julmon great ! Thanks @bsislow for reporting :-)
