### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by shadmar** [dalibo/temboard#244]
I followed the instruction from 
http://temboard-agent.readthedocs.io/en/latest/temboard-agent-install-sources.html
and
http://temboard.readthedocs.io/en/latest/temboard-install-sources/

But no matter what I do I always end up getting this:
![image](https://user-images.githubusercontent.com/2836201/34513155-fad06516-f066-11e7-8c5f-8d39b98fc08b.png)

I tested using the certificates supplied, and making my own, but both results in :
ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>

Server log:

2018-01-03 09:19:18,962 temboard[56524]: [temboardui              ]     INFO: Getting discovery.
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]    ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]    ERROR: Traceback (most recent call last):
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]    ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/handlers/settings/instance.py", line 345, in get_discover
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]    ERROR:     self.ssl_ca_cert_file, agent_address, agent_port)
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]    ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/temboardclient.py", line 378, in temboard_discover
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]    ERROR:     raise TemboardError(500, str(e))
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]    ERROR: TemboardError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>
2018-01-03 09:19:18,977 temboard[56524]: [temboardui              ]     INFO: Failed.
2018-01-03 09:19:18,978 temboard[56524]: [temboardui              ]     INFO: 500 GET /json/discover/instance/uil0ski-pilot-pgsql02.skead.no/2345 (151.187.81.25) 16.67ms

**Comment by julmon** [comment]
Did you try to comment out both `ssl_ca_cert_file` parameters from `temboard.conf` and `temboard-agent.conf` files ?

**Comment by shadmar** [comment]
If I comment ssl_ca_cert_file on both config files and restart both agent and server I get the exact same result.

server log after change:

2018-01-03 09:48:18,337 temboard[61349]: [temboardui              ]     INFO: Getting discovery.
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]    ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]    ERROR: Traceback (most recent call last):
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]    ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/handlers/settings/instance.py", line 345, in get_discover
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]    ERROR:     self.ssl_ca_cert_file, agent_address, agent_port)
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]    ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/temboardclient.py", line 378, in temboard_discover
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]    ERROR:     raise TemboardError(500, str(e))
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]    ERROR: TemboardError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>
2018-01-03 09:48:18,362 temboard[61349]: [temboardui              ]     INFO: Failed.
2018-01-03 09:48:18,363 temboard[61349]: [temboardui              ]     INFO: 500 GET /json/discover/instance/uil0ski-pilot-pgsql02.skead.no/2345 (151.187.81.25) 26.55ms

**Comment by julmon** [comment]
Could you please attach the configuration files ?

**Comment by shadmar** [comment]
`
[root@uil0ski-pilot-pgsql02 /etc/temboard-agent]# cat temboard-agent.conf
[temboard]
# Bind port.
port = 2345
# Bind address.
address = 0.0.0.0
# User & password file.
users = users
# Plugins in use.
plugins = ["monitoring", "dashboard", "pgconf", "administration", "activity"]
# SSL: certificat file path (.pem)
ssl_cert_file = /etc/temboard-agent/temboard-agent_CHANGEME.pem
# SSL: private key file path (.key)
ssl_key_file = /etc/temboard-agent/temboard-agent_CHANGEME.key
# Hostname must be an unique and valid FQDN : e.g. db1.mydomain.foo
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
hostname = uil0ski-pilot-pgsql02.skead.no
# Key
key = JHKSDGFJHSDBF89874JKS

[postgresql]
# Unix socket path.
host = /var/run/postgresql
# PG port number.
port = 5432
# Super-user name.
user = postgres
# Super-user password.
# password =
# Default database.
dbname = postgres
# Instance name.
instance = main

[logging]
# Available methods for logging: stderr, syslog or file
method = stderr
# Syslog facility.
# facility = local0
# Log destination, should be /dev/log for syslog on Linux system.
# When using file logging method, this is referencing the log file path.
# destination = /var/log/temboard-agent/temboard-agent.log
# Log level, can be: DEBUG, INFO, WARNING, ERROR or CRITICAL.
level = INFO

### PLUGINS ###
[dashboard]
# Dashboard plugin part
# Interval, in second, between each run of the process collecting
# data used to render the dashboard. Default: 2
# scheduler_interval = 2
# Number of record to keep. Default: 20
# history_length = 20

[monitoring]
# Monitoring plugin part.
# DB name list (comma separator) to supervise. * for all.
dbnames = *
# Collector URL. (defaults to TEMBOARD_MONITORING_COLLECTOR_URL env var)
# collector_url = https://0.0.0.0:8888/monitoring/collector
# List of probes to run, comma separator, * for all.
# Available probes: locks,process,db_size,tblspc_size,sessions,blocks,xacts,replication,loadavg,filesystems_size,cpu,bgwriter,memory,wal_files
# when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
probes = *
# Interval, in second, between each run of the process executing
# the probes. Default: 60
# scheduler_interval = 60
# File where to store collector's SSL certificate.
#ssl_ca_cert_file = /etc/temboard-agent/temboard_ca_certs_CHANGEME.pem

[administration]
# External command used for start/stop PostgreSQL.
# This commands actually works on Debian jessie.
pg_ctl = '/usr/lib/postgresql/9.4/bin/pg_ctl %s -D /var/lib/postgresql/9.4'

`

**Comment by julmon** [comment]
I need also server configuration file please. Thanks.

**Comment by shadmar** [comment]
[temboard-conffiles.zip](https://github.com/dalibo/temboard/files/1599881/temboard-conffiles.zip)

**Comment by julmon** [comment]
Wich temboard and temboard-agent versions is it ?

**Comment by shadmar** [comment]
I used the master versions from github on both, 27 december I think,
I am running RHEL7

**Comment by julmon** [comment]
I'd recommend you to move to RPM packages then : 

- http://temboard-agent.readthedocs.io/en/latest/temboard-agent-install-rpm.html
- http://temboard.readthedocs.io/en/latest/temboard-install-rpm/

When installing temboard server & agent from RPM, new SSL self-signed certificates are built and default SSL configuration should work fine.

**Comment by shadmar** [comment]
Ok I will give the RPMs a try, thank you.

**Comment by shadmar** [comment]
rpm's work and I dont get this error
