### ISSUE TITLE
errors monitoring repmgr standby database

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#247]
v1.1
Configured a PostgreSQL hot standby database (using repmgr) in for monitoring and everything seems to be working fine except for these errors in the temboard-agent log:

2018-01-12 06:28:31,841 temboard-agent[150375]: [root] ERROR: Unable to run probe "wal_files" on "ariddbpg02-ams" on database "postgres"
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR: list index out of range
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR: Traceback (most recent call last):
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 995, in monitoring_collector_worker
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR:     data = run_probes(probes, instances)
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/probes.py", line 61, in run_probes
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR:     out += p.run(i)
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/probes.py", line 627, in run
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR:     metric['total'] = rows[0]['total']
2018-01-12 06:28:31,842 temboard-agent[150375]: [monitoring] ERROR: IndexError: list index out of range

**Comment by dgiffin** [comment]
Also, for this standby database the temboard GUI Monitoring screen never loads, I just get the "Loading, please wait" messages displayed. I assume this is related?

**Comment by julmon** [comment]
`1.2` is out, including fixes about this issue.
