### ISSUE TITLE
temboard-agent-adduser : ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by GReboute** [dalibo/temboard#251]
Tested on Linux server.
Red Hat kernel 3.10.0-693.11.6.el7.x86_64

Agent 1.1 (temboard-agent-1.1.tar.gz)

As root : 
```
useradd -M -r -d /pgsql/temboard-agent/ temboard
usermod -a -G postgres,dba temboard

sudo -u temboard temboard-agent-adduser

ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/cli.py", line 41, in cli_wrapper
ERROR:     retcode = main(argv, environ) or 1
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/adduser.py", line 70, in main
ERROR:     username = ask_username(config)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/adduser.py", line 39, in ask_username
ERROR:     get_user(config.temboard['users'], raw_username)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/usermgmt.py", line 39, in get_user
ERROR:     (l_username, l_hpasswd) = line.strip().split(':')
ERROR: ValueError: need more than 1 value to unpack
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard-agent/issues! Thanks!
```

**Comment by GReboute** [comment]
Remark : 
Multiples instances (cluster) on the server listening on different ports
2 different PG versions (9.4 and 9.6)

**Comment by julmon** [comment]
Could you please attach your `users` file (passwords are hashed) ? It seems that your file is not well formatted.

**Comment by gderenne** [comment]
Hi,
I had same issue. 
I solved it by removing file and CHOWNed it to postgres user and group.
(Linux CentOS7 fr installed from RPMs).

**Comment by julmon** [comment]
Fixed by https://github.com/dalibo/temboard-agent/pull/217/commits/bd513335a2e6978dc028bfe85fe91369be7db534
