### ISSUE TITLE
Problem with old version setup

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#259]
I'm trying to build an old version in dev so we can test the upgraded process to the latest build in our production environment:

temboard-agent-0.0.1-10.el7.centos.noarch
temboard-0.0.1-10.el7.centos.noarch

I am getting an error when I try to add an instance:

2018-02-16 02:31:32,776 temboard[2815]: [temboard] ERROR: Can't check agent's key.
2018-02-16 02:31:32,778 temboard[2815]: [temboard] INFO: 500 POST /supervision/collector (10.244.5.140) 4.79ms
2018-02-16 02:31:37,789 temboard[2815]: [temboard] INFO: Getting group list.
2018-02-16 02:31:37,798 temboard[2815]: [temboard] INFO: Done.
2018-02-16 02:31:37,799 temboard[2815]: [temboard] INFO: 200 GET /json/manage/all/group/instance (10.244.244.121) 10.25ms
2018-02-16 02:31:39,962 temboard[2815]: [temboard] ERROR: Can't check agent's key.
2018-02-16 02:31:39,963 temboard[2815]: [temboard] INFO: 500 POST /supervision/collector (10.244.5.142) 4.48ms

I know I've done or forgotten something obvious, but I can't track it down in the docs, any chance of pointing out where I've gone wrong?

**Comment by julmon** [comment]
Hi,

In temboard-agent's configuration file, under `[temboard]` section, there is a parameter named `key` : https://github.com/dalibo/temboard-agent/blob/master/share/temboard-agent.conf#L19

The same key must be set into instance's detail form through the web UI.

**Comment by dgiffin** [comment]
Thanks, I've tried to add a new instance again, and I am using the correct "secret key" but it still fails.

temboard-agent log
2018-02-19 00:57:41,766 temboard-agent[27575]: [dashboard_collector] ERROR: list index out of range
2018-02-19 00:57:43,778 temboard-agent[27580]: [dashboard_collector] ERROR: list index out of range
2018-02-19 00:57:45,690 temboard-agent[2906]: [api] INFO: Starting discovery.
2018-02-19 00:57:45,706 temboard-agent[2906]: [api] ERROR: list index out of range
2018-02-19 00:57:45,706 temboard-agent[2906]: [api] INFO: Discovery failed.
2018-02-19 00:57:45,706 temboard-agent[2906]: [httpd] INFO: client: devpg-temp01.chi.accertify.net request: "GET /discover HTTP/1.1" 500 -
2018-02-19 00:57:45,788 temboard-agent[27586]: [dashboard_collector] ERROR: list index out of range
2018-02-19 00:57:47,789 temboard-agent[27594]: [dashboard_collector] ERROR: list index out of range

temboard log
2018-02-19 00:57:45,655 temboard[2815]: [temboard] INFO: Getting discovery.
2018-02-19 00:57:45,708 temboard[2815]: [temboard] ERROR: Internal error.
2018-02-19 00:57:45,709 temboard[2815]: [temboard] INFO: Failed.
2018-02-19 00:57:45,710 temboard[2815]: [temboard] INFO: 500 GET /json/discover/instance/devpg-temp01.chi/2345 (10.244.244.101) 56.97ms

**Comment by dgiffin** [comment]
I set the log_level for temboard to DEBUG, hope this helps:

2018-02-19 05:21:31,422 temboard[27743]: [temboard] INFO: Getting discovery.
2018-02-19 05:21:31,523 temboard[27743]: [temboard] DEBUG: Traceback (most recent call last):
2018-02-19 05:21:31,523 temboard[27743]: [temboard] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardui/handlers/manage/instance.py", line 288, in get_discover
2018-02-19 05:21:31,523 temboard[27743]: [temboard] DEBUG:     res = temboard_discover(self.ssl_ca_cert_file, agent_address, agent_port)
2018-02-19 05:21:31,524 temboard[27743]: [temboard] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardui/temboardclient.py", line 343, in temboard_discover
2018-02-19 05:21:31,524 temboard[27743]: [temboard] DEBUG:     raise TemboardError(e.code, json.loads(e.read())['error'])
2018-02-19 05:21:31,524 temboard[27743]: [temboard] DEBUG: TemboardError: Internal error.
2018-02-19 05:21:31,524 temboard[27743]: [temboard] ERROR: Internal error.
2018-02-19 05:21:31,524 temboard[27743]: [temboard] INFO: Failed.
2018-02-19 05:21:31,525 temboard[27743]: [temboard] INFO: 500 GET /json/discover/instance/10.244.5.141/2345 (10.244.244.101) 105.88ms
2018-02-19 05:21:34,381 temboard[27743]: [temboard] DEBUG: Traceback (most recent call last):
2018-02-19 05:21:34,381 temboard[27743]: [temboard] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/supervision/__init__.py", line 142, in push_data
2018-02-19 05:21:34,382 temboard[27743]: [temboard] DEBUG:     check_agent_key(thread_session, data['hostinfo']['hostname'], data['instances'][0]['data_directory'], data['instances'][0]['port'], key)
2018-02-19 05:21:34,382 temboard[27743]: [temboard] DEBUG:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/supervision/__init__.py", line 70, in check_agent_key
2018-02-19 05:21:34,382 temboard[27743]: [temboard] DEBUG:     raise Exception("Can't find the instance \"%s\" in application.instances table." % hostname)
2018-02-19 05:21:34,382 temboard[27743]: [temboard] DEBUG: Exception: Can't find the instance "devpg-temp01.chi.accertify.net" in application.instances table.
2018-02-19 05:21:34,382 temboard[27743]: [temboard] ERROR: Can't find the instance "devpg-temp01.chi.accertify.net" in application.instances table.
2018-02-19 05:21:34,383 temboard[27743]: [temboard] INFO: 500 POST /supervision/collector (10.244.5.140) 6.60ms
^C

**Comment by dgiffin** [comment]
I get that error regardless if I put in the correct or an incorrect secret key when trying to add the instance.

**Comment by julmon** [comment]
Could you please show content of table `application.instances` and agent configuration file?

Thanks

**Comment by dgiffin** [comment]
devpg-temp01.chi:/home/postgres(postgres:45221)$ psql -U temboard -d temboard
psql (10.1)
Type "help" for help.

temboard=> select * from application.instances;
 agent_address | agent_port | agent_key | hostname | cpu | memory_size | pg_port | pg_version | pg_data
---------------+------------+-----------+----------+-----+-------------+---------+------------+---------
(0 rows)

temboard=>

**Comment by dgiffin** [comment]
[temboard-agent.txt](https://github.com/dalibo/temboard/files/1747331/temboard-agent.txt)

**Comment by dgiffin** [comment]
Still getting the same error, but this time I 'SAVED' the incomplete agent setups in the GUI:

temboard=> select * from application.instances;
 agent_address | agent_port |                            agent_key                             | hostname | cpu | memory_s
ize | pg_port | pg_version | pg_data
---------------+------------+------------------------------------------------------------------+----------+-----+---------
----+---------+------------+---------
 10.244.5.140  |       2345 | YCO3HVpgDY5avNrMg4246gPqvfBnPPQppv5mVrLKpwlPYUW43TTMVXu41gIYotGK |          |     |
    |         |            |
 10.244.5.141  |       2345 | YCO3HVpgDY5avNrMg4246gPqvfBnPPQppv5mVrLKpwlPYUW43TTMVXu41gIYotGK |          |     |
    |         |            |
 10.244.5.142  |       2345 | YCO3HVpgDY5avNrMg4246gPqvfBnPPQppv5mVrLKpwlPYUW43TTMVXu41gIYotGK |          |     |
    |         |            |
(3 rows)

[temboard.log](https://github.com/dalibo/temboard/files/1757906/temboard.log)
[temboard-agent.log](https://github.com/dalibo/temboard/files/1757907/temboard-agent.log)
