### ISSUE TITLE
Tornado 5.0 support

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard#279]

**Comment by daftaupe** [comment]
Hello,

I'm trying to use Temboard on ArchLinux which provides python2-tornado 5.1.0.
I get the following error when trying to access the UI, and from what I understand it's linked to the version of tornado used.

    ERROR: Error in connection callback  
    ERROR: Traceback (most recent call last):  
    ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/autossl.py", line 187, in_handle_connection  
    ERROR:     connection, io_loop=self.io_loop,  
    ERROR: AttributeError: 'AutoHTTPSServer' object has no attribute 'io_loop'  
    ERROR: Error in connection callback  
    ERROR: Traceback (most recent call last):  
    ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/autossl.py", line 187, in _handle_connection  
    ERROR:     connection, io_loop=self.io_loop,  
    ERROR: AttributeError: 'AutoHTTPSServer' object has no attribute 'io_loop'

Is there any reason for this issue having been closed ?

**Comment by julmon** [comment]
Hello,

The main reason is Tornado 5 does not support old Python 2.7 (< 2.7.9): http://www.tornadoweb.org/en/stable/releases/v5.0.0.html#backwards-compatibility-notes

Unfortunately, Python version shipped with RHEL/CentOS 7 is 2.7.5

Regards,

**Comment by daftaupe** [comment]
@julmon, I understand it's not an option to have tornado 5 support in the master branch.
What about having it on a separate branch so Temboard would be usable on distributions shipping tornado in version 5+ ?

Regards,

**Comment by daftaupe** [comment]
Thanks for pointing me to this, however virtualenv might work for myself, but I wanted to write a package for ArchLinux AUR, and I doubt that this could be a solution.

**Comment by bersace** [comment]
I'm investigating this.

RHEL 7, our target plateform, have Python 2.7.5. Tornado 5 requires new SSL module available in 2.7.9.

There is a backport of this SSL module we may use Python 2.7.5 is used *and* Tornado is 5.0+. https://github.com/alekstorm/backports.ssl
