### ISSUE TITLE
UnicodeDecodeError with SQLAlchemy error

### ISSUE THREAD

**Issue by bersace** [dalibo/temboard#338]
Extracted from #333 

```
temboard -c temboard.dev.conf --debug       
 INFO: Starting main process.
 INFO: Loading plugin 'dashboard'.
 INFO: Loading plugin 'dashboard' configuration.
 INFO: Loading plugin 'pgconf'.
 INFO: Loading plugin 'pgconf' configuration.
 INFO: Loading plugin 'activity'.
 INFO: Loading plugin 'activity' configuration.
 INFO: Loading plugin 'monitoring'.
 INFO: Loading plugin 'monitoring' configuration.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/Z50PPETI/gitHome/temboard/env/lib/python2.7/site-packages/temboardui/logger.py", line 17, in format
    lines = logging.StreamHandler.format(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/Z50PPETI/gitHome/temboard/env/lib/python2.7/site-packages/temboardui/logger.py", line 37, in format
    s = super(MultilineFormatter, self).format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "/home/Z50PPETI/gitHome/temboard/env/lib/python2.7/site-packages/sqlalchemy/exc.py", line 319, in __str__
    details = [self._message()]
  File "/home/Z50PPETI/gitHome/temboard/env/lib/python2.7/site-packages/sqlalchemy/exc.py", line 43, in _message
    return compat.text_type(self.args[0])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 59: ordinal not in range(128)
Logged from file utils.py, line 16
 INFO: Retrying in 0s.
```

This may be an error with special caracters in postgres message in e.g. locale fr_FR.

**Comment by mrechte** [comment]
Hi,
Having the same problem. I tried to export LANG=en_US.UTF-8 before starting temboard, but it does not change:

```
INFO: Loading plugin 'monitoring' configuration.
 INFO: Starting TaskManager
 INFO: Starting temboardui on https://0.0.0.0:80
ERROR: Could not aggregate montitoring data
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/home/temboard/SERVER/lib/python2.7/site-packages/temboardui/logger.py", line 17, in format
    lines = logging.StreamHandler.format(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/home/temboard/SERVER/lib/python2.7/site-packages/temboardui/logger.py", line 37, in format
    s = super(MultilineFormatter, self).format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
  File "/home/temboard/SERVER/lib/python2.7/site-packages/sqlalchemy/exc.py", line 319, in __str__
    details = [self._message()]
  File "/home/temboard/SERVER/lib/python2.7/site-packages/sqlalchemy/exc.py", line 43, in _message
    return compat.text_type(self.args[0])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 64: ordinal not in range(128)
Logged from file __init__.py, line 93
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/home/temboard/SERVER/lib/python2.7/site-packages/temboardui/logger.py", line 17, in format
    lines = logging.StreamHandler.format(self, record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/home/temboard/SERVER/lib/python2.7/site-packages/temboardui/logger.py", line 37, in format
    s = super(MultilineFormatter, self).format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
  File "/home/temboard/SERVER/lib/python2.7/site-packages/sqlalchemy/exc.py", line 319, in __str__
    details = [self._message()]
  File "/home/temboard/SERVER/lib/python2.7/site-packages/sqlalchemy/exc.py", line 43, in _message
    return compat.text_type(self.args[0])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 64: ordinal not in range(128)
Logged from file taskmanager.py, line 766
ERROR: Could not serialize Task to JSON

```

**Comment by mrechte** [comment]
As far as I am concerned, the problem arises in temboardui/plugins/monitoring/__init__.py, in Python function aggregate_data_worker() @ line 85 while calling:
res = conn.execute("SELECT * FROM aggregate_data()")

Running the query manually gives:

```
> SELECT * FROM aggregate_data();
ERREUR:  erreur de syntaxe sur ou près de « ON »
LINE 1: ..._time(NOW(), '30m') GROUP BY 1,2,3 ORDER BY 1,2,3 ON CONFLIC...
                                                             ^
QUERY:  INSERT INTO metric_sessions_30m_current SELECT truncate_time(datetime, '30m') AS datetime, instance_id, dbname, ROW(NULL, AVG((r).active), AVG((r).waiting), AVG((r).idle), AVG((r).idle_in_xact), AVG((r).idle_in_xact_aborted), AVG((r).fastpath), AVG((r).disabled), AVG((r).no_priv))::metric_sessions_record, COUNT(*) AS w FROM expand_data('metric_sessions', tstzrange((SELECT MAX(datetime) FROM metric_sessions_30m_current), NOW())) AS (datetime timestamp with time zone, instance_id integer, dbname text, r metric_sessions_record) WHERE truncate_time(datetime, '30m') < truncate_time(NOW(), '30m') GROUP BY 1,2,3 ORDER BY 1,2,3 ON CONFLICT (datetime, instance_id, dbname) DO UPDATE SET w = EXCLUDED.w, record = EXCLUDED.record WHERE metric_sessions_30m_current.w < EXCLUDED.w;
CONTEXT:  fonction PL/pgsql aggregate_data(), ligne 18 à instruction EXECUTE

```

One can see that the original error cause is the error message itself which contains a 'à' despite having set LANG variable to en_US.UTF-8.

However there is still a problem in the SQL function.

**Comment by mrechte** [comment]
Note that temboard repository is hosted on a PostgreSQL 9.4.3 instance.

**Comment by bersace** [comment]
Merci @mrechte  !

> I tried to export LANG=en_US.UTF-8 before starting temboard,

You should change Postgres locale, not temboard locale. Can you confirm that postgres is running in fr_FR.UTF-8 ?

**Comment by mrechte** [comment]
And PG 9.4 does not support "ON CONFLICT" clause...

**Comment by mrechte** [comment]
Yep:
```
> show lc_messages;
 lc_messages 
-------------
 fr_FR.UTF-8
(1 row)
```

**Comment by bersace** [comment]
Closing stale issue. Please reopen if updates !
