### ISSUE TITLE
docker image: "this is a bug!"

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard#413]
To test Temboard, I've just downloaded docker-compose.yml, installed docker-compose and run it. 
It says to report the bug, hence this issue:
```
$ docker-compose up      
Starting temboarddocker_repository_1 ... 
Starting temboarddocker_repository_1 ... done
Starting temboarddocker_agent_1 ... 
Starting temboarddocker_agent_1 ... done
Attaching to temboarddocker_repository_1, temboarddocker_agent_1
repository_1  | LOG:  database system was shut down at 2018-10-05 05:57:38 UTC
repository_1  | LOG:  MultiXact member wraparound protections are now enabled
agent_1       | + trap catchall INT EXIT TERM
repository_1  | LOG:  autovacuum launcher started
repository_1  | LOG:  database system is ready to accept connections
agent_1       | + '[' 0 = 0 ']'
agent_1       | ++ stat -c %g /var/run/docker.sock
agent_1       | + groupmod -g 999 docker
agent_1       | ++ stat -c %u /var/lib/postgresql/data
agent_1       | + usermod -u 999 postgres
agent_1       | usermod: no changes
agent_1       | ++ stat -c %G /var/lib/postgresql/data
agent_1       | + group=postgres
agent_1       | + '[' postgres = UNKNOWN ']'
agent_1       | + adduser postgres postgres
agent_1       | The user `postgres' is already a member of `postgres'.
agent_1       | + chown -R postgres: /var/lib/postgresql /etc/temboard-agent /var/lib/temboard-agent
agent_1       | + exec sudo -u postgres /usr/local/bin/docker-entrypoint.sh temboard-agent
agent_1       | + trap catchall INT EXIT TERM
agent_1       | + '[' 999 = 0 ']'
agent_1       | + command=temboard-agent
agent_1       | + export PGHOST=repository.fqdn
agent_1       | + PGHOST=repository.fqdn
agent_1       | + export PGPORT=5432
agent_1       | + PGPORT=5432
agent_1       | + export PGUSER=postgres
agent_1       | + PGUSER=postgres
agent_1       | + PGPASSWORD=
agent_1       | + export PGDATABASE=postgres
agent_1       | + PGDATABASE=postgres
agent_1       | + TEMBOARD_UI_URL=https://172.17.0.1:8888/
agent_1       | + export TEMBOARD_UI_USER=admin
agent_1       | + TEMBOARD_UI_USER=admin
agent_1       | + export TEMBOARD_UI_PASSWORD=admin
agent_1       | + TEMBOARD_UI_PASSWORD=admin
agent_1       | ++ docker inspect --format '{{ index .Config.Labels "com.docker.compose.project"}}' d149c5ee8ca9
agent_1       | + COMPOSE_PROJECT=temboarddocker
agent_1       | + links=($(docker inspect --format '{{ $net := index .NetworkSettings.Networks "'"${COMPOSE_PROJECT}_default"'" }}{{range $net.Links }}{{.}} {{end}}' $HOSTNAME))
agent_1       | ++ docker inspect --format '{{ $net := index .NetworkSettings.Networks "temboarddocker_default" }}{{range $net.Links }}{{.}} {{end}}' d149c5ee8ca9
agent_1       | + links=(${links[@]%%:${TEMBOARD_HOSTNAME}})
agent_1       | + PGCONTAINER=temboarddocker_repository_1
agent_1       | ++ docker inspect --format '{{ index .Config.Labels "com.docker.compose.service"}}' d149c5ee8ca9
agent_1       | + COMPOSE_SERVICE=agent
agent_1       | + echo 'Managing PostgreSQL container temboarddocker_repository_1.'
agent_1       | Managing PostgreSQL container temboarddocker_repository_1.
agent_1       | + echo 'Generating temboard-agent.conf'
agent_1       | Generating temboard-agent.conf
agent_1       | + mkdir -p /etc/temboard-agent/temboard-agent.conf.d
agent_1       | + cat
agent_1       | + cat
agent_1       | + cat
agent_1       | + touch /etc/temboard-agent/users
agent_1       | + chmod 0600 /etc/temboard-agent/users
agent_1       | + for entry in ${TEMBOARD_USERS_LIST-alice:alice bob:bob}
agent_1       | Adding user alice.
agent_1       | + echo 'Adding user alice.'
agent_1       | + sed -i /alice/d /etc/temboard-agent/users
agent_1       | + temboard-agent-password alice:alice
agent_1       | Adding user bob.
agent_1       | + for entry in ${TEMBOARD_USERS_LIST-alice:alice bob:bob}
agent_1       | + echo 'Adding user bob.'
agent_1       | + sed -i /bob/d /etc/temboard-agent/users
agent_1       | + temboard-agent-password bob:bob
agent_1       | + wait-for-it repository.fqdn:5432
agent_1       | wait-for-it: waiting 15 seconds for repository.fqdn:5432
repository_1  | LOG:  incomplete startup packet
agent_1       | wait-for-it: repository.fqdn:5432 is available after 0 seconds
agent_1       | + '[' -z '' -a -n admin ']'
agent_1       | + set -x
agent_1       | + register
agent_1       | + exec temboard-agent
agent_1       | + set -x
agent_1       | + hostportpath=172.17.0.1:8888/
agent_1       | + hostport=172.17.0.1:8888
agent_1       | + wait-for-it localhost:2345 -t 60
agent_1       | wait-for-it: waiting 60 seconds for localhost:2345
agent_1       |  INFO: Found plugin activity = temboardagent.plugins.activity:ActivityPlugin.
agent_1       |  INFO: Found plugin administration = temboardagent.plugins.administration:AdministrationPlugin.
agent_1       |  INFO: Found plugin dashboard = temboardagent.plugins.dashboard:DashboardPlugin.
agent_1       |  INFO: Found plugin monitoring = temboardagent.plugins.monitoring:MonitoringPlugin.
agent_1       |  INFO: Found plugin pgconf = temboardagent.plugins.pgconf:PgConfPlugin.
agent_1       |  INFO: Loading plugin dashboard.
repository_1  | FATAL:  role "postgres" does not exist
agent_1       | ERROR: Unhandled error:
agent_1       | ERROR: Traceback (most recent call last):
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 254, in entrypoint
agent_1       | ERROR:     retcode = self.main(argv, environ)
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/scripts/agent.py", line 203, in main
agent_1       | ERROR:     self.bootstrap(args=args, environ=environ)
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 99, in bootstrap
agent_1       | ERROR:     self.apply_config()
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/cli.py", line 67, in apply_config
agent_1       | ERROR:     return super(Application, self).apply_config()
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 151, in apply_config
agent_1       | ERROR:     self.update_plugins(old_plugins=old_plugins)
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/toolkit/app.py", line 218, in update_plugins
agent_1       | ERROR:     self.plugins[name].load()
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/plugins/dashboard/__init__.py", line 146, in load
agent_1       | ERROR:     pg_version = self.app.postgres.fetch_version()
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/postgres.py", line 54, in fetch_version
agent_1       | ERROR:     with self.connect() as conn:
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/postgres.py", line 23, in __enter__
agent_1       | ERROR:     self.conn.connect()
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/spc.py", line 847, in connect
agent_1       | ERROR:     self._check_message_error(message)
agent_1       | ERROR:   File "/usr/local/lib/python3.6/site-packages/temboardagent/spc.py", line 697, in _check_message_error
agent_1       | ERROR:     err_split = err_string.split('\x00')
agent_1       | ERROR: TypeError: a bytes-like object is required, not 'str'
agent_1       | ERROR: temboardagent version is 2.0.
agent_1       | ERROR: This is a bug!
agent_1       | ERROR: Please report traceback to https://github.com/dalibo/temboard-agent! Thanks!
temboarddocker_agent_1 exited with code 1
```

Config : Ubuntu 18.04
```
$ apt-cache policy docker docker-compose
docker:
  Installé : 1.5-1build1
  Candidat : 1.5-1build1
 Table de version :
     1.5-1+b1 1
          1 http://deb.debian.org/debian stretch/main amd64 Packages
 *** 1.5-1build1 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
docker-compose:
  Installé : 1.17.1-2
  Candidat : 1.17.1-2
 Table de version :
 *** 1.17.1-2 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://fr.archive.ubuntu.com/ubuntu bionic/universe i386 Packages
        100 /var/lib/dpkg/status
     1.8.0-2 1
          1 http://deb.debian.org/debian stretch/main amd64 Packages
          1 http://deb.debian.org/debian stretch/main i386 Packages
```

**Comment by pgiraud** [comment]
The `docker-compose.yml` file you downloaded is not the one suggested in https://temboard.readthedocs.io/en/latest/QUICKSTART/.
