### ISSUE TITLE
Load Charts on Homepage - When Are They Updated?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#416]
I had to shutdown the temboard agent and PostgreSQL cluster on a host for hardware maintenance, downtime was around 90 minutes or so. When the host came back up and the cluster and temboard-agent were restarted the TPS and Load/Avg charts on the GUI homepage were blank for that instance. I've waited over an hour and they still aren't populated.

How long does the instance and agent have to be running before those charts get some data?

**Comment by pgiraud** [comment]
The charts in the dashboard should be updated immediately. You shouldn't have to wait.
At the begining you should be able to see something looking like this (not complete chart): 
![capture du 2018-10-08 13-59-41](https://user-images.githubusercontent.com/319774/46607768-7cdc8500-cb02-11e8-9cfc-eac58746800e.png)

Then it should be appended with new data every 2 seconds.

Is the gauge for CPU updating?
Do you get any javascript errors?

**Comment by dgiffin** [comment]
The CPU guage for the instance is updating fine, but it looks like I have a problem:

temboard-agent.log:

2018-10-08 07:02:09,196 temboardagent[22673]: [probes] INFO: Loaded probe: memory
2018-10-08 07:02:09,723 temboardagent[22675]: [monitoring] ERROR: Failed to send data to collector: max_connections
2018-10-08 07:02:09,723 temboardagent[22675]: [monitoring] ERROR: You should find details in temBoard UI logs.
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR: Failed to send data to collector.
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR: Traceback (most recent call last):
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/taskmanager.py", line 815, in exec_worker
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 102, in wrapper
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 227, in monitoring_sender_worker
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR:     raise Exception("Failed to send data to collector.")
2018-10-08 07:02:09,724 temboardagent[22675]: [taskmanager] ERROR: Exception: Failed to send data to collector.


temboard.log:

2018-10-08 07:03:10,123 temboard-agent[15792]: [temboardui] ERROR: 'max_connections'
2018-10-08 07:03:10,123 temboard-agent[15792]: [temboardui] ERROR: Traceback (most recent call last):
2018-10-08 07:03:10,123 temboard-agent[15792]: [temboardui] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 105, in push_data
2018-10-08 07:03:10,123 temboard-agent[15792]: [temboardui] ERROR:     data['instances'][0]['max_connections']
2018-10-08 07:03:10,123 temboard-agent[15792]: [temboardui] ERROR: KeyError: 'max_connections'
2018-10-08 07:03:10,124 temboard-agent[15792]: [temboardui] INFO: 500 POST /supervision/collector (10.244.5.141) 21.94ms
^C

**Comment by dgiffin** [comment]
I'm sure nothing changed...

**Comment by dgiffin** [comment]
The problem only seems to be on a remote instances, the agent running on the host where the temboard repository database runs is showing no errors.

**Comment by pgiraud** [comment]
In your browser developper tools you should be able to see several calls to a "dashboard" service (network tab). Can you please copy the response and paste it here?
This should like this:
```json
{"pg_uptime": "00:36:36", "active_backends": {"nb": 1, "time": 1539001700.33024}, "databases": {"total_rollback": 151, "total_size": "18 MB", "timestamp": 1539001700.4452925, "databases": 2, "total_commit": 13934, "time": "12:28"}, "linux_distribution": "debian 9.5", "notifications": [{"date": "2018-10-08T11:59:31", "username": "alice", "message": "Login"}, {"date": "2018-10-08T11:56:12", "username": "alice", "message": "Login"}, {"date": "2018-10-08T11:55:22", "username": "alice", "message": "Login"}, {"date": "2018-10-08T11:52:26", "username": "alice", "message": "Login"}], "pg_version": "PostgreSQL 9.6.9 on x86_64-pc-linux-gnu (Debian 9.6.9-2.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit", "hostname": "repository.fqdn", "pg_data": "/var/lib/postgresql/data", "os_version": "4.15.0-34-generic", "loadaverage": 2.52, "hitratio": 99.0, "cpu_models": {"Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz": 4}, "memory": {"active": 38.8, "cached": 28.9, "total": 16306184, "free": 32.3}, "pg_port": "5432", "n_cpu": 4, "cpu": {"iowait": 2.7, "idle": 73.0, "steal": 0.0, "user": 18.9, "system": 5.4}, "buffers": {"nb": 820, "time": 1539001700.315011}, "max_connections": 100}
```

**Comment by dgiffin** [comment]
Sorry, I can't see anything called "dashboard".

<img width="1280" alt="temboard-1" src="https://user-images.githubusercontent.com/4103061/46609347-1c941600-caf7-11e8-8927-061c9f2cf22e.png">

**Comment by pgiraud** [comment]
My bad, I didn't pay enough attention. I thought you were talking about the dashboard page hence the confusion.
The charts on the homepage are updated every minute. They behave just like the charts in the monitoring tab.

Are both UI and agents running the same major version?
What version of the agent is running on temp01? and on temp02?

**Comment by dgiffin** [comment]
They are all running the same version:

[dgiffin@devpg-temp01 ~]$ rpm -q temboard
temboard-2.0-1.el7.noarch

[dgiffin@devpg-temp01 ~]$ rpm -q temboard-agent
temboard-agent-2.0-1.el7.noarch

[dgiffin@devpg-temp02 ~]$ rpm -q temboard-agent
temboard-agent-2.0-1.el7.noarch

**Comment by pgiraud** [comment]
Did the "max_connections" happen several times or only once?
Are you able to see any data in the chart for loadaverage in the monitoring tab?

**Comment by dgiffin** [comment]
The max_connections error occurs in the temboard-agent log every 60 seconds.
In the temboard gui I can't see data in the Loadaverage and TPS chart in the Monitoring window for devpg-temp02.

**Comment by dgiffin** [comment]
Sorry, I meant the max_connections error appears every 60 seconds in the TEMBOARD log.

**Comment by pgiraud** [comment]
Could you please paste here the content of the `metrics.q` file for one of the failing agent? It should be located in `/var/lib/temboard-agent` if you didn't change the configuration.

**Comment by dgiffin** [comment]
[metrics.q.gz](https://github.com/dalibo/temboard/files/2459307/metrics.q.gz)

**Comment by pgiraud** [comment]
OK, this makes sense now. For an unknown reason, the metrics collected before `2018-10-08 09:32:30 +0000` don't contain the appropriate data. I will have to dig a bit more.

For now, what you can do is either:
 - remove the `metrics.q`. The agent will create a new one next time probes are collected,
 - remove manually the lines not containing `max_connections` (the following command should do the job `sed -i '/max_connections/!d' metrics.q`)

The first solution is a lot easier but you will loose the data collected yesterday.

**Comment by dgiffin** [comment]
I stopped the temboard-agent, removed the metrics.q file and restarted the agent. I am no longer seeing the max_connections error in the temboard log BUT I am now seeing a new but similar error:

2018-10-09 03:47:32,606 temboard-agent[20584]: [monitoring.handlers.monitoring] ERROR: 'wal_files'
2018-10-09 03:47:32,606 temboard-agent[20584]: [monitoring.handlers.monitoring] ERROR: Traceback (most recent call last):
2018-10-09 03:47:32,606 temboard-agent[20584]: [monitoring.handlers.monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 119, in push_data
2018-10-09 03:47:32,606 temboard-agent[20584]: [monitoring.handlers.monitoring] ERROR:     v = spec.get('preprocess')(data['data'])
2018-10-09 03:47:32,606 temboard-agent[20584]: [monitoring.handlers.monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/alerting.py", line 93, in wal_files
2018-10-09 03:47:32,606 temboard-agent[20584]: [monitoring.handlers.monitoring] ERROR:     return int(data['wal_files'][0]['total'])
2018-10-09 03:47:32,606 temboard-agent[20584]: [monitoring.handlers.monitoring] ERROR: KeyError: 'wal_files'
2018-10-09 03:47:32,607 temboard-agent[20584]: [monitoring.handlers.monitoring] WARNING: Not able to preprocess 'wal_files_total' data.

**Comment by dgiffin** [comment]
Ah, my bad, looks like I was bit heavy handed deleting the metrics.q file :-( I've deleted and re-added the PostgreSQL instance and am no longer getting the wal_files errors.

**Comment by dgiffin** [comment]
Ah, my bad, looks like I was bit heavy handed deleting the metrics.q file :-( I've deleted and re-added the PostgreSQL instance and am no longer getting the wal_files errors.

**Comment by dgiffin** [comment]
If I look into the temboard-agent.log file for the primary I can see:
temboardagent[7614]: [probes] INFO: Loaded probe: wal_files

I CANNOT see a similar entry in the log file for the agent on the standby host - this is what I would expect - so not sure the wal_files data seems to be being sent.

**Comment by pgiraud** [comment]
With the latest code, the charts now show more relevant information. The range of data displayed really correspond to the last 5 min (dashboard) or last 1 hour (monitoring).
temBoard now detects when the monitored instance is not available (stopped, unreachable, etc...) and stores information about that. In the charts the line may be discontinuated.
See https://github.com/dalibo/temboard/pull/415
