### ISSUE TITLE
Monitoring not working after PostgreSQL crash and page status white

### ISSUE THREAD

**Issue by ezwww** [dalibo/temboard#476]
Hi,

one postgresql server has crashed / freeze at 7h am this morning. This server hosting temboard and one temboard-agent.

After restart postgresql/temboard the graph for monitoring don't show new value and the status page is blank.

See below the error in log file 

2018-11-29 19:24:51,939 temboard-agent[2503]: [temboardui] ERROR: object of type 'NoneType' has no len()
2018-11-29 19:24:51,939 temboard-agent[2503]: [temboardui] ERROR: Traceback (most recent call last):
2018-11-29 19:24:51,939 temboard-agent[2503]: [temboardui] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 90, in push_data
2018-11-29 19:24:51,939 temboard-agent[2503]: [temboardui] ERROR:     data['hostinfo']['hostname'], data['instances'][0]['port'])
2018-11-29 19:24:51,939 temboard-agent[2503]: [temboardui] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/tools.py", line 145, in insert_metrics
2018-11-29 19:24:51,939 temboard-agent[2503]: [temboardui] ERROR:     if len(agent_data[metric]) == 0:
2018-11-29 19:24:51,939 temboard-agent[2503]: [temboardui] ERROR: TypeError: object of type 'NoneType' has no len()
2018-11-29 19:24:51,941 temboard-agent[2503]: [temboardui] INFO: 500 POST /monitoring/collector (xxx.xxx.xxx.xxx) 23.61ms

For the status page i don't have error in log file, only this entry

2018-11-29 19:18:50,526 temboard-agent[2503]: [temboardui] INFO: 200 GET /server/xxxxxx.xxxxx.xx/2345/alerting/checks.json (xxx.xxx.xxx.xxx) 22.84ms

I have an another postgresql server with temboard-agent and the graphs are OK in temboard for this server and good value in the status page.

Thanks for your help

![temboard_monitoring_page](https://user-images.githubusercontent.com/18184902/49243170-f4e17000-f40c-11e8-92e7-3e083067838e.png)

Another temboard-agent server with no problem

![temboard_secondagent_ok](https://user-images.githubusercontent.com/18184902/49243450-b0a29f80-f40d-11e8-97fd-94c18ce12f9d.png)

# SET search_path TO monitoring; SELECT * FROM aggregate_data();

SET
NOTICE:  WITH expand AS (SELECT datetime, instance_id, dbname, record FROM metric_sessions_current WHERE datetime <@ '["2018-11-29 12:00:00+01","2018-11-29 19:39:34.886283+01")'::TSTZRANGE UNION SELECT (hist_query.record).datetime, instance_id, dbname, hist_query.record FROM (SELECT instance_id, dbname, unnest(records)::metric_sessions_record AS record FROM metric_sessions_history WHERE history_range && '["2018-11-29 12:00:00+01","2018-11-29 19:39:34.886283+01")'::TSTZRANGE) AS hist_query) SELECT * FROM expand WHERE datetime <@ '["2018-11-29 12:00:00+01","2018-11-29 19:39:34.886283+01")'::TSTZRANGE ORDER BY datetime ASC LIMIT 100000

....

NOTICE:  WITH expand AS (SELECT datetime, instance_id, dbname, record FROM metric_vacuum_analyze_current WHERE datetime <@ '(,"2018-11-29 19:39:34.886283+01")'::TSTZRANGE UNION SELECT (hist_query.record).datetime, instance_id, dbname, hist_query.record FROM (SELECT instance_id, dbname, unnest(records)::metric_vacuum_analyze_record AS record FROM metric_vacuum_analyze_history WHERE history_range && '(,"2018-11-29 19:39:34.886283+01")'::TSTZRANGE) AS hist_query) SELECT * FROM expand WHERE datetime <@ '(,"2018-11-29 19:39:34.886283+01")'::TSTZRANGE ORDER BY datetime ASC LIMIT 100000
NOTICE:  WITH expand AS (SELECT datetime, instance_id, dbname, record FROM metric_vacuum_analyze_current WHERE datetime <@ '(,"2018-11-29 19:39:34.886283+01")'::TSTZRANGE UNION SELECT (hist_query.record).datetime, instance_id, dbname, hist_query.record FROM (SELECT instance_id, dbname, unnest(records)::metric_vacuum_analyze_record AS record FROM metric_vacuum_analyze_history WHERE history_range && '(,"2018-11-29 19:39:34.886283+01")'::TSTZRANGE) AS hist_query) SELECT * FROM expand WHERE datetime <@ '(,"2018-11-29 19:39:34.886283+01")'::TSTZRANGE ORDER BY datetime ASC LIMIT 100000
                  tblname                  | nb_rows 
-------------------------------------------+---------
 metric_sessions_30m_current               |       0
 metric_sessions_6h_current                |       0
 metric_xacts_30m_current                  |       0
 metric_xacts_6h_current                   |       0
 metric_locks_30m_current                  |       0
 metric_locks_6h_current                   |       0
 metric_blocks_30m_current                 |       0
 metric_blocks_6h_current                  |       0
 metric_bgwriter_30m_current               |       0
 metric_bgwriter_6h_current                |       0
 metric_db_size_30m_current                |       0
 metric_db_size_6h_current                 |       0
 metric_tblspc_size_30m_current            |       0
 metric_tblspc_size_6h_current             |       0
 metric_filesystems_size_30m_current       |       0
 metric_filesystems_size_6h_current        |       0
 metric_temp_files_size_tblspc_30m_current |       0
 metric_temp_files_size_tblspc_6h_current  |       0
 metric_temp_files_size_db_30m_current     |       0
 metric_temp_files_size_db_6h_current      |       0
 metric_wal_files_30m_current              |       0
 metric_wal_files_6h_current               |       0
 metric_cpu_30m_current                    |       0
 metric_cpu_6h_current                     |       0
 metric_process_30m_current                |       0
 metric_process_6h_current                 |       0
 metric_memory_30m_current                 |       0
 metric_memory_6h_current                  |       0
 metric_loadavg_30m_current                |       0
 metric_loadavg_6h_current                 |       0
 metric_vacuum_analyze_30m_current         |       0
 metric_vacuum_analyze_6h_current          |       0
(32 rows)

**Comment by ezwww** [comment]
thanks, this fix correct my problem.
