### ISSUE TITLE
How to Identify Problem Agent?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#534]
I can see errors in the temboard logfile:

2019-01-07 10:40:03,015 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR: 'wal_files'
2019-01-07 10:40:03,015 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR: Traceback (most recent call last):
2019-01-07 10:40:03,015 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 119, in push_data
2019-01-07 10:40:03,015 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:     v = spec.get('preprocess')(data['data'])
2019-01-07 10:40:03,015 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/alerting.py", line 89, in archive_ready
2019-01-07 10:40:03,015 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:     return int(data['wal_files'][0]['archive_ready'])
2019-01-07 10:40:03,015 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR: KeyError: 'wal_files'
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] WARNING: Not able to preprocess 'wal_files_archive' data.
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR: 'wal_files'
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR: Traceback (most recent call last):
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 119, in push_data
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:     v = spec.get('preprocess')(data['data'])
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/alerting.py", line 93, in wal_files
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR:     return int(data['wal_files'][0]['total'])
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] ERROR: KeyError: 'wal_files'
2019-01-07 10:40:03,016 temboard-agent[7362]: [monitoring.handlers.monitoring] WARNING: Not able to preprocess 'wal_files_total' data.

How can I identify which agent is causing these?

**Comment by julmon** [comment]
Hello,

This is coming from an agent monitoring a standby Postgres instance. WAL probes a not enabled on standby. This is not blocking, but we're going to fix it.
Please keep this ticket open until we provide a fix.

Thanks,

**Comment by julmon** [comment]
#545 fixed it
