### ISSUE TITLE
[temboard-agent] Error using temboard-agent-register

### ISSUE THREAD

**Issue by Rodac** [dalibo/temboard#590]
Hi,

Following the installation guide (https://temboard-agent.readthedocs.io/en/v2/installation.html#)  I hang at the registration step using `temboard-agent-register`

I have this error : 
**CRITI: <urlopen error [Errno 111] Connection refused>**

The environment : 
OS : CentOS 7.6.1810
Python : 2.7.5
Temboard-agent : 2.3
Temboard : 2.3

Installation made via RPM.

temboard-agent logs :
```shell
[taskmanager] ERROR: <urlopen error [Errno 111] Connection refused>
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR: Traceback (most recent call last):
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/taskmanager.py", line 815, in exec_worker
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 102, in wrapper
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 208, in monitoring_sender_worker
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     msg.content
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/output.py", line 34, in send_output
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     data=json.loads(j_output)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpsclient.py", line 100, in https_request
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     handle = url_opener.open(request)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 431, in open
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     response = self._open(req, data)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     '_open', req)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     result = func(*args)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpsclient.py", line 64, in https_open
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     return self.do_open(self.specialized_conn_class, req)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR:     raise URLError(err)
2019-03-18 13:20:58,437 temboardagent[40627]: [taskmanager] ERROR: URLError: <urlopen error [Errno 111] Connection refused>
`
 
Any idea of what's wrong ?

**Comment by julmon** [comment]
Hi,

Could you check that `collector_url` parameter is well configured in `temboard-agent.conf` file ?

**Comment by Rodac** [comment]
The problem seems to occurs when using the auto-configure script with an instance name containing an hyphen ( - )  (example : REC-BDD1)

The path was splitted aroung the hyphen in the service created.
This is a problem using %I in the generic service (temboard-agent@.service).
 

Nos, when using the _/etc/temboard-agent/temboard-agent.conf,_ with the correct collector URL I have this bug : 

```shell 
2019-03-21 12:16:21,641 temboardagent[54905]: [app] WARNING: setuptools is too old. Can't reload installed packages.
2019-03-21 12:16:21,641 temboardagent[54905]: [app] WARNING: Restart if new plugins can't be found.
2019-03-21 12:16:21,655 temboardagent[54905]: [app] INFO: Found plugin monitoring = temboardagent.plugins.monitoring:MonitoringPlugin.
2019-03-21 12:16:21,667 temboardagent[54905]: [app] INFO: Found plugin dashboard = temboardagent.plugins.dashboard:DashboardPlugin.
2019-03-21 12:16:21,669 temboardagent[54905]: [app] INFO: Found plugin pgconf = temboardagent.plugins.pgconf:PgConfPlugin.
2019-03-21 12:16:21,674 temboardagent[54905]: [app] INFO: Found plugin administration = temboardagent.plugins.administration:AdministrationPlugin.
2019-03-21 12:16:21,675 temboardagent[54905]: [app] INFO: Found plugin activity = temboardagent.plugins.activity:ActivityPlugin.
2019-03-21 12:16:21,679 temboardagent[54905]: [app] INFO: Loading plugin administration.
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR: Unhandled error:
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR: Traceback (most recent call last):
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 254, in entrypoint
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     retcode = self.main(argv, environ)
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 203, in main
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     self.bootstrap(args=args, environ=environ)
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 99, in bootstrap
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     self.apply_config()
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/cli.py", line 67, in apply_config
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     return super(Application, self).apply_config()
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 151, in apply_config
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     self.update_plugins(old_plugins=old_plugins)
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 218, in update_plugins
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     self.plugins[name].load()
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/administration/__init__.py", line 104, in load
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     pg_version = self.app.postgres.fetch_version()
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/postgres.py", line 54, in fetch_version
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     with self.connect() as conn:
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/postgres.py", line 23, in __enter__
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     self.conn.connect()
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 827, in connect
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR:     self._password.encode()
2019-03-21 12:16:21,687 temboardagent[54905]: [app] ERROR: AttributeError: 'NoneType' object has no attribute 'encode'
2019-03-21 12:16:21,690 temboardagent[54905]: [app] ERROR: temboardagent version is 2.3.
2019-03-21 12:16:21,690 temboardagent[54905]: [app] ERROR: This is a bug!
2019-03-21 12:16:21,690 temboardagent[54905]: [app] ERROR: Please report traceback to https://github.com/dalibo/temboard-agent! Thanks!
```

**Comment by Rodac** [comment]
I made a mistake configuring the [postgresql] part of the config file.

Everything is now working.
