### ISSUE TITLE
Compatibility python3

### ISSUE THREAD

**Issue by XpzJulien86** [dalibo/temboard#605]
Hello,
Temboard can work with python3?
If not how launch it with py2?

I have this error : 

`Traceback (most recent call last):
  File "/usr/local/bin/temboard", line 11, in <module>
    load_entry_point('temboard==3.0', 'console_scripts', 'temboard')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/temboardui/__main__.py", line 24, in <module>
    from .web import Error404Handler, app
  File "/usr/local/lib/python3.6/dist-packages/temboardui/web.py", line 7, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

`

**Comment by XpzJulien86** [comment]
i found my error, i remove temboard and reinstall with pip2
