### ISSUE TITLE
Failed authentication on the configuration tab

### ISSUE THREAD

**Issue by dagravito** [dalibo/temboard#628]
Hello
I've created the user on the agent like it is in the documentation and I can't connect on the configuration webpage... I still have authentication failed in the log :

```
2019-04-29 11:48:21,839 temboardagent[18169]: [api] INFO: Authenticating user: temboard
2019-04-29 11:48:21,841 temboardagent[18169]: [api] INFO: Authentication failed.
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR: {'error': 'Invalid username/password.'}
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR: Traceback (most recent call last):
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 109, in response
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR:     (code, message) = self.route_request()
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/httpd.py", line 260, in route_request
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR:     return (200, func(http_context, self.app, self.sessions))
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/api.py", line 61, in login
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR:     raise e
2019-04-29 11:48:21,841 temboardagent[18169]: [httpd] ERROR: HTTPError: Invalid username/password.
2019-04-29 11:48:21,842 temboardagent[18169]: [httpd] ERROR: {'error': 'Invalid username/password.'}
2019-04-29 11:48:21,849 temboardagent[18169]: [httpd] INFO: client: 10.20.106.106 request: "POST /login?key=5c9c75d7b0cec37b35a52bc4c60b4c2f HTTP/1.1" 404 -
```

Do I miss something ?
Thanks,
Damien.

**Comment by julmon** [comment]
Hello,

It seems user/password couple created on the agent and used on the agent login page do not match.

You could test this from command line with curl like this (from the host running the agent):
```console
$ curl -s -k -X POST --data '{"username": "temboard", "password": "<password>"}' https://localhost:2345/login
```

**Comment by dagravito** [comment]
Hello Julien
strange I have created it using (with correct conf file) :
sudo -u postgres temboard-agent-adduser -c /etc/temboard-agent/11/main/temboard-agent.conf

But I have the invalid username/password :

```
curl -s -k -X POST --data '{"username": "temboard", "password": "temboard"}' https://localhost:2345/login
{"error": "Invalid username/password."}
```

**Comment by dagravito** [comment]
OK I have it now.
I used the temboard-agent.conf.d/auto.conf file instead of temboard-agent.conf...
