### ISSUE TITLE
temboard-agent error in logs

### ISSUE THREAD

**Issue by Dreych** [dalibo/temboard#651]
Hi! I have a problem with status on temboard server. I see error in temboard-agent. I don't see status. 
![image](https://user-images.githubusercontent.com/46996795/60345016-ac992900-99c0-11e9-816a-246cbd497379.png)

```

июн 28 20:08:58 kry-wms-pg-2-p env[23484]: Failed to send data to collector.
июн 28 20:08:58 kry-wms-pg-2-p env[23484]: Traceback (most recent call last):
июн 28 20:08:58 kry-wms-pg-2-p env[23484]:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 888, in exec_worker
июн 28 20:08:58 kry-wms-pg-2-p env[23484]:     res = getattr(sys.modules[module], function)(*args, **kws)
июн 28 20:08:58 kry-wms-pg-2-p env[23484]:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 1051, in wrapper
июн 28 20:08:58 kry-wms-pg-2-p env[23484]:     return function(app=self.app, *a, **kw)
июн 28 20:08:58 kry-wms-pg-2-p env[23484]:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/plugins/monitoring/__init__.py", line 257, in monitoring_sender_worker
июн 28 20:08:58 kry-wms-pg-2-p env[23484]:     raise Exception("Failed to send data to collector.")
июн 28 20:08:58 kry-wms-pg-2-p env[23484]: Exception: Failed to send data to collector.

```

**Comment by loumour** [comment]
Hello,
I have the same error with temboard-agent version 4.0b1 and I have the following errors in temboard server 4.0b1.
-----------------------------------------------------------------------
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:     expire=0,
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 787, in schedule_task
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:     conn = Client(self.scheduler.address, self.scheduler.authkey)
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:   File "/usr/lib64/python2.7/multiprocessing/connection.py", line 173, in Client
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:     c = SocketClient(address)
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:   File "/usr/lib64/python2.7/multiprocessing/connection.py", line 308, in SocketClient
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:     s.connect(address)
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:   File "/usr/lib64/python2.7/socket.py", line 224, in meth
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR:     return getattr(self._sock,name)(*args)
2019-07-02 11:18:18,482 temboardui[18142]: [web] ERROR: error: [Errno 2] No such file or directory
2019-07-02 11:18:18,483 temboardui[18142]: [web] ERROR: Request failed: 500 [Errno 2] No such file or directory.
2019-07-02 11:18:18,485 temboardui[18142]: [access] ERROR: 500 POST /monitoring/collector 
----------------------------------------------------------------------------


I'm looking forward  to resolve this issue.
Regards

**Comment by loumour** [comment]
Hi, 
this issue has disappeared after restarting temboard UI and his database

**Comment by pgiraud** [comment]
@Dreych This error means that the monitoring plugin on the agent isn't able to send data to the UI. It's either because the UI cannot be reached from the agent (ie. networking issues) or that there's error on the UI itself when it receives the data.

Can you please look at the logs on the UI side to see if there are relevant errors?
Can you also please ensure that everything is correct in the `monitoring` section of the agent configuration file, especially the `collector_url`.

**Comment by madtibo** [comment]
Hello,

I encounter the same kind of error.
I am on debian buster with install using pip.
I have nothing on the status or maintenance window.

In the agent log:
```
2019-11-08 12:17:31,241 temboardagent[9173]: [monitoring] ERROR: Failed to send data to collector: address type of u'/var/lib/temboard/.tm.socket' unrecognized
2019-11-08 12:17:31,241 temboardagent[9173]: [monitoring] ERROR: You should find details in temBoard UI logs.
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR: Failed to send data to collector.
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR: Traceback (most recent call last):
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 888, in exec_worker
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/toolkit/taskmanager.py", line 1051, in wrapper
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardagent/plugins/monitoring/__init__.py", line 257, in monitoring_sender_worker
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR:     raise Exception("Failed to send data to collector.")
2019-11-08 12:17:31,242 temboardagent[9173]: [taskmanager] ERROR: Exception: Failed to send data to collector.
```

In the temboard log:
```
2019-11-08 12:17:31,236 temboardui[29353]: [monitoring] WARNING: Failed to preprocess alerting check 'replication_lag'
2019-11-08 12:17:31,237 temboardui[29353]: [monitoring] WARNING: Failed to preprocess alerting check 'replication_connection'
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR: Unhandled Error:
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR: Traceback (most recent call last):
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/web.py", line 224, in error_middleware
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:     return func(request, *args)
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/web.py", line 379, in json_middleware
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:     return func(request, *args)
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/web.py", line 419, in user_middleware
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:     return func(request, *args)
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 142, in collector
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:     expire=0,
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/toolkit/taskmanager.py", line 787, in schedule_task
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:     conn = Client(self.scheduler.address, self.scheduler.authkey)
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:   File "/usr/lib/python2.7/multiprocessing/connection.py", line 165, in Client
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:     family = family or address_type(address)
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:   File "/usr/lib/python2.7/multiprocessing/connection.py", line 111, in address_type
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR:     raise ValueError('address type of %r unrecognized' % address)
2019-11-08 12:17:31,237 temboardui[29353]: [web] ERROR: ValueError: address type of u'/var/lib/temboard/.tm.socket' unrecognized
2019-11-08 12:17:31,238 temboardui[29353]: [web] ERROR: Request failed: 500 address type of u'/var/lib/temboard/.tm.socket' unrecognized.
2019-11-08 12:17:31,241 temboardui[29353]: [access] ERROR: 500 POST /monitoring/collector (127.0.0.1) 220.84ms
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR: Unhandled Error:
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR: Traceback (most recent call last):
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/web.py", line 224, in error_middleware
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:     return func(request, *args)
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/web.py", line 379, in json_middleware
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:     return func(request, *args)
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/web.py", line 419, in user_middleware
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:     return func(request, *args)
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 112, in collector
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:     check_agent_request(request, hostname, instance)
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/plugins/monitoring/handlers/monitoring.py", line 44, in check_agent_request
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:     key)
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:   File "/usr/local/lib/python2.7/dist-packages/temboardui/plugins/monitoring/tools.py", line 132, in check_agent_key
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR:     "in application.instances table." % hostname)
2019-11-08 12:17:33,127 temboardui[29353]: [web] ERROR: Exception: Can't find the instance "supervision.ws" in application.instances table.
2019-11-08 12:17:33,128 temboardui[29353]: [web] ERROR: Request failed: 500 Can't find the instance "supervision.ws" in application.instances table..
2019-11-08 12:17:33,133 temboardui[29353]: [access] ERROR: 500 POST /monitoring/collector (127.0.0.1) 8.12ms
```

Not sure if the 2 messages are linked 

* `ERROR: Request failed: 500 Can't find the instance "supervision.ws" in application.instances table..`
* `ERROR: Request failed: 500 address type of u'/var/lib/temboard/.tm.socket' unrecognized.`

I have the following lines in the temboard db:

```
temboard=# select  * from application.instances ;
-[ RECORD 1 ]------+-----------------------------------------------------------------------------------------------------------------
agent_address      | supervision.ws
agent_port         | 2345
agent_key          | b9b74481d8149c2c18bb227e773a8879
hostname           | supervision.ws
cpu                | 2
memory_size        | 4138512384
pg_port            | 5432
pg_version         | PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
pg_version_summary | PostgreSQL 12.0
pg_data            | /var/lib/postgresql/12/main
notify             | f
-[ RECORD 2 ]------+-----------------------------------------------------------------------------------------------------------------
agent_address      | supervision.ws
agent_port         | 3345
agent_key          | 4d0441f8d34aea1dffcce1b3978ba9b0
hostname           | supervision.ws
cpu                | 2
memory_size        | 4138512384
pg_port            | 5433
pg_version         | PostgreSQL 11.5 (Debian 11.5-3.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
pg_version_summary | PostgreSQL 11.5
pg_data            | /var/lib/postgresql/11/main
notify             | f
```

My hostname seems to be valid in the agent configuration:
```
dalibo@supervision:~$ hostname --fqdn
supervision.ws

dalibo@supervision:~$ curl -s -k https://localhost:2345/discover | python -m json.tool
{
    "cpu": 2,
    "hostname": "supervision.ws",
    "memory_size": 4138512384,
    "pg_data": "/var/lib/postgresql/12/main",
    "pg_port": "5432",
    "pg_version": "PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit",
    "pg_version_summary": "PostgreSQL 12.0",
    "plugins": [
        "monitoring",
        "dashboard",
        "pgconf",
        "administration",
        "activity",
        "maintenance"
    ]
}
dalibo@supervision:~$ curl -s -k https://localhost:3345/discover | python -m json.tool
{
    "cpu": 2,
    "hostname": "supervision.ws",
    "memory_size": 4138512384,
    "pg_data": "/var/lib/postgresql/11/main",
    "pg_port": "5433",
    "pg_version": "PostgreSQL 11.5 (Debian 11.5-3.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit",
    "pg_version_summary": "PostgreSQL 11.5",
    "plugins": [
        "monitoring",
        "dashboard",
        "pgconf",
        "administration",
        "activity",
        "maintenance"
    ]
}
```

Cordialement,

**Comment by madtibo** [comment]
My error was linked to a problem in temboard toolkit, solved by this [commit](https://github.com/dalibo/temboard-toolkit/commit/f342591bcdd8e14f014ac384ff56d0956d64d486)
So problem solved on my side.
Thanks!

**Comment by bersace** [comment]
Closing.
