### ISSUE TITLE
Bounced Server Hosting temboard; temboard Will Not Function Now

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#691]
The server that hosts our main temboard server instance was bounced about a week ago. I was out of the office. When I returned, temboard wasn't responding so I bounced the service. It took a very long time to start (tens of minutes).

When I was finally able to reach the GUI in Chrome, all targets were not reporting anything; we would just see a spinning circle. No metrics were being collected. The instance has been up for some time now and we still see this. This essentially means our enterprise monitoring is down. I do not have any solutions at this point. I tried vacuuming and analyzing all tables in the `monitoring` schema but this did not help.

This _might_ be related to:
https://github.com/dalibo/temboard/issues/684
???

When restarting the service, it takes around 2-5 minutes to actually "start" - for example:

```
2020-03-18 07:59:45,546 temboardui[14665]: [temboardui] INFO: Starting main process.
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR: Could not unserialize Task from JSON
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR: Unterminated string starting at: line 1 column 1877 (char 1876)
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR: Traceback (most recent call last):
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 216, in recover
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:     raw_dict = json.loads(l)
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:     return _default_decoder.decode(s)
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR:     obj, end = self.scan_once(s, idx)
2020-03-18 08:02:56,910 temboardui[14685]: [taskmanager] ERROR: ValueError: Unterminated string starting at: line 1 column 1877 (char 1876)
2020-03-18 08:02:56,989 temboardui[19421]: [services] INFO: Starting worker pool.
2020-03-18 08:02:56,991 temboardui[14685]: [services] INFO: Starting main.
2020-03-18 08:02:56,992 temboardui[19422]: [services] INFO: Starting scheduler.
2020-03-18 08:02:56,994 temboardui[14685]: [temboardui] INFO: Serving temboardui on https://...
```

It's worth mentioning that before the server itself was restarted, temboard was functioning properly. We had no issues with GUI response time. We are monitoring 35 targets/agents.

Please advise.

I can provide logs via email to keep details private.

**Comment by julmon** [comment]
Could try to remove `.tm.task_list` file located into temboard home directory and restart temboard.
Your file looks corrupted.

**Comment by bsislow** [comment]
I removed it - it was 21MB - and restarted temboard server. It is still very slow. I don't see any details on the dashboard (0 TPS and no load average for all targets). All targets still have the "spinning circle."

Does temboard server need time to "warm up?"

I am seeing more logged to the corresponding PostgreSQL log now at least... some locking:

```
2020-03-18 08:49:47 CDT [39586]: [4-1] user=postgres,db=temboard,app=[unknown],client=[local] LOG:  process 39586 acquired AccessShareLock on relation 4210957 of database 4210731 after 5583.681 ms
2020-03-18 08:49:47 CDT [39586]: [5-1] user=postgres,db=temboard,app=[unknown],client=[local] STATEMENT:
        SELECT
          current_database() AS dbname,
          SUM(bloat_size) / SUM(indexes_size) * 100 AS ratio
        FROM (
          SELECT
            SUM(pg_relation_size(quote_ident(schemaname) || '.' || quote_ident(indexname)))::BIGINT AS indexes_size
          FROM pg_catalog.pg_indexes
          GROUP BY schemaname
        ) AS indexes,
        (
          SELECT
            SUM(bloat_size) AS bloat_size,
            schemaname
          FROM (

        -- WARNING: executed with a non-superuser role, the query inspect only index on tables you are granted to read.
        -- WARNING: rows with is_na = 't' are known to have bad statistics ("name" type is not supported).
        -- This query is compatible with PostgreSQL 8.2 and after
        SELECT current_database(), nspname AS schemaname, tblname, idxname, bs*(relpages)::bigint AS real_size,
          bs*(relpages-est_pages)::bigint AS extra_size,
          100 * (relpages-est_pages)::float / relpages AS extra_ratio,
          fillfactor,
          CASE WHEN relpages > est_pages_ff
            THEN bs*(relpages-est_pages_ff)
            ELSE 0
          END AS bloat_size,
          100 * (relpages-est_pages_ff)::float / relpages AS bloat_ratio,
          is_na
          -- , 100-(pst).avg_leaf_density AS pst_avg_bloat, est_pages, index_tuple_hdr_bm, maxalign, pagehdr, nulldatawidth, nulldatahdrwidth, reltuples, relpages -- (DEBUG INFO)
        FROM (
          SELECT coalesce(1 +
                 ceil(reltuples/floor((bs-pageopqdata-pagehdr)/(4+nulldatahdrwidth)::float)), 0 -- ItemIdData size + computed avg size of a tuple (nulldatahdrwidth)
              ) AS est_pages,
              coalesce(1 +
                 ceil(reltuples/floor((bs-pageopqdata-pagehdr)*fillfactor/(100*(4+nulldatahdrwidth)::float))), 0
              ) AS est_pages_ff,
              bs, nspname, tblname, idxname, relpages, fillfactor, is_na
              -- , pgstatindex(idxoid) AS pst, index_tuple_hdr_bm, maxalign, pagehdr, nulldatawidth, nulldatahdrwidth, reltuples -- (DEBUG INFO)
          FROM (
              SELECT maxalign, bs, nspname, tblname, idxname, reltuples, relpages, idxoid, fillfactor,
                    ( index_tuple_hdr_bm +
                        maxalign - CASE -- Add padding to the index tuple header to align on MAXALIGN
                          WHEN index_tuple_hdr_bm%maxalign = 0 THEN maxalign
                          ELSE index_tuple_hdr_bm%maxalign
                        END
                      + nulldatawidth + maxalign - CASE -- Add padding to the data to align on MAXALIGN
                          WHEN nulldatawidth = 0 THEN 0
                          WHEN nulldatawidth::integer%maxalign = 0 THEN maxalign
                          ELSE nulldatawidth::integer%maxalign
                        END
                    )::numeric AS nulldatahdrwidth, pagehdr, pageopqdata, is_na
                    -- , index_tuple_hdr_bm, nulldatawidth -- (DEBUG INFO)
              FROM (
                  SELECT n.nspname, i.tblname, i.idxname, i.reltuples, i.relpages,
                      i.idxoid, i.fillfactor, current_setting('block_size')::numeric AS bs,
                      CASE -- MAXALIGN: 4 on 32bits, 8 on 64bits (and mingw32 ?)
                        WHEN version() ~ 'mingw32' OR version() ~ '64-bit|x86_64|ppc64|ia64|amd64' THEN 8
                        ELSE 4
                      END AS maxalign,
                      /* per page header, fixed size: 20 for 7.X, 24 for others */
                      24 AS pagehdr,
                      /* per page btree opaque data */
                      16 AS pageopqdata,
                      /* per tuple header: add IndexAttributeBitMapData if some cols are null-able */
                      CASE WHEN max(coalesce(s.null_frac,0)) = 0
                          THEN 2 -- IndexTupleData size
                          ELSE 2 + (( 32 + 8 - 1 ) / 8) -- IndexTupleData size + IndexAttributeBitMapData size ( max num filed per index + 8 - 1 /8)
                      END AS index_tuple_hdr_bm,
                      /* data len: we remove null values save space using it fractionnal part from stats */
                      sum( (1-coalesce(s.null_frac, 0)) * coalesce(s.avg_width, 1024)) AS nulldatawidth,
                      max( CASE WHEN i.atttypid = 'pg_catalog.name'::regtype THEN 1 ELSE 0 END ) > 0 AS is_na
                  FROM (
                      SELECT ct.relname AS tblname, ct.relnamespace, ic.idxname, ic.attpos, ic.indkey, ic.indkey[ic.attpos], ic.reltuples, ic.relpages, ic.tbloid, ic.idxoid, ic.fillfactor,
                          coalesce(a1.attnum, a2.attnum) AS attnum, coalesce(a1.attname, a2.attname) AS attname, coalesce(a1.atttypid, a2.atttypid) AS atttypid,
                          CASE WHEN a1.attnum IS NULL
                          THEN ic.idxname
                          ELSE ct.relname
                          END AS attrelname
                      FROM (
                          SELECT idxname, reltuples, relpages, tbloid, idxoid, fillfactor, indkey,
                              pg_catalog.generate_series(1,indnatts) AS attpos
                          FROM (
                              SELECT ci.relname AS idxname, ci.reltuples, ci.relpages, i.indrelid AS tbloid,
                                  i.indexrelid AS idxoid,
                                  coalesce(substring(
                                      array_to_string(ci.reloptions, ' ')
                                      from 'fillfactor=([0-9]+)')::smallint, 90) AS fillfactor,
                                  i.indnatts,
                                  pg_catalog.string_to_array(pg_catalog.textin(
                                      pg_catalog.int2vectorout(i.indkey)),' ')::int[] AS indkey
                              FROM pg_catalog.pg_index i
                              JOIN pg_catalog.pg_class ci ON ci.oid = i.indexrelid
                              WHERE ci.relam=(SELECT oid FROM pg_am WHERE amname = 'btree')
                              AND ci.relpages > 0
                          ) AS idx_data
                      ) AS ic
                      JOIN pg_catalog.pg_class ct ON ct.oid = ic.tbloid
                      LEFT JOIN pg_catalog.pg_attribute a1 ON
                          ic.indkey[ic.attpos] <> 0
                          AND a1.attrelid = ic.tbloid
                          AND a1.attnum = ic.indkey[ic.attpos]
                      LEFT JOIN pg_catalog.pg_attribute a2 ON
                          ic.indkey[ic.attpos] = 0
                          AND a2.attrelid = ic.idxoid
                          AND a2.attnum = ic.attpos
                    ) i
                    JOIN pg_catalog.pg_namespace n ON n.oid = i.relnamespace
                    JOIN pg_catalog.pg_stats s ON s.schemaname = n.nspname
                                              AND s.tablename = i.attrelname
                                              AND s.attname = i.attname
                    GROUP BY 1,2,3,4,5,6,7,8,9,10,11
              ) AS rows_data_stats
          ) AS rows_hdr_pdg_stats
        ) AS relation_stats
        ORDER BY nspname, tblname, idxname

          ) AS a
          GROUP BY schemaname
        ) AS ibloat
        WHERE schemaname !~ '^pg_temp'
        AND schemaname !~ '^pg_toast';

2020-03-18 08:49:47 CDT [33154]: [4-1] user=temboard,db=temboard,app=[unknown],client=[local] LOG:  process 33154 acquired RowExclusiveLock on relation 4210946 of database 4210731 after 247861.950 ms at character 38
2020-03-18 08:49:47 CDT [33154]: [5-1] user=temboard,db=temboard,app=[unknown],client=[local] STATEMENT:
                                INSERT INTO monitoring.metric_sessions_current
                                VALUES ('2020-03-17 18:23:57.24989-05', 37, 'metastore', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))
```

**Comment by bsislow** [comment]
This is essentially how the entire dashboard currently looks... redacted details for security:

![image](https://user-images.githubusercontent.com/30243584/76968158-6ee58300-68f6-11ea-971c-b16849f172e1.png)

**Comment by julmon** [comment]
Could you send me temboard and postgres logs at julmon@gmail.com please ?

**Comment by pgiraud** [comment]
It looks like this issue is not relevant anymore. @bsislow please reopen if it's not the case.
