### ISSUE TITLE
Error message in Configuration : Error  local variable 'categories' referenced before assignment

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard#738]
> Error  local variable 'categories' referenced before assignment

This message appears in a big red scary box when I change the value `autovacuum_vacuum_threshold` from the Configuration. The value is correctly set in `postgresql.auto.conf` but the configuration reload is not done.

The problem appears for some parameters, most are okay. I could reproduce the problem with a few other parameters from the Autovacuum category. There is no error when I click on 'Reset the default'.

It seems to occur only on v12 instances (I have 2 Temboard instances, all is okay with 9.6 or v11 instances on both ; but all v12 instances show the error).

Traces : 

temboard-client.log :
```
2020-05-11 18:39:19,907 temboardagent[27289]: [httpd] INFO: client: monolithe.mondomaine.org request: "GET /profile?key=f04aecf24cc0ed8229a90aef1defe4de HTTP/1.1" 200 -
2020-05-11 18:39:19,927 temboardagent[27289]: [functions] DEBUG: [{u'setting': u'0.2', u'name': u'autovacuum_vacuum_scale_factor'}, {u'setting': u'4', u'name': u'autovacuum_max_workers'}, {u'setting': u'on', u'name': u'autovacuum'}, {u'setting': u'50', u'name': u'autovacuum_analyze_threshold'}, {u'setting': u'400000000', u'name': u'autovacuum_multixact_freeze_max_age'}, {u'setting': u'52', u'name': u'autovacuum_vacuum_threshold'}, {u'setting': u'-1', u'name': u'autovacuum_vacuum_cost_limit'}, {u'setting': u'2ms', u'name': u'autovacuum_vacuum_cost_delay'}, {u'setting': u'0.1', u'name': u'autovacuum_analyze_scale_factor'}, {u'setting': u'200000000', u'name': u'autovacuum_freeze_max_age'}, {u'setting': u'1min', u'name': u'autovacuum_naptime'}]
2020-05-11 18:39:19,927 temboardagent[27289]: [functions] DEBUG: ALTER SYSTEM SET autovacuum_vacuum_threshold TO '52'
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR: {'error': "Parameter autovacuum_vacuum_cost_delay can't be checked."}
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR: Traceback (most recent call last):
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/httpd.py", line 109, in response
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:     (code, message) = self.route_request()
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/httpd.py", line 263, in route_request
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:     return (200, func(http_context, self.app))
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/plugins/pgconf/__init__.py", line 29, in post_pg_conf
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:     return pgconf_functions.post_settings(conn, app.config, http_context)
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:   File "/usr/lib/python2.7/dist-packages/temboardagent/plugins/pgconf/functions.py", line 294, in post_settings
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR:     (setting['name']))
2020-05-11 18:39:27,146 temboardagent[27289]: [httpd] ERROR: HTTPError: Parameter autovacuum_vacuum_cost_delay can't be checked.
2020-05-11 18:39:27,147 temboardagent[27289]: [httpd] ERROR: {'error': "Parameter autovacuum_vacuum_cost_delay can't be checked."}
2020-05-11 18:39:27,147 temboardagent[27289]: [httpd] INFO: client: monolithe.mondomaine.org request: "POST /pgconf/configuration?key=f04aecf24cc0ed8229a90aef1defe4de HTTP/1.1" 406 -
```

temboard.log
```
2020-05-11 18:39:19,904 temboardui[28896]: [web] DEBUG: Proxying GET https://huge.monolithe.mondomaine.org:2350/profile?key=f04aecf24cc0ed8229a90aef1defe4de.
2020-05-11 18:39:19,907 temboardui[28896]: [web] DEBUG: Proxying POST https://huge.monolithe.mondomaine.org:2350/pgconf/configuration?key=f04aecf24cc0ed8229a90aef1defe4de.
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR: Unhandled Error:
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR: Traceback (most recent call last):
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 224, in error_middleware
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:     return func(request, *args)
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 403, in user_instance_middleware
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:     return func(request, address, port, *args)
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 262, in instance_middleware
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:     return callable_(request, *args)
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/web.py", line 426, in user_middleware
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:     return func(request, *args)
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/plugins/pgconf/__init__.py", line 93, in configuration_handler
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR:     configuration_categories=categories,
2020-05-11 18:39:27,150 temboardui[28896]: [web] ERROR: UnboundLocalError: local variable 'categories' referenced before assignment
2020-05-11 18:39:27,151 temboardui[28896]: [web] ERROR: Request failed: 500 local variable 'categories' referenced before assignment.
2020-05-11 18:39:27,152 temboardui[28896]: [access] ERROR: 500 POST /server/huge.monolithe.mondomaine.org/2350/pgconf/configuration (192.168.74.150) 7257.78ms
```

**Comment by Krysztophe** [comment]
```
$ apt-cache policy temboard*
temboard:
  Installé : 5.1-0dlb1stretch1
  Candidat : 5.1-0dlb1stretch1
 Table de version :
 *** 5.1-0dlb1stretch1 500
        500 http://apt.dalibo.org/labs stretch-dalibo/main amd64 Packages
        100 /var/lib/dpkg/status
...
temboard-agent:
  Installé : 5.1-0dlb1stretch1
  Candidat : 5.1-0dlb1stretch1
 Table de version :
 *** 5.1-0dlb1stretch1 500
        500 http://apt.dalibo.org/labs stretch-dalibo/main amd64 Packages
        500 http://apt.dalibo.org/labs stretch-dalibo/main all Packages
        100 /var/lib/dpkg/status
```
