### ISSUE TITLE
ERROR: Could not send mail; getaddrinfo() argument 2 must be integer or string

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#765]
Dear temBoard Team

since the upgrade from temBoard 4.x to 5.x, I do get the following error, whenever a email is send by temBoard.
With temBoard 6.1, I still have the same issue. With temBoard 4.x it used to work perfectly.

```
$ temboard --version
 INFO: Starting temboard 6.1.
temBoard 6.1
System Red Hat Enterprise Linux Server 7.8 (Maipo)
Python 2.7.5 (/usr/bin/python)
psycopg2 2.5.1 (dt dec pq3 ext)
Tornado 4.2.1
SQLAlchemy 0.9.8
alembic 0.8.3
```

```
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR: Could not send mail; getaddrinfo() argument 2 must be integer or string
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR: SMTP server may be misconfigured.
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR: Traceback (most recent call last):
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 885, in exec_worker
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 1048, in wrapper
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/__init__.py", line 302, in notify_state_change
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:     smtp_login, smtp_password,  smtp_from_addr)
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/application.py", line 810, in send_mail
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR:     "SMTP server may be misconfigured." % e)
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR: TemboardUIError: Could not send mail; getaddrinfo() argument 2 must be integer or string
2020-06-16 10:03:55,199 temboardui[9150]: [taskmanager] ERROR: SMTP server may be misconfigured.
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR: Unhandled error in worker:
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR: Traceback (most recent call last):
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 1040, in serve1
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:     self.worker_pool.serve1()
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 834, in serve1
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:     self.check_jobs()
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 935, in check_jobs
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:     message_out = job['out'].get(False)
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/multiprocessing/queues.py", line 135, in get
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR:     res = self._recv()
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR: TypeError: ('__init__() takes exactly 3 arguments (2 given)', <class 'temboardui.errors.TemboardUIError'>, ('Could not send mail; getaddrinfo() argument 2 must be integer or string\nSMTP server may be misconfigured.',))
2020-06-16 10:03:55,252 temboardui[2797]: [taskmanager] ERROR: Not stopping worker process.
```

These are my temBoard configuration settings:

```
[notifications]
# SMTP host
smtp_host = localhost
# SMTP port
smtp_port = 25
# SMTP TLS
smtp_tls = False
# SMTP login / password
smtp_login = None
smtp_password = None
# SMTP from address
smtp_from_addr = postgres@company.ch
# Twilio SMS service configuration
# twilio_account_sid = ACCOUNTSIDTOBECHANGED
# twilio_auth_token = AUTHTOKENTOBECHANGED
# twilio_from = FROMNUMBERTOBECHANGED
```

However, when I send an email via the mail command, it works perfectly.

`echo test | mail -s test -r postgres@company.ch wsescu@company.ch`

Do you have any recommandations, how I can fix this issue?

Best regards
William

**Comment by bersace** [comment]
Hi @wsescu . Thanks for the report. I'm investigating.

**Comment by bersace** [comment]
I reproduced. I'm working on a fix.

**Comment by wsescu** [comment]
Thank you @bersace for working on the fix

**Comment by bersace** [comment]
@wsescu What if you unset `smtp_port` and *empty* `smtp_tls` ?

**Comment by bersace** [comment]
@wsescu yes.

**Comment by wsescu** [comment]
If I try to send a test email with the new settings, I do get the following error:

2020-06-16 11:36:59,075 temboardui[13118]: [web] ERROR: Request failed: 500 Could not send mail; SMTP AUTH extension not supported by server.
2020-06-16 11:36:59,075 temboardui[13118]: [web] ERROR: SMTP server may be misconfigured..
2020-06-16 11:36:59,077 temboardui[13118]: [access] ERROR: 500 POST /json/test_email (10.50.241.85) 17.49ms

**Comment by bersace** [comment]
@wsescu try to unset `smtp_login` and `smtp_password` instead of setting them to `None`. There is no `None` in `temboard.conf`. Did you found this value somewhere in documentation ?

**Comment by wsescu** [comment]
Yes. In the docs it says that the default is None

https://temboard.readthedocs.io/en/v6/configuration/

This section groups SMTP and Twilio parameters to send notifications.

smtp_host SMTP host. Default: None
smtp_port SMTP port. Default: None
smtp_tls Enable TLS connexion. Default: False
smtp_login SMTP login. Default: None
smtp_password SMTP password. Default: None
smtp_from_addr SMTP from address. Default: None
twilio_account_sid Twillio account SID. Default: None
twilio_auth_token Twilio authentication token. Default: None
twilio_from Twilio from phone number Default: None

Will set it now like this:

```
[notifications]
# SMTP host
smtp_host = localhost
# SMTP port
# smtp_port = 25
# SMTP TLS
smtp_tls =
# SMTP login / password
smtp_login =
smtp_password =
```

**Comment by wsescu** [comment]
After changing the values, I still get the same error, when I send a test notification

```
[2020-06-16 11:49:27,930 temboardui[3614]: [web] ERROR: Request failed: 500 Could not send mail; SMTP AUTH extension not supported by server.
2020-06-16 11:49:27,930 temboardui[3614]: [web] ERROR: SMTP server may be misconfigured..
2020-06-16 11:49:27,931 temboardui[3614]: [access] ERROR: 500 POST /json/test_email (10.50.241.85) 88.25ms]([url](url))
```

**Comment by bersace** [comment]
> smtp_host SMTP host. Default: None

Hm, this is misleading. `None` here means empty.

**Comment by bersace** [comment]
Please test like this :

```
# SMTP login / password
# smtp_login =
# smtp_password =
```

**Comment by wsescu** [comment]
After changing the config file to the following values, it works:

```
[notifications]
# SMTP host
smtp_host = localhost
# SMTP port
# smtp_port = 25
# SMTP TLS
# smtp_tls =
# SMTP login / password
# smtp_login =
# smtp_password =
# SMTP from address
smtp_from_addr = postgres@company.ch
# Twilio SMS service configuration
# twilio_account_sid = ACCOUNTSIDTOBECHANGED
# twilio_auth_token = AUTHTOKENTOBECHANGED
# twilio_from = FROMNUMBERTOBECHANGED
```

Thanks a lot @bersace

**Comment by bersace** [comment]
Great. Still, I have some fixes to make this easier !

**Comment by wsescu** [comment]
At least to me, the documentation is a little misleading. ;-)
