### ISSUE TITLE
temboard-migratedb Upgrade Results in "ERROR: ProgrammingError: (InvalidSchemaName) no schema has been selected to create in"

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#771]
We are running this step before we start the upgraded temboard UI and it fails:

```
$ temboard-migratedb -c ./temboard.conf stamp
 INFO: Starting temboard-migratedb 6.1.
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 301, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 57, in main
ERROR:     getattr(self, command_method)(args)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 68, in command_stamp
ERROR:     alembic.command.stamp(alembic_cfg, 'head')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/command.py", line 355, in stamp
ERROR:     script.run_env()
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
ERROR:     util.load_python_file(self.dir, 'env.py')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 79, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 73, in run_migrations_online
ERROR:     context.run_migrations()
ERROR:   File "<string>", line 8, in run_migrations
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
ERROR:     self.get_context().run_migrations(**kw)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 299, in run_migrations
ERROR:     self._ensure_version_table()
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 250, in _ensure_version_table
ERROR:     self._version.create(self.connection, checkfirst=True)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/schema.py", line 707, in create
ERROR:     checkfirst=checkfirst)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1245, in _run_visitor
ERROR:     **kwargs).traverse_single(element)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 120, in traverse_single
ERROR:     return meth(obj, **kw)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 732, in visit_table
ERROR:     self.connection.execute(CreateTable(table))
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
ERROR:     return meth(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
ERROR:     return connection._execute_ddl(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
ERROR:     compiled
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
ERROR:     exc_info
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
ERROR:     reraise(type(exception), exception, tb=exc_tb)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
ERROR:     cursor.execute(statement, parameters)
ERROR: ProgrammingError: (InvalidSchemaName) no schema has been selected to create in
ERROR: LINE 2: CREATE TABLE alembic_version (
ERROR:                      ^
ERROR:  '\nCREATE TABLE alembic_version (\n\tversion_num VARCHAR(32) NOT NULL\n)\n\n' {}
ERROR: temboardui version is 6.1.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```

**Comment by bsislow** [comment]
Perhaps the repository schema is needed? I don't see this in our temboard database...

```
temboard=> \dn
    List of schemas
    Name     |  Owner
-------------+----------
 application | postgres
 monitoring  | postgres
 public      | postgres
(4 rows)
```

**Comment by bersace** [comment]
Hmm, we should put alembic table in `application` schema. Instead, we rely on public.

That's not easy to change now :/

**Comment by bsislow** [comment]
I figured out a workaround; we prefer to not have anything in public; in fact, we typically drop public immediately after creating databases. We see it as a security risk.

```temboard=# \c temboard temboard
You are now connected to database "temboard" as user "temboard".
temboard=> show search_path ;
      search_path
-----------------------
 temboard, application
(1 row)

temboard=> \q
pgstmb001v.prd:/home/postgres/bsislow(temboard:45221)$ temboard-migratedb -c ./temboard.conf stamp
 INFO: Starting temboard-migratedb 6.1.
 INFO: Database marked as up to date.
```

**Comment by bsislow** [comment]
We have a temboard login role but no schema. I forced temboard-migratedb to use the search_path result of application in this case...

Does this answer your question? I'm not sure it does...

**Comment by bersace** [comment]
Where does `temboard` schema come from ?

**Comment by bsislow** [comment]
There actually is no temboard schema in our environment; I updated the search_path to simply read:

```
temboard=> show search_path ;
      search_path
-----------------------
 application
(1 row)
```

**Comment by bersace** [comment]
@bsislow Yes, that's a good workaround. Still, i think temBoard should not use public.

**Comment by bsislow** [comment]
i agree. i will close this and would recommend upgrading documentation as you see fit. thanks.

**Comment by bsislow** [comment]
FYI, this is still happening with the v8 upgrade from v7.11...

**Comment by bsislow** [comment]
```
# sudo -u temboard temboard migratedb upgrade
INFO:  app: Using config file /etc/temboard/temboard.conf.
INFO:  migratedb: Upgrading database to version 007_drop-alembic.sql.
INFO:  migratedb: Upgrading database to version 008_monitoring-archive-wait-lock.sql.
ERROR:  app: Unhandled error:
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/site-packages/temboardui/toolkit/app.py", line 351, in entrypoint
	    retcode = self.main(argv, environ)
	  File "/usr/lib/python3.6/site-packages/temboardui/cli/app.py", line 145, in main
	    return command.main(args)
	  File "/usr/lib/python3.6/site-packages/temboardui/cli/migratedb.py", line 55, in main
	    migrator.apply(conn, version)
	  File "/usr/lib/python3.6/site-packages/temboardui/model/migrator.py", line 40, in apply
	    cur.execute(sql)
	psycopg2.errors.InvalidSchemaName: no schema has been selected to create in

ERROR:  app: temboardui version is 8.0.
ERROR:  app: This is a bug!
ERROR:  app: Please report traceback to https://github.com/dalibo/temboard/issues/new! Thanks!
```

**Comment by bersace** [comment]
Hi @bsislow, I didn't reproduced the bug but found something suspicous.

Can you edit 008_monitoring-archive-wait-lock.sql and prefix `archive_current_metrics` with `monitoring.archive_current_metrics` like this:

``` sql
CREATE OR REPLACE FUNCTION monitoring.archive_current_metrics(table_name TEXT, record_type TEXT, query TEXT) RETURNS TABLE(tblname TEXT, nb_rows INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_table_current TEXT;
  v_table_history TEXT;
  v_query TEXT;
  i INTEGER;
BEGIN
  v_table_current := table_name || '_current';
  v_table_history := table_name || '_history';
  -- Lock _current table to prevent concurrent updates
  EXECUTE 'LOCK TABLE ' || v_table_current || ' IN SHARE MODE';
  v_query := replace(query, '#history_table#', v_table_history);
  v_query := replace(v_query, '#current_table#', v_table_current);
  v_query := replace(v_query, '#record_type#', record_type);
  -- Move data into _history table
  EXECUTE v_query;
  GET DIAGNOSTICS i = ROW_COUNT;
  -- Truncate _current table
  EXECUTE 'TRUNCATE '||v_table_current;
  -- Return each history table name and the number of rows inserted
  RETURN QUERY SELECT v_table_history, i;
END;
$$;
```

Then rerun migratedb.

**Comment by bsislow** [comment]
I was able to bypass the issue again by setting `search_path`. I'm not sure if I can consider this resolved; shouldn't the code qualify the schema explicitly?

**Comment by bersace** [comment]
> I was able to bypass the issue again by setting `search_path`. I'm not sure if I can consider this resolved; shouldn't the code qualify the schema explicitly?

It should. I need to modify dev env to reproduce this easier. Please keep opened until I fixed this.
