### ISSUE TITLE
Error when posting new group

### ISSUE THREAD

**Issue by daamien** [dalibo/temboard#8]
I can't create a new group. The creation form hangs forerver:

Here's the log trace

```
2016-10-26 14:27:22,978 temboard[18043]: [temboard] INFO: Posting new group.
2016-10-26 14:27:22,991 temboard[18043]: [temboard] DEBUG: {u'new_group_name': u'test', u'description': u'test'}
2016-10-26 14:27:23,087 temboard[18043]: [temboard] DEBUG: Traceback (most recent call last):
2016-10-26 14:27:23,089 temboard[18043]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/handlers/manage/group.py", line 164, in post_group
2016-10-26 14:27:23,090 temboard[18043]: [temboard] DEBUG:     group_kind)
2016-10-26 14:27:23,093 temboard[18043]: [temboard] DEBUG:   File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/application.py", line 105, in add_group
2016-10-26 14:27:23,094 temboard[18043]: [temboard] DEBUG:     raise TemboardUIError(400, "Group '%s' ('%s') already exists." % (group_name, group_kind))
2016-10-26 14:27:23,095 temboard[18043]: [temboard] DEBUG: TemboardUIError: Group 'test' ('role') already exists.
2016-10-26 14:27:23,095 temboard[18043]: [temboard] ERROR: Group 'test' ('role') already exists.
2016-10-26 14:27:23,096 temboard[18043]: [temboard] INFO: Failed.
```

**Comment by daamien** [comment]
The latest commit removes the error but the form still hang forever 

2016-10-28 19:20:24,323 temboard[4803]: [temboard] INFO: 200 GET /manage/groups/role (90.78.76.123) 91.95ms
2016-10-28 19:20:24,389 temboard[4803]: [temboard] INFO: 200 GET /js/temboard.manage.group.js (90.78.76.123) 4.55ms
2016-10-28 19:20:32,028 temboard[4803]: [temboard] INFO: Posting new group.
2016-10-28 19:20:32,041 temboard[4803]: [temboard] DEBUG: {u'new_group_name': u'test2', u'description': u''}
2016-10-28 19:20:32,071 temboard[4803]: [temboard] INFO: Done.

When I refresh the page the group is correctly created and I can see it

**Comment by daamien** [comment]
I launched the server without the -d option and here's the output:

```
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7f34e81419f0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 604, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/async.py", line 12, in <lambda>
    IOLoop.instance().add_callback(lambda: callback(result))
  File "/usr/local/lib/python2.7/dist-packages/temboard-0.0.1-py2.7.egg/temboardui/handlers/base.py", line 144, in async_callback
    if async_result.secure_cookie != None and 'name' in async_result.secure_cookie and 'content' in async_result.secure_cookie:
AttributeError: 'JSONAsyncResult' object has no attribute 'secure_cookie'
```

**Comment by daamien** [comment]
Here's a suggested fix
