### ISSUE TITLE
[temboard-migratedb] Issue migrating to 7.2

### ISSUE THREAD

**Issue by Rodac** [dalibo/temboard#861]
Hello,

Trying to update temBoard from version 6.x to 7.2 , I'm not able to migrate : 
```bash
bash-4.2$ temboard-migratedb upgrade
 INFO: Starting temboard-migratedb 7.2.
 INFO: Found config file /etc/temboard/temboard.conf.
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade cd5b518ab5cf -> 48dc1c585e8, Add comment field to instances table
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 58, in main
ERROR:     getattr(self, command_method)(args)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 74, in command_upgrade
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
ERROR:     script.run_env()
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
ERROR:     util.load_python_file(self.dir, 'env.py')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online
ERROR:     context.run_migrations()
ERROR:   File "<string>", line 8, in run_migrations
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
ERROR:     self.get_context().run_migrations(**kw)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
ERROR:     step.migration_fn(**kw)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/versions/20200706_2d48dc1c585e8_add_comment_field_to_instance_table.py", line 22, in upgrade
ERROR:     schema='application')
ERROR:   File "<string>", line 8, in add_column
ERROR:   File "<string>", line 3, in add_column
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/operations/ops.py", line 1535, in add_column
ERROR:     return operations.invoke(op)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
ERROR:     return fn(self, operation)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 123, in add_column
ERROR:     schema=schema
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 172, in add_column
ERROR:     self._exec(base.AddColumn(table_name, column, schema=schema))
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
ERROR:     return conn.execute(construct, *multiparams, **params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
ERROR:     return meth(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
ERROR:     return connection._execute_ddl(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
ERROR:     compiled
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
ERROR:     exc_info
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
ERROR:     reraise(type(exception), exception, tb=exc_tb)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
ERROR:     cursor.execute(statement, parameters)
ERROR: ProgrammingError: (ProgrammingError) must be owner of relation instances
ERROR:  'ALTER TABLE application.instances ADD COLUMN comment TEXT' {}
ERROR: temboardui version is 7.2.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```

Here is the output of `temboard-migratedb -V` : 
temBoard 7.2
System CentOS Linux 7 (Core)
Python 2.7.5 (/usr/bin/python)
psycopg2 2.7.5 (dt dec pq3 ext lo64)
Tornado 4.2.1
SQLAlchemy 0.9.8
alembic 0.8.3

Thanks in advance for any help

**Comment by pgiraud** [comment]
Can you please try the following command?
```
sudo -u temboard temboard-migratedb upgrade
```

**Comment by Rodac** [comment]
That does the same

**Comment by pgiraud** [comment]
Could you please tell us what the current owner of the `application.instances` table is?
In a psql console:
```
\dt application.instances
```
What is the owner for other temboard tables?

**Comment by damienreyre** [comment]
Hello, I have the same issue like Rodac.
version 6.x to 7.2

temboard-migratedb -V
temBoard 7.2
System Debian GNU/Linux 10 (buster)
Python 2.7.16 (/usr/bin/python2.7)
psycopg2 2.7.7 (dt dec pq3 ext lo64)
Tornado 5.1.1
SQLAlchemy 1.3.19
alembic 1.4.3

temboard=# \dt application.instances
              Liste des relations
   Schéma    |    Nom    | Type  | Propriétaire
-------------+-----------+-------+--------------
 application | instances | table | postgres

Cheers,

Damien

**Comment by Rodac** [comment]
> Could you please tell us what the current owner of the `application.instances` table is?
> In a psql console:
> 
> ```
> \dt application.instances
> ```
> 
> What is the owner for other temboard tables?
```bash
temboard=# \dt application.instances
             List of relations
   Schema    |   Name    | Type  |  Owner   
-------------+-----------+-------+----------
 application | instances | table | postgres
```

- The database is owned by _temboard_
- The schemas are owned by _postgres_
```bash
temboard=# \dn+
                            List of schemas
    Name     |  Owner   |  Access privileges   |      Description       
-------------+----------+----------------------+------------------------
 application | postgres | postgres=UC/postgres+| 
             |          | temboard=UC/postgres | 
 monitoring  | postgres | postgres=UC/postgres+| 
             |          | temboard=UC/postgres | 
 public      | postgres | postgres=UC/postgres+| standard public schema
             |          | =UC/postgres         | 
(3 rows)
```

```bash
temboard=# \dt+ application.*
                                List of relations
   Schema    |         Name         | Type  |  Owner   |    Size    | Description 
-------------+----------------------+-------+----------+------------+-------------
 application | access_role_instance | table | postgres | 16 kB      | 
 application | alembic_version      | table | temboard | 8192 bytes | 
 application | groups               | table | postgres | 16 kB      | 
 application | instance_groups      | table | postgres | 48 kB      | 
 application | instances            | table | postgres | 16 kB      | 
 application | plugins              | table | postgres | 48 kB      | 
 application | role_groups          | table | postgres | 16 kB      | 
 application | roles                | table | postgres | 16 kB      | 
(8 rows)
```

**Comment by pgiraud** [comment]
@Rodac Thanks a lot for the details.
We'll try to come back with a solution as quickly as possible.

Quick note: in our dev or testing environnement, all relations are owned by the user `temboard`.
You may want to try to change this manually.

**Comment by Rodac** [comment]
> @Rodac Thanks a lot for the details.
> We'll try to come back with a solution as quickly as possible.
> 
> Quick note: in our dev or testing environnement, all relations are owned by the user `temboard`.
> You may want to try to change this manually.

Well, thanks for the tip. 
Actually, it lets the _temboard-migratedb_ works as expected.

To anyone dealing with the same issue : 
you could run the following requests : 
```sql
ALTER SCHEMA public OWNER TO temboard;
ALTER SCHEMA application OWNER TO temboard;
ALTER SCHEMA monitoring OWNER TO temboard;

ALTER TABLE application.access_role_instance OWNER TO temboard;
ALTER TABLE application.alembic_version OWNER TO temboard;
ALTER TABLE application.groups OWNER TO temboard;
ALTER TABLE application.instance_groups OWNER TO temboard;
ALTER TABLE application.instances OWNER TO temboard;
ALTER TABLE application.plugins OWNER TO temboard;
ALTER TABLE application.role_groups OWNER TO temboard;
ALTER TABLE application.roles OWNER TO temboard;
ALTER TABLE monitoring.check_changes OWNER TO temboard;
ALTER TABLE monitoring.check_states OWNER TO temboard;
ALTER TABLE monitoring.checks OWNER TO temboard;
ALTER TABLE monitoring.collector_status OWNER TO temboard;
ALTER TABLE monitoring.hosts OWNER TO temboard;
ALTER TABLE monitoring.instance_availability OWNER TO temboard;
ALTER TABLE monitoring.instances OWNER TO temboard;
ALTER TABLE monitoring.metric_bgwriter_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_bgwriter_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_bgwriter_current OWNER TO temboard;
ALTER TABLE monitoring.metric_bgwriter_history OWNER TO temboard;
ALTER TABLE monitoring.metric_blocks_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_blocks_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_blocks_current OWNER TO temboard;
ALTER TABLE monitoring.metric_blocks_history OWNER TO temboard;
ALTER TABLE monitoring.metric_btree_bloat_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_btree_bloat_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_btree_bloat_current OWNER TO temboard;
ALTER TABLE monitoring.metric_btree_bloat_history OWNER TO temboard;
ALTER TABLE monitoring.metric_cpu_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_cpu_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_cpu_current OWNER TO temboard;
ALTER TABLE monitoring.metric_cpu_history OWNER TO temboard;
ALTER TABLE monitoring.metric_db_size_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_db_size_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_db_size_current OWNER TO temboard;
ALTER TABLE monitoring.metric_db_size_history OWNER TO temboard;
ALTER TABLE monitoring.metric_filesystems_size_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_filesystems_size_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_filesystems_size_current OWNER TO temboard;
ALTER TABLE monitoring.metric_filesystems_size_history OWNER TO temboard;
ALTER TABLE monitoring.metric_heap_bloat_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_heap_bloat_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_heap_bloat_current OWNER TO temboard;
ALTER TABLE monitoring.metric_heap_bloat_history OWNER TO temboard;
ALTER TABLE monitoring.metric_loadavg_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_loadavg_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_loadavg_current OWNER TO temboard;
ALTER TABLE monitoring.metric_loadavg_history OWNER TO temboard;
ALTER TABLE monitoring.metric_locks_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_locks_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_locks_current OWNER TO temboard;
ALTER TABLE monitoring.metric_locks_history OWNER TO temboard;
ALTER TABLE monitoring.metric_memory_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_memory_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_memory_current OWNER TO temboard;
ALTER TABLE monitoring.metric_memory_history OWNER TO temboard;
ALTER TABLE monitoring.metric_process_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_process_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_process_current OWNER TO temboard;
ALTER TABLE monitoring.metric_process_history OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_connection_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_connection_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_connection_current OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_connection_history OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_lag_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_lag_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_lag_current OWNER TO temboard;
ALTER TABLE monitoring.metric_replication_lag_history OWNER TO temboard;
ALTER TABLE monitoring.metric_sessions_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_sessions_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_sessions_current OWNER TO temboard;
ALTER TABLE monitoring.metric_sessions_history OWNER TO temboard;
ALTER TABLE monitoring.metric_tblspc_size_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_tblspc_size_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_tblspc_size_current OWNER TO temboard;
ALTER TABLE monitoring.metric_tblspc_size_history OWNER TO temboard;
ALTER TABLE monitoring.metric_temp_files_size_delta_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_temp_files_size_delta_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_temp_files_size_delta_current OWNER TO temboard;
ALTER TABLE monitoring.metric_temp_files_size_delta_history OWNER TO temboard;
ALTER TABLE monitoring.metric_vacuum_analyze_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_vacuum_analyze_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_vacuum_analyze_current OWNER TO temboard;
ALTER TABLE monitoring.metric_vacuum_analyze_history OWNER TO temboard;
ALTER TABLE monitoring.metric_wal_files_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_wal_files_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_wal_files_current OWNER TO temboard;
ALTER TABLE monitoring.metric_wal_files_history OWNER TO temboard;
ALTER TABLE monitoring.metric_xacts_30m_current OWNER TO temboard;
ALTER TABLE monitoring.metric_xacts_6h_current OWNER TO temboard;
ALTER TABLE monitoring.metric_xacts_current OWNER TO temboard;
ALTER TABLE monitoring.metric_xacts_history OWNER TO temboard;
ALTER TABLE monitoring.state_changes OWNER TO temboard;
```

Then : 
```bash
sudo -u temboard temboard-migratedb upgrade

INFO: Starting temboard-migratedb 7.2.
 INFO: No config file found.
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade cd5b518ab5cf -> 48dc1c585e8, Add comment field to instances table
 INFO: Running upgrade 48dc1c585e8 -> d2120f410bb5, statements
 INFO: Database up to date.
```

**Comment by damienreyre** [comment]
Thanks for the information, but unfortunately, it's not working for me.

I run your following requests and I have the same issue :

```
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 58, in main
ERROR:     getattr(self, command_method)(args)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 74, in command_upgrade
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/command.py", line 298, in upgrade
ERROR:     script.run_env()
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 489, in run_env
ERROR:     util.load_python_file(self.dir, "env.py")
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/compat.py", line 250, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online
ERROR:     context.run_migrations()
ERROR:   File "<string>", line 8, in run_migrations
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
ERROR:     self.get_context().run_migrations(**kw)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/migration.py", line 511, in run_migrations
ERROR:     for step in self._migrations_fn(heads, self):
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/command.py", line 287, in upgrade
ERROR:     return script._upgrade_revs(revision, rev)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 369, in _upgrade_revs
ERROR:     for script in reversed(list(revs))
ERROR:   File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
ERROR:     self.gen.throw(type, value, traceback)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 194, in _catch_revision_errors
ERROR:     compat.raise_from_cause(util.CommandError(resolution))
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/compat.py", line 323, in raise_from_cause
ERROR:     reraise(type(exception), exception, tb=exc_tb)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 162, in _catch_revision_errors
ERROR:     yield
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 364, in _upgrade_revs
ERROR:     revs = list(revs)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/revision.py", line 765, in _iterate_revisions
ERROR:     requested_lowers = self.get_revisions(lower)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/revision.py", line 319, in get_revisions
ERROR:     return sum([self.get_revisions(id_elem) for id_elem in id_], ())
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/revision.py", line 324, in get_revisions
ERROR:     for rev_id in resolved_id
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/revision.py", line 324, in <genexpr>
ERROR:     for rev_id in resolved_id
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/revision.py", line 397, in _revision_for_ident
ERROR:     resolved_id,
ERROR: CommandError: Can't locate revision identified by '2678b1a78dfa'
ERROR: temboardui version is 7.2.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```

```
temboard=# \dt application.instances
              Liste des relations
   Schéma    |    Nom    | Type  | Propriétaire
-------------+-----------+-------+--------------
 application | instances | table | temboard
(1 ligne)

temboard=# \dn+
                             Liste des schémas
     Nom     | Propriétaire |    Droits d'accès    |      Description
-------------+--------------+----------------------+------------------------
 application | temboard     | temboard=UC/temboard |
 monitoring  | temboard     | temboard=UC/temboard |
 public      | temboard     | temboard=UC/temboard+| standard public schema
             |              | =UC/temboard         |
(3 lignes)

temboard=# \dt+ application.*
                                 Liste des relations
   Schéma    |         Nom          | Type  | Propriétaire |   Taille   | Description
-------------+----------------------+-------+--------------+------------+-------------
 application | access_role_instance | table | temboard     | 16 kB      |
 application | alembic_version      | table | temboard     | 8192 bytes |
 application | groups               | table | temboard     | 16 kB      |
 application | instance_groups      | table | temboard     | 16 kB      |
 application | instances            | table | temboard     | 16 kB      |
 application | plugins              | table | temboard     | 48 kB      |
 application | role_groups          | table | temboard     | 16 kB      |
 application | roles                | table | temboard     | 16 kB      |
(8 lignes)
```

Cheers,

**Comment by damienreyre** [comment]
```
temboard=# \dt+ monitoring.*
                                           Liste des relations
   Schéma   |                    Nom                    | Type  | Propriétaire |   Taille   | Description
------------+-------------------------------------------+-------+--------------+------------+-------------
 monitoring | check_changes                             | table | temboard     | 64 kB      |
 monitoring | check_states                              | table | temboard     | 176 kB     |
 monitoring | checks                                    | table | temboard     | 64 kB      |
 monitoring | collector_status                          | table | temboard     | 56 kB      |
 monitoring | hosts                                     | table | temboard     | 16 kB      |
 monitoring | instance_availability                     | table | temboard     | 72 kB      |
 monitoring | instances                                 | table | temboard     | 16 kB      |
 monitoring | metric_bgwriter_30m_current               | table | temboard     | 19 MB      |
 monitoring | metric_bgwriter_6h_current                | table | temboard     | 1672 kB    |
 monitoring | metric_bgwriter_current                   | table | temboard     | 414 MB     |
 monitoring | metric_bgwriter_history                   | table | temboard     | 27 MB      |
 monitoring | metric_blocks_30m_current                 | table | temboard     | 50 MB      |
 monitoring | metric_blocks_6h_current                  | table | temboard     | 4504 kB    |
 monitoring | metric_blocks_current                     | table | temboard     | 1148 MB    |
 monitoring | metric_blocks_history                     | table | temboard     | 103 MB     |
 monitoring | metric_btree_bloat_30m_current            | table | temboard     | 9976 kB    |
 monitoring | metric_btree_bloat_6h_current             | table | temboard     | 896 kB     |
 monitoring | metric_btree_bloat_current                | table | temboard     | 203 MB     |
 monitoring | metric_btree_bloat_history                | table | temboard     | 14 MB      |
 monitoring | metric_cpu_30m_current                    | table | temboard     | 15 MB      |
 monitoring | metric_cpu_6h_current                     | table | temboard     | 1304 kB    |
 monitoring | metric_cpu_current                        | table | temboard     | 293 MB     |
 monitoring | metric_cpu_history                        | table | temboard     | 32 MB      |
 monitoring | metric_db_size_30m_current                | table | temboard     | 36 MB      |
 monitoring | metric_db_size_6h_current                 | table | temboard     | 3280 kB    |
 monitoring | metric_db_size_current                    | table | temboard     | 819 MB     |
 monitoring | metric_db_size_history                    | table | temboard     | 45 MB      |
 monitoring | metric_filesystems_size_30m_current       | table | temboard     | 134 MB     |
 monitoring | metric_filesystems_size_6h_current        | table | temboard     | 12 MB      |
 monitoring | metric_filesystems_size_current           | table | temboard     | 4282 MB    |
 monitoring | metric_filesystems_size_history           | table | temboard     | 144 MB     |
 monitoring | metric_heap_bloat_30m_current             | table | temboard     | 9976 kB    |
 monitoring | metric_heap_bloat_6h_current              | table | temboard     | 896 kB     |
 monitoring | metric_heap_bloat_current                 | table | temboard     | 203 MB     |
 monitoring | metric_heap_bloat_history                 | table | temboard     | 11 MB      |
 monitoring | metric_loadavg_30m_current                | table | temboard     | 10 MB      |
 monitoring | metric_loadavg_6h_current                 | table | temboard     | 912 kB     |
 monitoring | metric_loadavg_current                    | table | temboard     | 219 MB     |
 monitoring | metric_loadavg_history                    | table | temboard     | 18 MB      |
 monitoring | metric_locks_30m_current                  | table | temboard     | 66 MB      |
 monitoring | metric_locks_6h_current                   | table | temboard     | 5944 kB    |
 monitoring | metric_locks_current                      | table | temboard     | 1522 MB    |
 monitoring | metric_locks_history                      | table | temboard     | 43 MB      |
 monitoring | metric_memory_30m_current                 | table | temboard     | 14 MB      |
 monitoring | metric_memory_6h_current                  | table | temboard     | 1224 kB    |
 monitoring | metric_memory_current                     | table | temboard     | 293 MB     |
 monitoring | metric_memory_history                     | table | temboard     | 27 MB      |
 monitoring | metric_process_30m_current                | table | temboard     | 13 MB      |
 monitoring | metric_process_6h_current                 | table | temboard     | 1136 kB    |
 monitoring | metric_process_current                    | table | temboard     | 256 MB     |
 monitoring | metric_process_history                    | table | temboard     | 27 MB      |
 monitoring | metric_replication_connection_30m_current | table | temboard     | 1744 kB    |
 monitoring | metric_replication_connection_6h_current  | table | temboard     | 192 kB     |
 monitoring | metric_replication_connection_current     | table | temboard     | 39 MB      |
 monitoring | metric_replication_connection_history     | table | temboard     | 1776 kB    |
 monitoring | metric_replication_lag_30m_current        | table | temboard     | 8192 bytes |
 monitoring | metric_replication_lag_6h_current         | table | temboard     | 8192 bytes |
 monitoring | metric_replication_lag_current            | table | temboard     | 8192 bytes |
 monitoring | metric_replication_lag_history            | table | temboard     | 8192 bytes |
 monitoring | metric_sessions_30m_current               | table | temboard     | 50 MB      |
 monitoring | metric_sessions_6h_current                | table | temboard     | 4504 kB    |
 monitoring | metric_sessions_current                   | table | temboard     | 1163 MB    |
 monitoring | metric_sessions_history                   | table | temboard     | 44 MB      |
 monitoring | metric_tblspc_size_30m_current            | table | temboard     | 34 MB      |
 monitoring | metric_tblspc_size_6h_current             | table | temboard     | 3072 kB    |
 monitoring | metric_tblspc_size_current                | table | temboard     | 771 MB     |
 monitoring | metric_tblspc_size_history                | table | temboard     | 42 MB      |
 monitoring | metric_temp_files_size_delta_30m_current  | table | temboard     | 43 MB      |
 monitoring | metric_temp_files_size_delta_6h_current   | table | temboard     | 3880 kB    |
 monitoring | metric_temp_files_size_delta_current      | table | temboard     | 979 MB     |
 monitoring | metric_temp_files_size_delta_history      | table | temboard     | 71 MB      |
 monitoring | metric_vacuum_analyze_30m_current         | table | temboard     | 8192 bytes |
 monitoring | metric_vacuum_analyze_6h_current          | table | temboard     | 8192 bytes |
 monitoring | metric_vacuum_analyze_current             | table | temboard     | 8192 bytes |
 monitoring | metric_vacuum_analyze_history             | table | temboard     | 8192 bytes |
 monitoring | metric_wal_files_30m_current              | table | temboard     | 11 MB      |
 monitoring | metric_wal_files_6h_current               | table | temboard     | 960 kB     |
 monitoring | metric_wal_files_current                  | table | temboard     | 221 MB     |
 monitoring | metric_wal_files_history                  | table | temboard     | 23 MB      |
 monitoring | metric_xacts_30m_current                  | table | temboard     | 46 MB      |
 monitoring | metric_xacts_6h_current                   | table | temboard     | 4208 kB    |
 monitoring | metric_xacts_current                      | table | temboard     | 1083 MB    |
 monitoring | metric_xacts_history                      | table | temboard     | 73 MB      |
 monitoring | state_changes                             | table | temboard     | 9864 kB    |

```

**Comment by pgiraud** [comment]
@damienreyre this is a different issue. I'm opening a new one with a description of the problem and a solution. https://github.com/dalibo/temboard/issues/862
