### ISSUE TITLE
URGENT - Cannot Start temboard UI - Hit a Bug Upgrading to 7.2

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard#864]
Encountered the following after upgrading package and then issuing `temboard-migratedb`. Please advise.

```
$ temboard-migratedb upgrade
 INFO: Starting temboard-migratedb 7.2.
 INFO: No config file found.
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 58, in main
ERROR:     getattr(self, command_method)(args)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 74, in command_upgrade
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
ERROR:     script.run_env()
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
ERROR:     util.load_python_file(self.dir, 'env.py')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 77, in run_migrations_online
ERROR:     % version_table_schema
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 721, in execute
ERROR:     return self._execute_text(object, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 870, in _execute_text
ERROR:     statement, parameters
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
ERROR:     exc_info
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
ERROR:     reraise(type(exception), exception, tb=exc_tb)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
ERROR:     cursor.execute(statement, parameters)
ERROR: ProgrammingError: (InsufficientPrivilege) permission denied for database temboard
ERROR:  'CREATE SCHEMA IF NOT EXISTS "application";' {}
ERROR: temboardui version is 7.2.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```

**Comment by pgiraud** [comment]
It looks like you are running the script with the wrong user. There's an error in the documentation that we should fix.
Can you please run the command using the following statement?
```
sudo -u temboard temboard-migratedb upgrade
```

**Comment by pgiraud** [comment]
Do you remember how you ran the `temboard-migratedb stamp` command when upgrading from 5 to 6 ?

**Comment by bsislow** [comment]
No, that's not in the shell history.

**Comment by pgiraud** [comment]
Can you please show what the privileges on the database and on the schemas?
In a `psql` console:
```
temboard # \n
temboard # \dn+
```

**Comment by bsislow** [comment]
```
postgres=# \c temboard postgres
You are now connected to database "temboard" as user "postgres".
temboard=# \n
invalid command \n
Try \? for help.
temboard=# \dn+
                            List of schemas
    Name     |  Owner   |  Access privileges   |      Description
-------------+----------+----------------------+------------------------
 application | postgres | postgres=UC/postgres+|
             |          | temboard=UC/postgres |
 dbaadmin    | postgres | postgres=UC/postgres+|
             |          | dpa_user=U/postgres  |
 monitoring  | postgres | postgres=UC/postgres+|
             |          | temboard=UC/postgres |
 public      | postgres | postgres=UC/postgres | standard public schema
(4 rows)
```

**Comment by pgiraud** [comment]
Can you please check what's temboard's database owner?
```
postgres=# \l
```

**Comment by pgiraud** [comment]
Can you also please tell us who's the owner of the following directories?
```
ls -l /etc/temboard/ /var/lib/temboard/
```

**Comment by bsislow** [comment]
```
temboard=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 pghero    | pghero   | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 temboard  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(5 rows)
```

```
total 4
drwxr-x--- 2 postgres postgres  76 Mar 20  2020 ssl
-rw-r----- 1 temboard temboard 702 Mar 27  2020 temboard.conf

/var/lib/temboard/:
total 24
-rw-r--r-- 1 temboard temboard 21504 Oct  9 08:08 server_tasks.db
```

**Comment by pgiraud** [comment]
@bsislow it seems like there's *actually* a `temboard` user on your system. I'd recommend you run the migrate commands using this user.

Also, it's a common usage that the `temboard` database is owned by the `temboard` user as well.

**Comment by bsislow** [comment]
still did not work:

```
 INFO: Starting temboard-migratedb 7.2.
 INFO: Found config file /etc/temboard/temboard.conf.
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade cd5b518ab5cf -> 48dc1c585e8, Add comment field to instances table
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 58, in main
ERROR:     getattr(self, command_method)(args)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/migratedb.py", line 74, in command_upgrade
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/command.py", line 174, in upgrade
ERROR:     script.run_env()
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 397, in run_env
ERROR:     util.load_python_file(self.dir, 'env.py')
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online
ERROR:     context.run_migrations()
ERROR:   File "<string>", line 8, in run_migrations
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 797, in run_migrations
ERROR:     self.get_context().run_migrations(**kw)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 312, in run_migrations
ERROR:     step.migration_fn(**kw)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/model/alembic/versions/20200706_2d48dc1c585e8_add_comment_field_to_instance_table.py", line 22, in upgrade
ERROR:     schema='application')
ERROR:   File "<string>", line 8, in add_column
ERROR:   File "<string>", line 3, in add_column
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/operations/ops.py", line 1535, in add_column
ERROR:     return operations.invoke(op)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/operations/base.py", line 318, in invoke
ERROR:     return fn(self, operation)
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 123, in add_column
ERROR:     schema=schema
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 172, in add_column
ERROR:     self._exec(base.AddColumn(table_name, column, schema=schema))
ERROR:   File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
ERROR:     return conn.execute(construct, *multiparams, **params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
ERROR:     return meth(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
ERROR:     return connection._execute_ddl(self, multiparams, params)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
ERROR:     compiled
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
ERROR:     exc_info
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
ERROR:     reraise(type(exception), exception, tb=exc_tb)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
ERROR:     context)
ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
ERROR:     cursor.execute(statement, parameters)
ERROR: ProgrammingError: (InsufficientPrivilege) must be owner of table instances
ERROR:  'ALTER TABLE application.instances ADD COLUMN comment TEXT' {}
ERROR: temboardui version is 7.2.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```

**Comment by bsislow** [comment]
i had to alter all tables to be owned by `temboard` as well.
