### ISSUE TITLE
temboard-migratedb :  relation "public.alembic_version" does not exist

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard#876]
The problem appears on 2 different TemBoard repositories, on 2 different Ubuntu 20.04 servers, both installed with packages from apt.dalibo.org some time ago.

Since the OS & packages were upgraded, TemBoard does not start anymore. I can't tell when exactly, these are rarely used, but all was okay a few months ago.

Summary: The log asks for a migration. `temboard-migratedb check` generates an error about a missing `alembic_version`. The `upgrade` totally fails.

```
$ apt-cache policy temboard
temboard:
  Installed: 7.3-0dlb1buster1
  Candidate: 7.3-0dlb1buster1
  Version table:
 *** 7.3-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
        100 /var/lib/dpkg/status
     7.2-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
     7.1-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
     7.0-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
     6.2-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
     6.1-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
     6.0-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
     5.1-0dlb1buster1 500
        500 http://apt.dalibo.org/labs buster-dalibo/main amd64 Packages
```
```
# systemctl status temboard
* temboard.service - temBoard Web UI
     Loaded: loaded (/usr/lib/systemd/system/temboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-11-02 15:33:03 CET; 1h 7min ago
    Process: 3496245 ExecStart=/usr/bin/env SYSTEMD=1 temboard -c /etc/temboard/temboard.conf (code=exited, status=1/FAILURE)
   Main PID: 3496245 (code=exited, status=1/FAILURE)

Nov 02 15:33:03 monolithe env[3496245]: Loaded plugin 'activity'.
Nov 02 15:33:03 monolithe env[3496245]: Loaded plugin 'dashboard'.
Nov 02 15:33:03 monolithe env[3496245]: Loaded plugin 'monitoring'.
Nov 02 15:33:03 monolithe env[3496245]: Loaded plugin 'pgconf'.
Nov 02 15:33:03 monolithe env[3496245]: Loaded plugin 'maintenance'.
Nov 02 15:33:03 monolithe env[3496245]: Loaded plugin 'statements'.
Nov 02 15:33:03 monolithe env[3496245]: temBoard database is uninitialized.
Nov 02 15:33:03 monolithe env[3496245]: Database is not up to date. Please use temboard-migratedb.
Nov 02 15:33:03 monolithe systemd[1]: temboard.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 15:33:03 monolithe systemd[1]: temboard.service: Failed with result 'exit-code'.
```

`temboard.log`:
```
$ cat /var/log/temboard/temboard.log
2020-11-02 15:33:03,806 temboardui[3496245]: [pluginsmgmt] INFO: Loaded plugin 'activity'.
2020-11-02 15:33:03,820 temboardui[3496245]: [pluginsmgmt] INFO: Loaded plugin 'dashboard'.
2020-11-02 15:33:03,821 temboardui[3496245]: [pluginsmgmt] INFO: Loaded plugin 'monitoring'.
2020-11-02 15:33:03,822 temboardui[3496245]: [pluginsmgmt] INFO: Loaded plugin 'pgconf'.
2020-11-02 15:33:03,823 temboardui[3496245]: [pluginsmgmt] INFO: Loaded plugin 'maintenance'.
2020-11-02 15:33:03,824 temboardui[3496245]: [pluginsmgmt] INFO: Loaded plugin 'statements'.
2020-11-02 15:33:03,862 temboardui[3496245]: [model] DEBUG: temBoard database is uninitialized.
2020-11-02 15:33:03,863 temboardui[3496245]: [app] CRITICAL: Database is not up to date. Please use temboard-migratedb.
```

Config file `/etc/temboard/temboard.log`
```
# Configuration initiated by /usr/share/temboard/auto_configure.sh on jeudi 26 septembre 2019, 15:53:45 (UTC+0200)
# ...
[temboard]
ssl_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
cookie_secret = dc7fe1d...
home = /var/lib/temboard
# Bind port
# defaut 8888
port = 3001
# Bind address
address = 0.0.0.0
cookie_secret=s...

[repository]
host = 
port = 5432
user = temboard
password = .....
dbname = temboard

[logging]
method=file
level = DEBUG
destination=/var/log/temboard/temboard.log

[monitoring]
purge_after = 60
```

Migration check:
```
temboard@monolithe:~$ temboard-migratedb check 
 INFO: Starting temboard-migratedb 7.3.
 INFO: Found config file /etc/temboard/temboard.conf.
/usr/lib/temboard/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
CRITI: Database is not up to date. Please use temboard-migratedb.
```

NB: I have the warning about psycopg2 on both servers. 

`/var/log/temboard/temboard.log` does not say anymor

In `postgresql.log` I can already see that `alembic_version` is missing:
```
2020-11-02 16:45:32 CET [4006801]: [3-1] user=temboard,db=temboard,app=[unknown],client=[local] ERROR:  relation "public.alembic_version" does not exist
2020-11-02 16:45:32 CET [4006801]: [4-1] user=temboard,db=temboard,app=[unknown],client=[local] STATEMENT:  ALTER TABLE public.alembic_version SET SCHEMA "application";
```
This table is nowhere to be found:
```
temboard=> \dn
     Liste des schémas
     Nom     | Propriétaire 
-------------+--------------
 application | temboard
 monitoring  | temboard
 public      | temboard
(3 lignes)

temboard=> \dt public.*
Aucune relation nommée « public.* » n'a été trouvée.

temboard=> \dt application.*
                    Liste des relations
   Schéma    |         Nom          | Type  | Propriétaire 
-------------+----------------------+-------+--------------
 application | access_role_instance | table | temboard
 application | groups               | table | temboard
 application | instance_groups      | table | temboard
 application | instances            | table | temboard
 application | plugins              | table | temboard
 application | role_groups          | table | temboard
 application | roles                | table | temboard
(7 lignes)
```

If I try an `upgrade`, it seems to think it must create everything, and fails:
```
temboard@monolithe:~$ temboard-migratedb upgrade
 INFO: Starting temboard-migratedb 7.3.
 INFO: Found config file /etc/temboard/temboard.conf.
/usr/lib/temboard/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade  -> e73c6bfce646, application
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):                                                                                                                                          
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint                                                                   
ERROR:     retcode = self.main(argv, environ)                                                                                                                                      
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 58, in main                                                                            
ERROR:     getattr(self, command_method)(args)                                                                                                                                     
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 74, in command_upgrade                                                                 
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')                                                                                                                            
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/command.py", line 298, in upgrade                                                                             
ERROR:     script.run_env()                                                                                                                                                        
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 489, in run_env                                                                         
ERROR:     util.load_python_file(self.dir, "env.py")                                                                                                                               
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file                                                                
ERROR:     module = load_module_py(module_id, path)                                                                                                                                
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/compat.py", line 250, in load_module_py                                                                  
ERROR:     mod = imp.load_source(module_id, path, fp)                                                                                                                              
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>                                                               
ERROR:     run_migrations_online()                                                                                                                                                 
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online                                                   
ERROR:     context.run_migrations()                                                                                                                                                
ERROR:   File "<string>", line 8, in run_migrations                                                                                                                                
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations                                                          
ERROR:     self.get_context().run_migrations(**kw)                                                                                                                                 
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/migration.py", line 522, in run_migrations                                                            
ERROR:     step.migration_fn(**kw)                                                                                                                                                 
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/versions/20200325_2de73c6bfce646_application.py", line 28, in upgrade                        
ERROR:     op.get_bind().execute(sqlfile('application'))                                                                                                                           
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute                                                                     
ERROR:     return meth(self, multiparams, params)                                                                                                                                  
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection                                                      
ERROR:     return connection._execute_clauseelement(self, multiparams, params)                                                                                                     
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement                                                      
ERROR:     distilled_params,                                                                                                                                                       
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context                                                            
ERROR:     e, statement, parameters, cursor, context                                                                                                                               
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception                                                     
ERROR:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e                                                                                                               
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context                                                            
ERROR:     cursor, statement, parameters, context                                                                                                                                  
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute                                                                
ERROR:     cursor.execute(statement, parameters)                                                                                                                                   
ERROR: ProgrammingError: (psycopg2.ProgrammingError) relation "roles" already exists                                                                                               
ERROR:                                                                                                                                                                             
ERROR: [SQL: SET search_path TO application, public;                                                                                                                               
ERROR:                                                                                                                                                                             
ERROR: CREATE TABLE roles (                                                                                                                                                        
ERROR:  role_name TEXT PRIMARY KEY,                                                                                                                                                
ERROR:  role_password TEXT NOT NULL,                                                                                                                                               
ERROR:  role_email TEXT,
ERROR:  role_phone TEXT,
ERROR:  is_active BOOLEAN NOT NULL DEFAULT true,
ERROR:  is_admin BOOLEAN NOT NULL DEFAULT false
ERROR: );
ERROR: 
ERROR: CREATE TABLE groups (
ERROR:  group_name TEXT NOT NULL,
ERROR:  group_description TEXT,
ERROR:  group_kind TEXT NOT NULL,
ERROR:  CHECK (group_kind IN ('instance', 'role')),
ERROR:  PRIMARY KEY (group_name, group_kind)
ERROR: );
ERROR: 
ERROR: CREATE TABLE instances (
ERROR:  agent_address TEXT NOT NULL,
ERROR:  agent_port INTEGER NOT NULL,
ERROR:  agent_key TEXT,
ERROR:  hostname TEXT NOT NULL,
ERROR:  cpu INTEGER,
ERROR:  memory_size BIGINT,
ERROR:  pg_port INTEGER,
ERROR:  pg_version TEXT,
ERROR:  pg_version_summary TEXT,
ERROR:  pg_data TEXT,
ERROR:  notify BOOLEAN DEFAULT true,
ERROR:  PRIMARY KEY (agent_address, agent_port)
ERROR: );
ERROR: 
ERROR: CREATE TABLE plugins (
ERROR:  agent_address TEXT NOT NULL,
ERROR:  agent_port INTEGER NOT NULL,
ERROR:  plugin_name TEXT NOT NULL,
ERROR:  PRIMARY KEY (agent_address, agent_port, plugin_name),
ERROR:  FOREIGN KEY (agent_address, agent_port) REFERENCES instances (agent_address, agent_port) ON DELETE CASCADE ON UPDATE CASCADE
ERROR: );
ERROR: 
ERROR: CREATE TABLE instance_groups (
ERROR:  agent_address TEXT NOT NULL,
ERROR:  agent_port INTEGER NOT NULL,
ERROR:  group_name TEXT NOT NULL,
ERROR:  group_kind TEXT NOT NULL DEFAULT 'instance' CHECK (group_kind = 'instance'),
ERROR:  FOREIGN KEY (agent_address, agent_port) REFERENCES instances (agent_address, agent_port) ON DELETE CASCADE ON UPDATE CASCADE,
ERROR:  FOREIGN KEY (group_name, group_kind) REFERENCES groups(group_name, group_kind) ON DELETE CASCADE ON UPDATE CASCADE,
ERROR:  PRIMARY KEY (agent_address, agent_port, group_name)
ERROR: );
ERROR: 
ERROR: CREATE TABLE role_groups (
ERROR:  role_name TEXT NOT NULL,
ERROR:  group_name TEXT NOT NULL,
ERROR:  group_kind TEXT NOT NULL DEFAULT 'role' CHECK (group_kind = 'role'),
ERROR:  PRIMARY KEY (role_name, group_name),
ERROR:  FOREIGN KEY (role_name) REFERENCES roles(role_name) ON DELETE CASCADE ON UPDATE CASCADE,
ERROR:  FOREIGN KEY (group_name, group_kind) REFERENCES groups(group_name, group_kind) ON DELETE CASCADE ON UPDATE CASCADE
ERROR: );
ERROR: 
ERROR: CREATE TABLE access_role_instance (
ERROR:  role_group_name TEXT NOT NULL,
ERROR:  role_group_kind TEXT NOT NULL DEFAULT 'role' CHECK (role_group_kind = 'role'),
ERROR:  instance_group_name TEXT NOT NULL,
ERROR:  instance_group_kind TEXT NOT NULL DEFAULT 'instance' CHECK (instance_group_kind = 'instance'),
ERROR:  PRIMARY KEY (role_group_name, instance_group_name),
ERROR:  FOREIGN KEY (role_group_name, role_group_kind) REFERENCES groups (group_name, group_kind) ON DELETE CASCADE ON UPDATE CASCADE,
ERROR:  FOREIGN KEY (instance_group_name, instance_group_kind) REFERENCES groups (group_name, group_kind) ON DELETE CASCADE ON UPDATE CASCADE
ERROR: );
ERROR: 
ERROR: GRANT ALL ON ALL TABLES IN SCHEMA application TO temboard;
ERROR: GRANT ALL ON ALL SEQUENCES IN SCHEMA application TO temboard;
ERROR: GRANT ALL ON SCHEMA application TO temboard;
ERROR: 
ERROR: -- Default administrator: admin/admin
ERROR: INSERT INTO roles VALUES ('admin', 'xiet7KLumux50Q2dmV/FBue2zqtexElavkVAKnEYN/rw2YLIn51TQsXb3u8FPm4wiuHUTtEjjvBIrtBPAgRMsA==', 'admin@change.me', NULL, true, true);
ERROR: INSERT INTO groups VALUES ('default', 'Default instance group', 'instance');
ERROR: INSERT INTO groups VALUES ('admin', 'Default admin role group', 'role');
ERROR: INSERT INTO role_groups VALUES ('admin', 'admin', 'role');
ERROR: INSERT INTO access_role_instance VALUES ('admin', 'role', 'default', 'instance');
ERROR: ]
ERROR: (Background on this error at: http://sqlalche.me/e/13/f405)
ERROR: temboardui version is 7.3.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```

BTW: the owner of schemas and tables was `postgres`, and not `temboard`, on both instances. Of course, correcting this didn't solve anything.

**Comment by Krysztophe** [comment]
I've just tried it again. After another migration, the two UIs seems to works.

(Honestly, I don't remember their whole history since November. I may have reinstalled the or the other)

On my server, there was a rights problem:

```
temboard@monolithe:~$ temboard-migratedb upgrade
 INFO: Starting temboard-migratedb 7.8.
 INFO: Found config file /etc/temboard/temboard.conf.
/usr/lib/temboard/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade d2120f410bb5 -> 9fe3bfb83329, Grant privileges on statements objects
 INFO: Running upgrade 9fe3bfb83329 -> 67f52879da15, Grant privileges on statements objects (bis)
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 58, in main
ERROR:     getattr(self, command_method)(args)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 74, in command_upgrade
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/command.py", line 294, in upgrade
ERROR:     script.run_env()
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 490, in run_env
ERROR:     util.load_python_file(self.dir, "env.py")
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/compat.py", line 219, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online
ERROR:     context.run_migrations()
ERROR:   File "<string>", line 8, in run_migrations
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
ERROR:     self.get_context().run_migrations(**kw)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
ERROR:     step.migration_fn(**kw)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/versions/20210628_2d67f52879da15_grant_privileges_on_statements_objects_.py", line 25, in upgrade
ERROR:     """)
ERROR:   File "<string>", line 8, in execute
ERROR:   File "<string>", line 3, in execute
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/operations/ops.py", line 2123, in execute
ERROR:     return operations.invoke(op)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/operations/base.py", line 354, in invoke
ERROR:     return fn(self, operation)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 181, in execute_sql
ERROR:     operation.sqltext, execution_options=operation.execution_options
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/ddl/impl.py", line 149, in execute
ERROR:     self._exec(sql, execution_options)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/ddl/impl.py", line 146, in _exec
ERROR:     return conn.execute(construct, multiparams)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
ERROR:     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
ERROR:     self, multiparams, params, execution_options
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
ERROR:     cache_hit=cache_hit,
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
ERROR:     e, statement, parameters, cursor, context
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
ERROR:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
ERROR:     cursor, statement, parameters, context
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
ERROR:     cursor.execute(statement, parameters)
ERROR: ProgrammingError: (psycopg2.ProgrammingError) permission denied for schema statements
ERROR: 
ERROR: [SQL: 
ERROR:     GRANT ALL ON SCHEMA statements TO temboard;
ERROR:     GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA statements TO temboard;
ERROR:     GRANT ALL ON ALL TABLES IN SCHEMA statements TO temboard;
ERROR:     GRANT ALL ON ALL SEQUENCES IN SCHEMA statements TO temboard;
ERROR:     ]
ERROR: (Background on this error at: http://sqlalche.me/e/14/f405)
ERROR: temboardui version is 7.8.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!
```
The tables were belonging to `postgres`.
I suppose the temboard-migratedb should be run as postgres or root, or that temboard.conf should contain a superuser as `user`.
Anyway, I've run the GRANTS manually as a superuser, re-run `temboard-migratedb`, then everything is okay and the UI runs.

* On my laptop :

The UI was down but the migration worked immediately BUT the tables were belonging to `temboard`, not `postgres`.

```
temboard@monolithe:~$ temboard-migratedb upgrade
 INFO: Starting temboard-migratedb 7.8.
 INFO: Found config file /etc/temboard/temboard.conf.
/usr/lib/temboard/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade d2120f410bb5 -> 9fe3bfb83329, Grant privileges on statements objects
 INFO: Running upgrade 9fe3bfb83329 -> 67f52879da15, Grant privileges on statements objects (bis)
 INFO: Database up to date.
```

And then the UI was running.

**Comment by bersace** [comment]
`auto_configure.sh` always puts temboard role in `temboard.conf.d/auto.conf`. This is what temboard-migratedb uses. `temboard` database and schema are then owned by temboard role. Other scenario comes from old installation or manual intervention.
 We don't have an ownership fixer script.

**Comment by bersace** [comment]
Fixed in master.
