### ISSUE TITLE
ERROR: 'SELECT * FROM history_tables()' {}

### ISSUE THREAD

**Issue by wsescu** [dalibo/temboard#890]
Dear temBoard support

since the upgrade to temBoard version 7.5, we do have every 3 hours the following deadlocks in the PostgreSQL log file
and in the temboard log file.

From the PostgreSQL log file:

```
$ cat PG-postgresql-Wed.log | grep deadlock
2021-01-20 00:57:34.406 CET [9764] ERROR:  deadlock detected
2021-01-20 03:57:39.711 CET [20415] ERROR:  deadlock detected
2021-01-20 06:57:46.392 CET [4874] ERROR:  deadlock detected
2021-01-20 09:57:42.595 CET [20910] ERROR:  deadlock detected
2021-01-20 12:57:52.551 CET [6710] ERROR:  deadlock detected
2021-01-20 15:57:53.235 CET [23318] ERROR:  deadlock detected
2021-01-20 18:58:01.151 CET [7343] ERROR:  deadlock detected
2021-01-20 21:58:14.124 CET [23769] ERROR:  deadlock detected
```

From the temboard log file:

```
$ cat temboard.log-20210121 | grep deadlock
2021-01-20 03:57:39,799 temboardui[20414]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-20 03:57:39,799 temboardui[20414]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 03:57:39,813 temboardui[20414]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-20 03:57:39,813 temboardui[20414]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 06:57:46,424 temboardui[4873]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-20 06:57:46,424 temboardui[4873]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 06:57:46,434 temboardui[4873]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-20 06:57:46,434 temboardui[4873]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 09:57:42,657 temboardui[20909]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-20 09:57:42,657 temboardui[20909]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 09:57:42,725 temboardui[20909]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-20 09:57:42,725 temboardui[20909]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 12:57:52,563 temboardui[6709]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-20 12:57:52,563 temboardui[6709]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 12:57:52,698 temboardui[6709]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-20 12:57:52,698 temboardui[6709]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 15:57:53,335 temboardui[23316]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-20 15:57:53,335 temboardui[23316]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 15:57:53,352 temboardui[23316]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-20 15:57:53,352 temboardui[23316]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 18:58:01,229 temboardui[7342]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-20 18:58:01,229 temboardui[7342]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 18:58:01,245 temboardui[7342]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-20 18:58:01,245 temboardui[7342]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 21:58:14,178 temboardui[23768]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-20 21:58:14,178 temboardui[23768]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-20 21:58:14,221 temboardui[23768]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-20 21:58:14,221 temboardui[23768]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-21 00:58:31,325 temboardui[7479]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-21 00:58:31,325 temboardui[7479]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-21 00:58:31,344 temboardui[7479]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-21 00:58:31,344 temboardui[7479]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected

```

Detailed error from the PostgreSQL log file.

```
2021-01-21 12:58:34.900 CET [4136] ERROR:  deadlock detected
2021-01-21 12:58:34.900 CET [4136] DETAIL:  Process 4136 waits for ShareLock on relation 16820 of database 16566; blocked by process 4178.
        Process 4178 waits for RowExclusiveLock on relation 16778 of database 16566; blocked by process 4136.
        Process 4136: SELECT * FROM history_tables()
        Process 4178:
        INSERT INTO monitoring.metric_sessions_current
        VALUES ('2021-01-21T12:55:29.121626+01:00', 8, 'template1', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))

2021-01-21 12:58:34.900 CET [4136] HINT:  See server log for query details.
2021-01-21 12:58:34.900 CET [4136] CONTEXT:  SQL statement "LOCK TABLE metric_xacts_current IN SHARE MODE"
        PL/pgSQL function history_tables() line 14 at EXECUTE
2021-01-21 12:58:34.900 CET [4136] STATEMENT:  SELECT * FROM history_tables()
2021-01-21 12:58:34.901 CET [4247] LOG:  duration: 141522.046 ms  statement:
        INSERT INTO monitoring.metric_sessions_current
        VALUES ('2021-01-21T12:55:54.599037+01:00', 30, 'template1', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))

2021-01-21 12:58:34.902 CET [4183] LOG:  duration: 142056.081 ms  statement:
        INSERT INTO monitoring.metric_sessions_current
        VALUES ('2021-01-21T12:56:05.790668+01:00', 10, 'template1', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))

2021-01-21 12:58:34.902 CET [4204] LOG:  duration: 141901.111 ms  statement:
        INSERT INTO monitoring.metric_sessions_current
        VALUES ('2021-01-21T12:56:00.531801+01:00', 66, 'template1', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))

2021-01-21 12:58:34.902 CET [4181] LOG:  duration: 142085.686 ms  statement:
        INSERT INTO monitoring.metric_sessions_current
        VALUES ('2021-01-21T12:56:08.485293+01:00', 9, 'template1', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))

2021-01-21 12:58:34.908 CET [4254] LOG:  duration: 141473.892 ms  statement:
        INSERT INTO monitoring.metric_sessions_current
        VALUES ('2021-01-21T12:55:33.787220+01:00', 19, 'template1', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))

2021-01-21 12:58:34.909 CET [4173] LOG:  duration: 142107.528 ms  statement:
        INSERT INTO monitoring.metric_sessions_current
        VALUES ('2021-01-21T12:56:11.098032+01:00', 2, 'template1', (NULL, 0, 0, 0, 0, 0, 0, 0, 0))
```

Detailed error from the temboard log file:

```
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: Could not history montitoring tables
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: (TransactionRollbackError) deadlock detected
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: DETAIL:  Process 4136 waits for ShareLock on relation 16820 of database 16566; blocked by process 4178.
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: Process 4178 waits for RowExclusiveLock on relation 16778 of database 16566; blocked by process 4136.
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: HINT:  See server log for query details.
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: CONTEXT:  SQL statement "LOCK TABLE metric_xacts_current IN SHARE MODE"
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: PL/pgSQL function history_tables() line 14 at EXECUTE
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:  'SELECT * FROM history_tables()' {}
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: Traceback (most recent call last):
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/__init__.py", line 100, in history_tables_worker
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     res = conn.execute("SELECT * FROM history_tables()")
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 721, in execute
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     return self._execute_text(object, multiparams, params)
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 870, in _execute_text
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     statement, parameters
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     context)
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     exc_info
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     reraise(type(exception), exception, tb=exc_tb)
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     context)
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:     cursor.execute(statement, parameters)
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: DETAIL:  Process 4136 waits for ShareLock on relation 16820 of database 16566; blocked by process 4178.
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: Process 4178 waits for RowExclusiveLock on relation 16778 of database 16566; blocked by process 4136.
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: HINT:  See server log for query details.
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: CONTEXT:  SQL statement "LOCK TABLE metric_xacts_current IN SHARE MODE"
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR: PL/pgSQL function history_tables() line 14 at EXECUTE
2021-01-21 12:58:35,012 temboardui[4134]: [monitoring] ERROR:  'SELECT * FROM history_tables()' {}
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: <class 'sqlalchemy.exc.OperationalError'>: (TransactionRollbackError) deadlock detected
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: DETAIL:  Process 4136 waits for ShareLock on relation 16820 of database 16566; blocked by process 4178.
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: Process 4178 waits for RowExclusiveLock on relation 16778 of database 16566; blocked by process 4136.
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: HINT:  See server log for query details.
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: CONTEXT:  SQL statement "LOCK TABLE metric_xacts_current IN SHARE MODE"
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: PL/pgSQL function history_tables() line 14 at EXECUTE
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:  'SELECT * FROM history_tables()' {}
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: Traceback (most recent call last):
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 882, in exec_worker
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 1046, in wrapper
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/__init__.py", line 113, in history_tables_worker
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:     raise(e)
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: OperationalError: (TransactionRollbackError) deadlock detected
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: DETAIL:  Process 4136 waits for ShareLock on relation 16820 of database 16566; blocked by process 4178.
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: Process 4178 waits for RowExclusiveLock on relation 16778 of database 16566; blocked by process 4136.
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: HINT:  See server log for query details.
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: CONTEXT:  SQL statement "LOCK TABLE metric_xacts_current IN SHARE MODE"
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR: PL/pgSQL function history_tables() line 14 at EXECUTE
2021-01-21 12:58:35,041 temboardui[4134]: [taskmanager] ERROR:  'SELECT * FROM history_tables()' {}
```

Cheers
William

**Comment by pgiraud** [comment]
I just wanted to let you know that I managed to reproduce the issue. I don't have any clue about what's going on though.

**Comment by wsescu** [comment]
Dear @pgiraud 

I do have a workaround for that issue

https://ptdb.ch/2021/04/14/postgresql-temboard-workaround-for-the-error-select-from-history_tables/

However, it is inconvenient, because you need a downtime.

Cheers
William
