### ISSUE TITLE
Temboard-agent error : no more monitoring data available

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#894]
Hi,

One off my monitored server does no more display monitoring data.
Temboard server and temBoard agent are both in 7.5 version.

On the agent server, I get the following error:

> févr. 09 19:21:09 new-del1207w108 env[1516]: <class 'TypeError'>: datetime.datetime(2021, 2, 9, 19, 21, 9, 150267, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=60, name=None)) is not JSON serializable
févr. 09 19:21:09 new-del1207w108 env[1516]: Traceback (most recent call last):
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/toolkit/taskmanager.py", line 882, in exec_worker
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/toolkit/taskmanager.py", line 1046, in wrapper
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/plugins/monitoring/__init__.py", line 270, in monitoring_collector_worker
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/plugins/monitoring/db.py", line 49, in add_metric
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
févr. 09 19:21:09 new-del1207w108 env[1516]:     return _default_encoder.encode(obj)
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
févr. 09 19:21:09 new-del1207w108 env[1516]:     chunks = self.iterencode(o, _one_shot=True)
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
févr. 09 19:21:09 new-del1207w108 env[1516]:     return _iterencode(o, 0)
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/encoder.py", line 179, in default
févr. 09 19:21:09 new-del1207w108 env[1516]:     raise TypeError(repr(o) + " is not JSON serializable")
févr. 09 19:21:09 new-del1207w108 env[1516]: TypeError: datetime.datetime(2021, 2, 9, 19, 21, 9, 150267, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=60, name=None)) is not JSON serializable

Could it be related to Python version on the monitored server?
Thanks in advance for your help,

Cedric

**Comment by dlax** [comment]
> Could it be related to Python version on the monitored server?

I don't think so. It looks like a bug.

**Comment by dlax** [comment]
Hm. Are you sure about the temboard-agent version? Can you post the content of `/usr/lib/python3.5/dist-packages/temboardagent/plugins/monitoring/db.py` from line 48 to 51, please?

**Comment by ced75** [comment]
Thanks for your help.
I confirm the agent version:

> temboard-agent --version
 INFO: Starting temboard-agent 7.5.
7.5


Here is the content of `/usr/lib/python3/dist-packages/temboardagent/plugins/monitoring/db.py` from line 48 to 51:
```python
        c.execute(
            "INSERT INTO metrics VALUES(?, ?)",
            (time, json.dumps(data, cls=JSONEncoder))
        )
```

**Comment by pgiraud** [comment]
@ced75 is there both a `python3` and a `python3.5` directory in `/usr/lib` ?

**Comment by ced75** [comment]
Yes, but temBoard agent is in `python3` directory.

**Comment by pgiraud** [comment]
That's not what the logs tell.

**Comment by ced75** [comment]
Seems to be a conflict between the two directories...
How can I fix it?

**Comment by dlax** [comment]
Can you run these two commands?
```
dpkg -S /usr/lib/python3.5/dist-packages/temboardagent/
dpkg -S /usr/lib/python3/dist-packages/temboardagent/
```

**Comment by ced75** [comment]
`dpkg -S /usr/lib/python3.5/dist-packages/temboardagent/`:

> dpkg-query: aucun chemin ne correspond à /usr/lib/python3.5/dist-packages/temboardagent/

`dpkg -S /usr/lib/python3/dist-packages/temboardagent/`:

> temboard-agent: /usr/lib/python3/dist-packages/temboardagent

**Comment by dlax** [comment]
I think you can safely remove `/usr/lib/python3.5/dist-packages/temboardagent/` directory (as well as `/usr/lib/python3.5/dist-packages/temboard_agent-*.*.dist-info` one, if present in your installation). Then, please report back whether or not this resolves the issue.
