### ISSUE TITLE
Two agents on the same host issue Multiple rows were found for one() error

### ISSUE THREAD

**Issue by jeanloesch** [dalibo/temboard#898]
Hi,

I have temboard-7.4-1.el7.noarch installed on CentOS Linux 7.6.
I happen to have two running postgres servers on the same host lyn3e600.tlt
So I have two running agents using port 2345 and 2346 (temboard-agent-7.1-1.el7.noarch).

I have these errors in my log file /var/log/temboard/temboard.log on the temboard server.

```
2021-03-25 12:30:35,412 temboardui[129552]: [taskmanager] ERROR:     Instances.hostname == hostname,
2021-03-25 12:30:35,412 temboardui[129552]: [taskmanager] ERROR:   File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2404, in one
2021-03-25 12:30:35,412 temboardui[129552]: [taskmanager] ERROR:     "Multiple rows were found for one()")
2021-03-25 12:30:35,412 temboardui[129552]: [taskmanager] ERROR: MultipleResultsFound: Multiple rows were found for one()
2021-03-25 12:32:37,272 temboardui[130508]: [taskmanager] ERROR: <class 'sqlalchemy.orm.exc.MultipleResultsFound'>: Multiple rows were found for one()
2021-03-25 12:32:37,272 temboardui[130508]: [taskmanager] ERROR: Traceback (most recent call last):
2021-03-25 12:32:37,272 temboardui[130508]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 882, in exec_worker
2021-03-25 12:32:37,272 temboardui[130508]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2021-03-25 12:32:37,272 temboardui[130508]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/toolkit/taskmanager.py", line 1046, in wrapper
2021-03-25 12:32:37,272 temboardui[130508]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2021-03-25 12:32:37,272 temboardui[130508]: [taskmanager] ERROR:   File "/usr/lib/python2.7/site-packages/temboardui/plugins/monitoring/__init__.py", line 247, in notify_state_change


temboard=# select hostname from application.instances where hostname='lyn3e600.tlt';
   hostname
--------------
 lyn3e600.tlt
 lyn3e600.tlt
```

Could you please tell me how to fix these errors ?

Thank you.

Regards.

**Comment by bersace** [comment]
Hi @jeanloesch the looks like the port of the monitored instance is the same on both agent. Are you sure both agent are configured to monitor different instances ?

**Comment by jeanloesch** [comment]
Hi,

Yes I am sure. In fact on the host lyn3e600.tlt, my two instances both listen on port 5432 but each instance uses a different network interface.

Regards.

**Comment by bersace** [comment]
@jeanloesch so you have two Postgres instances with same hostname, same port but only the `listen_address` differs ? temboard is not able to manage this as monitoring data are identified by (hostname, port) key.

**Comment by jeanloesch** [comment]
Hi,

Thank you very much for your explanation.

Regards.
