### ISSUE TITLE
Temboard UI server failure after upgrade

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard#933]
Hi, we have upgraded our temboard server to temboard 7.8 (Debian buster).
The upgraded required to execute temboard-migratedb, which I did as follow:
`sudo -u temboard temboard-migratedb upgrade`

But the script generates the following error message:

>  INFO: Starting temboard-migratedb 7.8.
 INFO: Found config file /etc/temboard/temboard.conf.
/usr/lib/temboard/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 INFO: Context impl PostgresqlImpl.
 INFO: Will assume transactional DDL.
 INFO: Running upgrade d2120f410bb5 -> 9fe3bfb83329, Grant privileges on statements objects
 INFO: Running upgrade 9fe3bfb83329 -> 67f52879da15, Grant privileges on statements objects (bis)
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/toolkit/app.py", line 298, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 58, in main
ERROR:     getattr(self, command_method)(args)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/migratedb.py", line 74, in command_upgrade
ERROR:     alembic.command.upgrade(alembic_cfg, 'head')
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/command.py", line 294, in upgrade
ERROR:     script.run_env()
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/script/base.py", line 490, in run_env
ERROR:     util.load_python_file(self.dir, "env.py")
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
ERROR:     module = load_module_py(module_id, path)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/util/compat.py", line 219, in load_module_py
ERROR:     mod = imp.load_source(module_id, path, fp)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 100, in <module>
ERROR:     run_migrations_online()
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/env.py", line 94, in run_migrations_online
ERROR:     context.run_migrations()
ERROR:   File "<string>", line 8, in run_migrations
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
ERROR:     self.get_context().run_migrations(**kw)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
ERROR:     step.migration_fn(**kw)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/temboardui/model/alembic/versions/20210628_2d67f52879da15_grant_privileges_on_statements_objects_.py", line 25, in upgrade
ERROR:     """)
ERROR:   File "<string>", line 8, in execute
ERROR:   File "<string>", line 3, in execute
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/operations/ops.py", line 2123, in execute
ERROR:     return operations.invoke(op)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/operations/base.py", line 354, in invoke
ERROR:     return fn(self, operation)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 181, in execute_sql
ERROR:     operation.sqltext, execution_options=operation.execution_options
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/ddl/impl.py", line 149, in execute
ERROR:     self._exec(sql, execution_options)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/alembic/ddl/impl.py", line 146, in _exec
ERROR:     return conn.execute(construct, multiparams)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
ERROR:     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
ERROR:     self, multiparams, params, execution_options
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
ERROR:     cache_hit=cache_hit,
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
ERROR:     e, statement, parameters, cursor, context
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
ERROR:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
ERROR:     cursor, statement, parameters, context
ERROR:   File "/usr/lib/temboard/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
ERROR:     cursor.execute(statement, parameters)
ERROR: ProgrammingError: (psycopg2.ProgrammingError) permission denied for schema statements
ERROR: 
ERROR: [SQL: 
ERROR:     GRANT ALL ON SCHEMA statements TO temboard;
ERROR:     GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA statements TO temboard;
ERROR:     GRANT ALL ON ALL TABLES IN SCHEMA statements TO temboard;
ERROR:     GRANT ALL ON ALL SEQUENCES IN SCHEMA statements TO temboard;
ERROR:     ]
ERROR: (Background on this error at: http://sqlalche.me/e/14/f405)
ERROR: temboardui version is 7.8.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard/issues! Thanks!

How can I upgrade the temboard DB?

Thanks in advance for your help.

**Comment by bersace** [comment]
Hi @ced75 . How did you execute this command ? What is the owner of schema `statements` in temboard database ?

**Comment by ced75** [comment]
Hi @bersace 

I executed the update command from a sudoer admin user of the Linux server.
The owner of schema statements is postgres.
