### ISSUE TITLE
ValueError: Invalid FQDN: XXX.XXX.XXX.XXX

### ISSUE THREAD

**Issue by damienreyre** [dalibo/temboard#935]
Hello,

OS : Debian 11.1
temBoard : 7.8
temBoard-agent : 7.8

Since few days, I have a problem with my temboard-agent.
In my logs, I can see an error : 

`2021-10-22 09:51:08,500 temboardagent[21582]: [taskmanager] ERROR:     data = metrics.get_metrics(app)
2021-10-22 09:51:08,500 temboardagent[21582]: [taskmanager] ERROR:   File "/usr/lib/python3/dist-packages/temboardagent/plugins/dashboard/metrics.py", line 49, in get_metrics
2021-10-22 09:51:08,500 temboardagent[21582]: [taskmanager] ERROR:     hostname=sysinfo.hostname(app.config.temboard.hostname),
2021-10-22 09:51:08,500 temboardagent[21582]: [taskmanager] ERROR:   File "/usr/lib/python3/dist-packages/temboardagent/inventory.py", line 31, in hostname
2021-10-22 09:51:08,500 temboardagent[21582]: [taskmanager] ERROR:     raise ValueError("Invalid FQDN: %s" % (hostname))
2021-10-22 09:51:08,500 temboardagent[21582]: [taskmanager] ERROR: ValueError: Invalid FQDN: 192.168.150.169
2021-10-22 09:51:11,710 temboardagent[21613]: [taskmanager] ERROR: <class 'ValueError'>: Invalid FQDN: 192.168.150.169
2021-10-22 09:51:11,710 temboardagent[21613]: [taskmanager] ERROR: Traceback (most recent call last):
2021-10-22 09:51:11,710 temboardagent[21613]: [taskmanager] ERROR:   File "/usr/lib/python3/dist-packages/temboardagent/toolkit/taskmanager.py", line 882, in exec_worker
2021-10-22 09:51:11,710 temboardagent[21613]: [taskmanager] ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
2021-10-22 09:51:11,710 temboardagent[21613]: [taskmanager] ERROR:   File "/usr/lib/python3/dist-packages/temboardagent/toolkit/taskmanager.py", line 1046, in wrapper
2021-10-22 09:51:11,710 temboardagent[21613]: [taskmanager] ERROR:     return function(app=self.app, *a, **kw)
2021-10-22 09:51:11,710 temboardagent[21613]: [taskmanager] ERROR:   File "/usr/lib/python3/dist-packages/temboardagent/plugins/dashboard/__init__.py", line 115, in dashboard_collector_wor`

My configuration has not changed. In conf file temboard-agent.conf : hostname = hostname.domain.fr
When I try "hostname --fqdn", good value is returned.

I tried to delete server from temBoard-UI and re insert it via "temboard-agent-register", but I get another error : 

`CRITI: HTTP Error 500: Internal Server Error`

Cheers,

**Comment by damienreyre** [comment]
@daamien Hello Damien, do you have an idea about its problem ? 
Thanks.

**Comment by damienreyre** [comment]
Problem was double configuration : one by default and one by myself.
