### ISSUE TITLE
installation fails freebsd

### ISSUE THREAD

**Issue by fahadshery** [dalibo/temboard#979]
Hi,

I am trying to install temboard on the postgres server:
```python
pip install temboard psycopg2
Requirement already satisfied: temboard in /usr/local/lib/python3.8/site-packages (7.9)
Collecting psycopg2
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     |████████████████████████████████| 380 kB 1.9 MB/s
  Preparing metadata (setup.py) ... done
Requirement already satisfied: alembic in /usr/local/lib/python3.8/site-packages (from temboard) (1.7.5)
Requirement already satisfied: future in /usr/local/lib/python3.8/site-packages (from temboard) (0.18.2)
Requirement already satisfied: tornado<7,>=3.2 in /usr/local/lib/python3.8/site-packages (from temboard) (6.1)
Requirement already satisfied: python-dateutil>=1.5 in /usr/local/lib/python3.8/site-packages (from temboard) (2.8.2)
Requirement already satisfied: sqlalchemy>=0.9.8 in /usr/local/lib/python3.8/site-packages (from temboard) (1.4.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/site-packages (from python-dateutil>=1.5->temboard) (1.16.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.8/site-packages (from sqlalchemy>=0.9.8->temboard) (1.1.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.8/site-packages (from alembic->temboard) (1.1.6)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.8/site-packages (from alembic->temboard) (5.4.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.8/site-packages (from alembic->temboard) (4.10.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/site-packages (from importlib-metadata->alembic->temboard) (3.7.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.8/site-packages (from Mako->alembic->temboard) (2.0.1)
Using legacy 'setup.py install' for psycopg2, since package 'wheel' is not installed.
Installing collected packages: psycopg2
    Running setup.py install for psycopg2 ... done
Successfully installed psycopg2-2.9.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
when I run:
```python
temboard --version
```
I am getting the following error:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/temboard", line 5, in <module>
    from temboardui.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/temboardui/__main__.py", line 28, in <module>
    from .toolkit.proctitle import ProcTitleManager
  File "/usr/local/lib/python3.8/site-packages/temboardui/toolkit/proctitle.py", line 32, in <module>
    libc = ctypes.CDLL('libc.so.6')
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: Shared object "libc.so.6" not found, required by "python3.8"
```
I do have the `libc.so` on the system though:
```bash
find / -name libc.so
/usr/lib/libc.so
/usr/lib32/libc.so
```

how do I fix this issue?
thanks

**Comment by bersace** [comment]
Hi @fahadshery , thanks for reaching.

I'm sorry for you We do not support BSD as a target for executing temBoard. Maybe could we add support for BSD to temBoard agent one time, but again, our priority is otherway.

Porting the UI way be a quickwin, but not the agent monitoring code as of now. Do you have a workaround ?

I suggest to keep this issue open so as to keep this in mind.

Regards,

**Comment by daamien** [comment]
@fahadshery We had an internal discussion about this request and decided that the BSD family is not a target for us. 

Therefore we're closing this issue as a "WONT FIX"

Sorry about that.... Your other ticket (#978) remains open.
